### ISSUE TITLE
Frisbyjs specs not existing or being malformed do not fail Docker build

### ISSUE THREAD

**Issue by Krijger** [weaviate/weaviate#13]
Unfortunately, this is due to an issue in jasmine-node: https://github.com/mhevery/jasmine-node/issues/379. Maybe we should create a pull request, or this bug will mainly function as a warning. That bug has been filed sometime a year ago...

**Comment by Krijger** [comment]
This also makes an exception like

    Exception loading: /specs/a_spec.js
    { [Error: Cannot find module 'frisby'] code: 'MODULE_NOT_FOUND' }

not fail the build :(

**Comment by Krijger** [comment]
This issue is broader...
- Frisby appears to be dead - even all the forks have stopped 8 months ago
- Frisby cannot handle Jasmine 2 - Jasmine 1 is not maintained and not even downloadable in newer npm versions
- jasmine-node is an alternative to get stuff running, but that is long dead as well

**Comment by bobvanluijt** [comment]
O wow, news for me.

Let's look for an alternative...

**Comment by Krijger** [comment]
http://dareid.github.io/chakram/ could be an option.

**Comment by Krijger** [comment]
I looked at supertest as well, but that seemed a bit more 'involved' somehow. I have setup a working example in https://github.com/weaviate/weaviate/pull/14 using Chakram. That at least fixes this issue.
