### ISSUE TITLE
group (from entity merging feature) depends on order of elements

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#1302]
## Description
The grouping function considers something a match to a group as soon as an element in an existing group has a lower distance than the required max distance. This means that if there are multiple matches, we always group with the first match. In turn, this means that the groups may depend on the order of incoming elements.

Discovered as part of #1286 

## Possible Solution
Instead of making group match a binary decision, we could list all matches and pick the one with the lowest distance.

**Comment by dirkkul** [comment]
I think this is not valid anymore
