### ISSUE TITLE
Feature Parity between APIs (Search with REST, Add data with GraphQL)

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#1540]
# Goal
The APIs should have feature parity.

Currently, to get an e2e use case going I need to switch between REST and GraphQL which is annoying. Preferably, I would like to stay within one type of API. As a start REST should be extended with whatever capabilities are currently missing (mainly search).

Some differences are OK, as GraphQL is naturally better at resolving graph references, whereas REST is more link-based, but the overall capabilities should match.

## Capabilites
Currently the following capabilites are lacking
* GraphQL
  *  can't do writes 
  *  can't control classifications
* REST
  * can't search through classes using filters

.... possibly others, feel free to add

**Comment by bobvanluijt** [comment]
cc: @mingfang

**Comment by mingfang** [comment]
One strategy would to be make Graphql the "core" API and then make every other APIs(REST, language specific clients) wrap the GraphQL API.  This way we the maintenance for all the APIs and clients can be dramatically reduced.

For example, Hasura can "RESTifed" any Graphql API
https://hasura.io/docs/latest/graphql/core/api-reference/restified.html

**Comment by etiennedi** [comment]
Thanks for the suggestion. Maintaining APIs has not been a big issue in the past and for me it's really important that a REST-API feels restful ([e.g. HATEOAS etc.](https://martinfowler.com/articles/richardsonMaturityModel.html)), so I'm very hesitant to make the REST API dependent on an API that follows different principles. I'd rather invest a bit more time in making sure the REST API feels natural. Or - if we for whatever reason decide the REST API isn't important anymore - abandon it completely.

**Comment by etiennedi** [comment]
Still very releveant. :)

**Comment by etiennedi** [comment]
This needs to be split into smaller chunks, so they can be worked on in between larger tasks. We're otherwise never going to prioritize this.

**Comment by bobvanluijt** [comment]
What would the impact be planning-wise?

**Comment by etiennedi** [comment]
I think we can plan this as we wish. E.g. if we say we dedicate 10% of the time to this (whole team, specific person, etc.), then we'd reach feature parity in X days. If we dedicate 20% of the time, we'd reach it in X/2 days, etc.

What X is, I don't know yet, but I think this could be easily determined, by just planning what needs to be done and estimating how big or small those changes would be.

**Comment by etiennedi** [comment]
We could get started by imagining what the missing GraphQL (@laura-ham) and REST (@etiennedi) endpoints/functions should look like. That shouldn't take more than maybe an hour each and then we'd know what needs to be done.

**Comment by etiennedi** [comment]
This issue was created (and auto-closed) before we had the voting roadmap. Reopening so everyone can express their interest.

**Comment by julian-hoch** [comment]
Has any consensus been reached? The REST API still does not have feature parity, so it seems this is not a priority?

**Comment by dirkkul** [comment]
I think with GRPC being here now, we are not going to do this
