### ISSUE TITLE
Can't retrieve vector representation of cref

### ISSUE THREAD

**Issue by bobvanluijt** [weaviate/weaviate#1663]
As described in the title :-)

[Live example](https://console.semi.technology/console/query#weaviate_uri=https://demo.dataset.playground.semi.technology&graphql_query=%7B%0A%20%20Get%20%7B%0A%20%20%20%20Article(limit%3A%201)%20%7B%0A%20%20%20%20%20%20title%0A%20%20%20%20%20%20_additional%20%7B%0A%20%20%20%20%20%20%20%20vector%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20inPublication%20%7B%0A%20%20%20%20%20%20%20%20...%20on%20Publication%20%7B%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%09_additional%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20vector%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)

e.g.,

```graphql
{
  Get {
    Article(limit: 1) {
      title
      _additional {
        vector
      }
      inPublication {
        ... on Publication {
          name
        	_additional {
            vector
          }
        }
      }
    }
  }
}
```

**Comment by etiennedi** [comment]
Hm, I'm surprised this is even in the API, `_additional` properties are only defined at the root level. Is this something we could provide in general, @antas-marcin?

**Comment by etiennedi** [comment]
Fixed in the meantime, just validated.
