### ISSUE TITLE
Unify the filters "value" syntax

### ISSUE THREAD

**Issue by eostis** [weaviate/weaviate#1720]
There are currently many syntaxes for filter values, depending on the schema type and operator: 
`valeString, valueInt, valueDate, ...`

And soon perhaps: 
`valeString[], valueInt[], valueDate[]...
`
It would be nice to replace them with a simple syntax 'value' for all types. Weaviate should be able to validate the filter real value based on the property schema type and filter's operator.

Valid:
```
operator: Equal,  value: "1"
operator: Equal,  value: 1
operator: GreaterThan,  value: 1
operator: GreaterThan,  value: 1.345
operator: Any,  value: ["1", "2"] 
operator: All,  value: [1, 2]

```
Not valid:
```
operator: Equal,  value: ["1"]
operator: GreaterThan, value: "1"
operator: Any,  value: "1"
operator: All,  value: 1

```

(I used my proposition of array filter operator All and Any from #1719 )

**Comment by etiennedi** [comment]
I am intrigued by the simplicity of this. Question @laura-ham: a.) Is this possible/valid with GraphQLs typing system. b) If so, is it best practice?
