### ISSUE TITLE
Weaviate compile instructions

### ISSUE THREAD

**Issue by apiszcz** [weaviate/weaviate#1723]
Is there a URL or reference on compiling weaviate with go?, windows, linux, macos?

**Comment by gedw99** [comment]
I am on intel mac and trying to run it without docker. 

Does it need quoted flags like in your docker example ? 

Is there an example JSON config file in the repo anywhere ?

````

mkdir -p ./modules
weaviate-srv --host 0.0.0.0 --port 8080 --scheme http
{"action":"config_load","config_file_path":"./weaviate.conf.json","level":"info","msg":"no config file specified, using default or environment based","time":"2022-02-04T07:39:05+01:00"}
{"action":"startup","error":"invalid config: no authentication scheme configured, you must select at least one","level":"error","msg":"could not load config","time":"2022-02-04T07:39:05+01:00"}
make: *** [srv-run] Error 1

````

**Comment by etiennedi** [comment]
@gedw99 You need to specify the required environment variables. For example, see a user-facing [docker-based configuration here](https://configuration.semi.technology/v2/docker-compose/docker-compose.yml?enterprise_usage_collector=false&media_type=none&runtime=docker-compose&weaviate_version=v1.10.1). You don't need to use Docker, but you need to set the required vars.

Alternatively a typical [dev setup here](https://github.com/semi-technologies/weaviate/blob/0a03bb8ee64ceb8a5c11393643db3536e0ff2bbb/tools/dev/run_dev_server.sh#L31-L46) which you can run without docker. This example assumes running a `text2vec-contextionary` module, but you can also remove all modules if you like. 

Please also see the convenience scripts mentioned [here](https://www.semi.technology/developers/contributor-guide/v1.9.0/weaviate-core/setup.html). These are commonly used by the Core dev team during development. For running tests, see [here](https://www.semi.technology/developers/contributor-guide/v1.9.0/weaviate-core/tests.html).
