### ISSUE TITLE
Respect context in aggregations

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#1742]
It seems that currently when a long-running aggregation times out from a user's perspective the aggregation doesn't stop and still occupies resources. In the ideal case, the context cancellation of the request should immediately stop the Aggregation, i.e. anything that loops should check the context at the beginning of the loop. This way any cancelled or timed out request should free up resources as soon as it's done/aborted/timed out.

**Comment by dirkkul** [comment]
handled by https://github.com/weaviate/weaviate/issues/5842
