### ISSUE TITLE
Documentation search

### ISSUE THREAD

**Issue by chris-aeviator** [weaviate/weaviate#1891]
Great to meet weaviate - I wonder why a tool around search does not have a searchable documentation - anyone up to change that? If not please just disregard this issue.

**Comment by etiennedi** [comment]
Yes, this is absolutely a great point and something that's missing indeed. We had been talking about this internally for quite a while, but never got around to it. Now that we're scaling up the team this will surely find some priority soon.

**Comment by chris-aeviator** [comment]
Stalebots don’t make issues stale - commenting to unstale

**Comment by sky-2002** [comment]
Hello @etiennedi and @chris-aeviator , I am interested contributing to this, and I believe we can use weaviate itself to perform search on the documentation! Let me know what you guys think ..

**Comment by chris-aeviator** [comment]
Let’s go for it! Weaviate should be a perfect match here 🤓

**Comment by etiennedi** [comment]
FYI: This is not forgotten, just got pushed back a bit. @sebawita has some context on this.

**Comment by sebawita** [comment]
We are looking to do two projects at the same time. One is to migrate the documentation to a new framework (most likely docusaurus) and the second part is to add the search functionality (we just need to make sure that we have a fine-tuned model that can handle our docs) 🙏

**Comment by dandv** [comment]
We gave a [sneak peek into the documentation search in the February edition of the Weaviate Air (#5)](https://www.youtube.com/watch?v=a_yfl4jIXFQ&t=744s).
