### ISSUE TITLE
empty dates return error

### ISSUE THREAD

**Issue by raam86** [weaviate/weaviate#1916]
When trying to index missing date data weaviate returns an error. 

**Expected:**
Object is indexed as null 

**Current State:** 
an error is returned:
```
weaviate.exceptions.UnexpectedStatusCodeException: Creating object! Unexpected status code: 422, with response body: {'error': [{'message': "invalid object: invalid date property 'date' on class 'DemoDate': requires a string with a RFC3339 formatted date, but the given value is ''"}]}
```
**Reproduce:** 
```
import json
import weaviate

schema = {"classes": [{
    "class": "DemoDate",
    "description": "example schema for bug",
    "properties": [
    {
          "dataType": [
            "date"
          ],
          "description": "a date value that returns an error",
          "name": "created_at"
    }]}]}

results = []
date1 = {"date": ''}
date2 = {"date": None}
client = weaviate.Client("http://localhost:8080")
client.schema.create(schema)
res1 = client.data_object.create(date1, "DemoDate")
res2 = client.data_object.create(date2, "DemoDate")
print(res1)
print(res2)
```

**Comments:**
This also blows up when schema is not set and None is passed

**Comment by etiennedi** [comment]
Thanks for the investigation and the great reproducing example, @raam86. Out of curiosity, did you verify with dataTypes other than `date`. Basically, I'm wondering if this bug is unique to this data type or if others might be affected as well.

**Comment by raam86** [comment]
From my investigation this manifests in two ways: 
1. none obvious null types will return this error (e.g empty string is not a canonical null type for date, sometimes 1970 is used etc')
2. In python client, null json values are interpreted as `None` and sent to weaviate as such and we get the same error, so for the comments it happens for at least `date` and `text` types

**Comment by StefanBogdan** [comment]
Hi @etiennedi and @raam86 , this is known behaviour to me. Etienne I think we already had this discussion that we cannot send `None`/`null` values for a property, you could just not include that property in the object to be created and it is not going to be set at all. If I remember correctly this is due to the `dataType`, in this case `None`/`null` is not of data type `date`, this is why you cannot create it. Also you cannot query data with fields being `None`/`null` due to the inverted index.

**Comment by dirkkul** [comment]
I fixed many issues around null properties some time ago and this works now :)
