### ISSUE TITLE
Unmarshalling error

### ISSUE THREAD

**Issue by mtruyens** [weaviate/weaviate#2010]
The following object creation command: 

```
curl \
-X POST \
-H "Content-Type: application/json" \
-d '{"class":"ClauseEN","id":"12738542-2712-7882-7000-000000000000","properties":{"domain":"lh","nid":1278827,"pid":1003655,"customer_id":107,"aco_id":250,"content":"appointment distributor this contract not deemed constitute distributor an agent legal representative affiliate manufacturer purpose whatsoever expressly agreed that distributor solely responsible all obligations liabilities incurred assumed distributor performance obligations this contract"}}' \
http://localhost:8080/v1/objects
```

results in the error: 

`{"error":[{"message":"unmarshal response body: invalid character '<' looking for beginning of value"}]}`

This does not seem to be linked to CURL, as I'm getting the same error from my Java-based application (not using your Java client).

**Comment by mtruyens** [comment]
(error on my own side)

**Comment by etiennedi** [comment]
> From my application's perspective, however, the unmarshalling error seemed to originate from Weaviate; no context or indication about the fact that the error was actually triggered further down, was given.

Good point, this sounds like an annotation is missing that this error is indeed coming from the vectorizer.
