### ISSUE TITLE
Validate the schema files itself

### ISSUE THREAD

**Issue by johnciocoiu** [weaviate/weaviate#203]
In the Schema files, classes and their properties are defined. Every class has their properties. It could be that there are properties with equal names over multiple classes. In this case, these properties must have the same 'datatype' configured, otherwise saving them in the database will give issues.

Aswel, each property could have multiple data types. We have to fix that to only one datatype, because of having issues when saving them into a database. Otherwise will it be impossible to use some type of databases.

**Comment by bobvanluijt** [comment]
Moved to: https://github.com/weaviate/weaviate-semantic-schemas/issues/10
