### ISSUE TITLE
Bug: Explore should skip classes that are not vector-indexed, but not block search

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#2078]
## Reproduce + Actual Behavior 

https://link.semi.technology/3vDpdpK

```
vector search: search index article: shard article_SZAfi4UN1F77: vector search: cannot vector-search on a class not vector-indexed
```

## Desired Behavior

* If all classes lack a vector index -> error
* If some classes lack a vector index -> ignore those and search across all others

**Comment by bobvanluijt** [comment]
Tagging myself to follow this issue to update it in the docs

**Comment by bobvanluijt** [comment]
Suggestion: If multiple classes have different vector lengths, the size of the vector of the input ID or input vector should be used.

**Comment by etiennedi** [comment]
> Suggestion: If multiple classes have different vector lengths, the size of the vector of the input ID or input vector should be used.

I like the idea, I'll create a separate issue for this. Reason for the two issues: As outlined above it's a super simple fix, with checking the vector lengths it's a bit more effort because we don't really track the lengths yet. But we will need to do that soon anyway for the proper usage tracking.

**Comment by dirkkul** [comment]
closing this in favour of https://github.com/weaviate/weaviate/issues/2887
