### ISSUE TITLE
PUT /objects/{className}/{id} fails if payload does not include `"class"`

### ISSUE THREAD

**Issue by StefanBogdan** [weaviate/weaviate#2103]
I noticed that the implementation of the `client.data_object.replace` is failing with Weaviate version 1.14.1. This is the error:
```
UnexpectedStatusCodeException: Replace object! Unexpected status code: 422, with response body: {'error': [{'message': 'invalid object: the given class is empty'}]}
```

I tried the `curl` example from our docs and it worked:
```
curl \
    -X PUT \
    -H "Content-Type: application/json" \
    -d '{
      "class": "Test",
      "id": "c9f5484f-9ded-404a-93dc-5d521c19e766",
      "properties": {
          "content": "I love cats"
      }
  }' \
    http://localhost:8080/v1/objects/Test/c9f5484f-9ded-404a-93dc-5d521c19e766
```
The only difference between the Python client request and the `curl` is that the `curl` has the `"class": "Test"` but the python client does not add this anymore since the class namespacing. Shouldn't this work without the `"class": "Test"` in payload?

**Comment by StefanBogdan** [comment]
@redouan-rhazouani Is this behaviour supposed to be like this for `PUT`?

**Comment by etiennedi** [comment]
Great point. Redouan is OOO at the moment, maybe @aliszka or @parkerduckworth could have a look? This sounds like it could be a simple fix.

**Comment by parkerduckworth** [comment]
I have identified and fixed this issue. It actually does not affect the other 3 clients, because they implicitly handle passing the class name to the object.

However, even if we adjusted the python client to do the same, the issue persists when using a raw HTTP client.

This raises another question though: Do we need to enforce object id's presence in the request body, since it is also contained in the url?

**Comment by parkerduckworth** [comment]
@etiennedi yes, I see your point, so id should stay. My reasoning was this this seems a bit verbose:
```
curl localhost:8080/v1/objects/Post/1ce21489-5b2e-4097-b265-aae377515549 -X PUT \
  -d '{
          "id": "1ce21489-5b2e-4097-b265-aae377515549", 
          "properties": {"content": "some other contents!"}
      }' \
  -H 'content-type: application/json' | jq
```

But the clients abstract that extra `id` out anyway

**Comment by parkerduckworth** [comment]
This is no longer a problem as of Weaviate version `v1.15.0`
