### ISSUE TITLE
Improve Read-only message by adding reason 

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#2227]
In v1.15 there is only a single reason for "ready only" which is disk full. But v1.16 will add a second reason (#2226). Then it would be nicer to know why a shard is read-only.

**Comment by etiennedi** [comment]
This also applies to the WCS free tier. When a user reaches the free tier limit, the message is just "shard is read-only" which is not helpful. It would be good to customize the message so that it's clearer that the limit of the free tier has been reached.

**Comment by dirkkul** [comment]
done: https://github.com/weaviate/weaviate/pull/6044
