### ISSUE TITLE
Dynamic Scaling: Move shards around nodes, drain node, etc.

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#2228]

**Comment by mcapitanio** [comment]
Is there any planning for this feature?

**Comment by glesperance** [comment]
Going to production we would be excited to have this feature

**Comment by nchao-invitae** [comment]
this is an important feature for us, and so far the lack of mature replication features and documentation is causing us to consider other vector DB options than weaviate

**Comment by VjDharnish** [comment]
As mentioned above, other vector DBs have this functionality but weaviate does not. If you guys are working on it. kindly make it fast . Else mention users that we are not planned for this

**Comment by etiennedi** [comment]
Thanks, @nchao-invitae and @VjDharnish, for your feedback. I appreciate your openness about this becoming a blocker to the point that you are considering other databases. Shard movement is still a planned feature and it's great to see that more and more folks are demanding this. Initially we deprioritized it because we couldn't see enough demand for it. This has clearly changed in the meantime. To me that is a great sign of use cases maturing and more and more users running in production. 

At the moment, shard movement is next in line right after #3515 which is a major refactor required to make multi-node setups a lot more stable. That said, we are currently also looking into whether we can make some capacity available in parallel to start shard movement sooner than that. Either way, please expect an update in the next ~8 weeks.

**Comment by etiennedi** [comment]
For those waiting, ETA is `v1.25` - March 31.

**Comment by etiennedi** [comment]
Update: Possible delay, it might land in `v1.26`. Blocked by the GA release of [the RAFT-based schema](https://github.com/weaviate/weaviate/issues/4280) which we anticipate for `v1.25`. This topic will start in parallel, but can only happen after.

For MT cases, note that #4272 (planned for `v1.25`) will also contain some shard movement capabilities.

**Comment by dhanshew72** [comment]
@etiennedi Any target dates for 1.27 and/or this feature?

**Comment by VjDharnish** [comment]
Any update on this dynamic scaling functioanilty ??

**Comment by VjDharnish** [comment]
@etiennedi , any update on dynamic scaling ?

**Comment by pradippipaliya-inventyv** [comment]
Is this feature (dynamic scaling) available in current latest version?
