### ISSUE TITLE
Feature request: Authentication scheme for systems long-term credentials

### ISSUE THREAD

**Issue by samos123** [weaviate/weaviate#2341]
I'm trying to integrate Firestore with Weaviate, similarly to how it's done with [Elastic Search](https://firebase.google.com/docs/firestore/solutions/search?provider=elastic). However, Weaviate seems to only support authenticating with a short-term JWT token. 

I couldn't find an easy programmatic way of generating JWT tokens that Weaviate would accept. In my use case I was using WCS which is using SeMI Auth OpenID provider.

A simple mechanism could be supporting a static username/password to authenticate to Weaviate or to utilize mTLS for even higher levels of security. It was unclear whether this is already supported in Weaviate and the client libraries. For Firebase functions we have to use Javascript so that's what I tried using.

The core requirement here is to have some long-term credential that can be used to authenticate to a public Weaviate instance.

**Comment by samos123** [comment]
Looks like the Python Client does have a mechanism for refreshing the Access Token automatically for you if you supply it with your username/password: https://github.com/semi-technologies/weaviate-python-client/blob/5f6c93903dbc242d2df03a7ba9fd4fce0ceaf25b/weaviate/connect/connection.py#L166

and https://github.com/semi-technologies/weaviate-python-client/blob/5f6c93903dbc242d2df03a7ba9fd4fce0ceaf25b/weaviate/wcs/crud_wcs.py#L78

So that might be workable for usage with Javascript client as well, however doesn't look like the Javascript client has similar logic yet. Sadly, firebase functions only support javascript or typescript.

**Comment by etiennedi** [comment]
Added the backlog label to be able to vote for this on the roadmap. A vote for this issue is not a vote for a specific solution (we'll figure out what the right solution is when the time comes). But rather a vote is a feature that satisfies this:

> The core requirement here is to have some long-term credential that can be used to authenticate to a public Weaviate instance.

**Comment by etiennedi** [comment]
Would firebase work with a self-hosted Weaviate instance as well or would it have to be a Weaviate-Cloud-Service provisioned one? The latter would make this a bit more complex because then we'd also have to take the auth for the WCS into account. But if self-hosted works, then we could build the following:

* Weaviate will support basic auth, user/pwd combinations can be specified using env vars 
* User self-hosts Weaviate with the above auth configured and exposes it on the internet
* The firebase connector uses basic auth to authenticate against the instance with the credentials set in the first step.

Probably not the prettiest solution, but one that would be minimal effort to build.

**Comment by samos123** [comment]
Here are the requirements for Firebase integration:
* Weaviate exposed on the internet so it's accessible from Firebase functions
* Utilize the Javascript client so the JS client needs to be able to support the authentication mechanism

So yes self-hosted would work because this is just an example integration. That being said, the blog I wrote did use WCS but with authentication disabled, which was fine for demo/example usage.

I do see value in starting with basic auth as a simple option to expose a self-hosted Weaviate on the internet. I'm sure there are people who expose Weaviate publicly without really understanding that anyone can access their database. This option should make it very easy for self-hosted WCS users to at least prevent anonymous users to access the DB without requiring a full fledged OIDC server. I don't like dealing with OIDC unless I really have to.

Some customers hyper focused on security have very specific requirements on what kind of credentials are acceptable and what not. Maybe a guide that shows how to setup mTLS would be helpful later. Would mTLS work already? I think you could deploy a TLS proxy in front of Weaviate that does mTLS? What do you think? Each client would get it's own unique cert that could get revoked and traffic would be encrypted as well.

**Comment by wyzhangyuhan** [comment]
+1, need  "basic auth, user/pwd combinations can be specified using env vars"

**Comment by etiennedi** [comment]
Thanks for the feedback, please upvote the first post in this thread so your "+1" is counted :-)

**Comment by dirkkul** [comment]
Hi @samos123,

The JS client supports authentication with username/password with automatic refresh [since the latest version](https://github.com/semi-technologies/weaviate-javascript-client/releases/tag/v2.14.2). Java and go clients should follow in the next weeks.

We do not support using env variables, is that something that people would prefer?

**Comment by samos123** [comment]
Nice! I think supporting env vars isn't important since you could easily do that yourself while calling the client. It does seem common to support env vars though. E.g. AWS and gcloud all support providing credentials through env vars directly.

OIDC is painful to setup and requires yet another component that can break. Some users just want a simple password or username/password to protect their public weaviate instance. Especially at larger enterprises having to integrate with corporate OIDC provider can be a very tedious and painful process. I've setup Dex and used it as an OIDC provider for k8s in the past.

**Comment by dirkkul** [comment]
Totally understand, just want to highlight what we can support.

Another option that does not involve configuring an OIDC provider/server yourself would be to use our auth server with your own weaviate instance, like in this example [docker-compose file](https://github.com/semi-technologies/weaviate-python-client/blob/main/ci/docker-compose-wcs.yml). Then you can authenticate with your WCS username/pw (client credentials will hopefully be added to WCS in a bit).

Obviously that is nothing that works in a large enterprise, but for a small setup it might be an easy start.

**Comment by simon-gd** [comment]
having a user/password or a build-in key mechanism would really helpful!
