### ISSUE TITLE
indexNullState is not immutable

### ISSUE THREAD

**Issue by evenfrost** [weaviate/weaviate#2360]
An `invertedIndexConfig.indexNullState` schema property can be updated via `PUT /v1/schema/{className}`, but it should be immutable, as discussed [here](https://weaviate.slack.com/archives/C017EG2SL3H/p1668440795555049?thread_ts=1668440733.940009&cid=C017EG2SL3H).

**Comment by etiennedi** [comment]
Closing as complete
