### ISSUE TITLE
(breaking feature) Internally manage long texts embedding for all models and modules

### ISSUE THREAD

**Issue by eostis** [weaviate/weaviate#2375]
Hi,

I recently simply could not make a simple WooCommerce demo work, due to a variety of text length errors on different models and modules: #2335 #2336 #2357 

I believe that this sort of issue should be fixed internally and hidden from the mere mortals, who just want to use the vector search without a headache.

This is a problem that could make or break vector search as a mainstream technology, as it otherwise is impossible to use as a plug&play tool.

**Comment by trengrj** [comment]
Thanks for the points raised @eostis, agree these text length issues should not occur

- We do support chunking longer texts in [t2v-transformers-models](https://github.com/semi-technologies/t2v-transformers-models), but should make sure this works in other vectorization modules as well.
- A more controversial feature would be to enable truncation (at some limit) by default. This would also fix text length issues but could confuse some users.

cc @antas-marcin

**Comment by eostis** [comment]
I'm reopening it, because it's fundamental.

We should have an option when indexing (or at least in the class schema) to choose a chunking strategy.

A strong point of Weaviate is its ability to integrate data internally, and the same should apply to chunking. No need to use an external API like Langchain for that.
