### ISSUE TITLE
Add an `ContainsAny` & `ContainsAll` Filter Operators

### ISSUE THREAD

**Issue by lefnire** [weaviate/weaviate#2387]
From [Filters](https://weaviate.io/developers/weaviate/current/graphql-references/filters.html) we've got:

```
where: {
  operator: <operator>,
  operands: [{
    path: [path],
    operator: <operator>
    <valueType>: <value>
  }]
}
```
It would be nice to have an `In <operator>` and an `arrayValues <valueType>`, so one can do `{path: objId, operator: In, arrayValues: ['x', 'y', 'z']}`. 

Use-case (I think this will be more common than meets the eye): doing the data filtering inside the app database (eg Postgres) rather than Weaviate. Using Weaviate for just the ML stuff (vectors, summary, question-answering, etc). One case is the project was already built, and now we're adding vector-search. Wherever the filters (say, faceted search page) are already in place; no need to replicate the schema/filter system over to Weaviate. Another case is the filtering is complex in SQL, and we want to ping Weaviate with the final rows. This is my scenario, I'm using some wild SQL before I land on the rows I want to work with. 

Anyway, for now I'll roll with

```
where: {
  operator: Or
  operands: [{
    path: ["objId"]
    operator: Equals
    valueString: "x"
  }, { ... }, { ... }]
}
```

Hopefully there's not a perf penalty in so doing (or in the concept I'm feature-requesting either)?

**Comment by etiennedi** [comment]
Thanks for the request. I'll add the `backlog` label, so this appears on the website for voting.

**Comment by eostis** [comment]
Asked a year ago 'All' and 'Any' : #1719

**Comment by lakshaykc** [comment]
Are there any updates on this or plans when this will make into a release?

**Comment by ejball** [comment]
Another advantage would be the ability to use a GraphQL variable for the potentially large array.

**Comment by etiennedi** [comment]
I've added the `planned-1.20` label, for now, to indicate that this is indeed prioritized. However, there is a non-zero chance that we might pull this into 1.19 already. At the same time, we can't promise it yet. 1.19 is all about reliability and improvements and we've reserved capacity for (emergency) bug fixes. If there is capacity left over before the rc release, we can tackle this earlier than 1.20.

**Comment by etiennedi** [comment]
I think we could rely on GraphQL's [Input Coercion](https://spec.graphql.org/June2018/#sec-Scalars) to extend the existing types without adding breaking changes. In other words we can support:

```valueInt: 7```
and
```valueInt: [7,8,9]``` 
at the same time.

Then the only other thing we need to agree on is names for the operators. I like `In` because it's intuitive, but it only covers the case of matching any results (i.e. `OR` chaining). 

I also like the suggestion from @eostis to use `Any` and `All`. We could also combine both ideas and use `AnyIn` and `AllIn`, but that seems a bit verbose and the latter is very hard to read because of how similar the lowercase-L and the uppercase-I are.

**Comment by trengrj** [comment]
If we just go with `In` that is understandable.

If we go with `Any` and `All` users might get them confused with `Or` and `And`. One option here would be to prefix the operators with `Equal` as they are just the array version of `Equal` i.e. `EqualAny` and `EqualAll`.

**Comment by etiennedi** [comment]
> If we just go with `In` that is understandable.

Agreed.

> If we go with Any and All users might get them confused with Or and And. One option here would be to prefix the operators with Equal as they are just the array version of Equal i.e. EqualAny and EqualAll.

Also agreed. This raises two more questions for me:

1. What happens if the user specifies an array with any of the other operators? My suggestion would be that the request fails with a helpful error message. This message tells the user which operators support multiple values.
2. If we go for `EqualAny/EqualAll` then `EqualAny` would be the same as `In`. So, we would probably have to pick two out of those three options. What if we had `In` and `AllEqual`?  Or would it be more intuitive to then not go for `In` and instead of `AnyEqual` and `AllEqual`?

**Comment by etiennedi** [comment]
@klehmann, yes I think you could structure your schema to work with this. That said, I don't know how cumbersome it'll get to mix AuthZ topics with data. It sounds like the feature request for [Role-Based Access Control](https://github.com/weaviate/weaviate/issues/2784) could also be of interest to you.

**Comment by SomebodySysop** [comment]
> We would like to store an array of usernames, groups, and roles in a WeaviateObject to control who is allowed to read the object, e.g., ["CN=Karsten Lehmann/O=Mindoo", "AdministratorGroup", "[CanReadAll]"]. (Roles are enclosed in square brackets.)
> 
> For the current web application user, we then compute their name variants, groups, and roles, e.g., ["CN=Karsten Lehmann/O=Mindoo", "*/O=Mindoo", "SomeGroup123", "[SomeOtherRole]", " * "] and add this to the Weaviate query to only return Weaviate objects that the user is allowed to see (where both string arrays intersect, ignoring case).
> 
> This mimics the behavior of the HCL Domino Server. Providing this functionality in Weaviate would give us a chance to use Weaviate a primary database for Domino apps during migrations.
> 
> The feature request sounds as if it could handle this string array comparison so that we don't have to compose OR'ed Weaviate filters and might gain some performance benefits in the future.
> 
> We are highly interested in this feature!

Yes!  I have a similar use case.  I think both cases are resolved by being able to compare arrays.

I am developing an app for the Drupal CMS https://www.wpbeginner.com/research/cms-market-share-report-latest-trends-and-usage-stats/#:~:text=Drupal%20CMS%20Market%20Share,-0.71%25%20of%20all&text=6.82%25%20of%20the%20top%20100,4.3%25%20decrease%20in%2010%20years.  One of the advantages of Drupal is it's robust classification systems (primarily, "Groups" and "Taxonomy").

In adding a semantic search ability to a Drupal CMS, you want to include this classification information in the vector database as metadata, which not only preserves the organizational categorization of responses, but also helps enforce access control -- e.g. the Domino example above.  Users may need to search information that could belong to multiple groups and/or  have multiple taxonomies (tags).  We need to be able to add those options to the query prompts, which will be returned to the back-end process as arrays.  

Having a built-in query array to array operator would make this easier than the current method which would be to have a list of operators under the "And" or "Or" operand.

**Comment by SomebodySysop** [comment]
> 2\. f we go for `EqualAny/EqualAll` then `EqualAny` would be the same as `In`. So, we would probably have to pick two out of those three options. What if we had `In` and `AllEqual`?  Or would it be more intuitive to then not go for `In` and instead have `AnyEqual` and `AllEqual`?

Yes!  I like this.  It seems to resolve the array to array query issue.  Both mines and the one mentioned here: https://github.com/weaviate/weaviate/issues/2387#issuecomment-1476198364

This way, we can compare to see if any or all of the elements of one are in the other in a very clear manner.  This is perfect!  No need for "In" because "Like" and "Equal" already work as workarounds: https://weaviate.slack.com/archives/C017EG2SL3H/p1682315604981049

With just those two options, you eliminate the necessity of complex multiple operand queries to deal with array comparisons.  And, as more people begin to realize the necessity of having more strict access control as well as diverse classifications in their vector stores, you will see this "array to array" query need only grow.

**Comment by etiennedi** [comment]
See also [Forum Discussion about naming these new operators](https://forum.weaviate.io/t/api-feedback-naming-for-new-array-filters-operators/203/8).

**Comment by etiennedi** [comment]
Unfortunately had to move this from 1.20 to 1.21. I know this will disappoint a lot of you who have been waiting for this. But I promise that we will tackle this very early in the 1.21 release cycle and make a pre-release available as soon as it's ready. It came down to [Multi-Tenancy](https://weaviate.io/blog/multi-tenancy-vector-search) quality control vs implementing this and we decided we'd rather want to get to get multi-tenancy right than deliver two half-assed features. Thanks for understanding.

**Comment by SomebodySysop** [comment]
Appreciate the feedback.  Thank you.

**Comment by zoltan-fedor** [comment]
@etiennedi , do we know the timeline for v1.21 and/or the timeline for that pre-release?

**Comment by etiennedi** [comment]
V1.20 will be out later this week, so v1.21 dev basically starts next week. We should have this pre-release ready within two weeks.

**Comment by adaptivedavid** [comment]
The original comment seemed to be about finding results where the value of a `text` property is in an array of user-provided values (like a MongoDB `$in` operator). Will `ContainsAny` work on both `text` and `text[]` data types?

**Comment by kcm** [comment]
Though it would require a bit more work than `ContainsAny` and `ContainsAll`, `ContainsNone` would be highly useful for negative searching. For example, `text` fields tokenized by word are not currently filterable on a negative basis, since `NotEqual` applies as an "any" style operator.

**Comment by jeffcaf1** [comment]
@etiennedi any chance you have an updated estimate of when the Contains operator will be released in preview?

**Comment by bhavnicksm** [comment]
Hey @etiennedi! 
Any updates on when this feature is being released? 

Thanks ^^

**Comment by WilliamWhispell** [comment]
Will this require a new client release to npm package weaviate-client -or- what is needed to use it?

**Comment by WilliamWhispell** [comment]
https://weaviate.io/developers/weaviate/api/graphql/filters#containsany shows:

{
  Get {
    Person (
      where: {
        path: ["languages_spoken"],
        operator: ContainsAny,
        valueText: ["Chinese", "French", "English"]
      }
    )
    {
      languages_spoken
      name
    }
  }
}

Are the docs just ahead of support? Or am I misunderstanding what this PR is about? I tried to use:

`var query = client.graphql
            .get()
            .withClassName(classType)
            .withFields(`${fields.join(' ')}${vector ? ` _additional { id certainty }` : ' _additional { id }'}`)
         
if (where && where.length > 0) {
            where.forEach(({ path, value, operator = 'Equal' }) => {


                var valString = 'valueString'
                if (operator === 'ContainsAny' || operator === 'ContainsAll') {
                    valString = 'valueText'
                }

                query = query.withWhere({
                    "path": path,
                    [valString]: value,
                    "operator": operator
                });
            });
        }

My schema has property: 

  {
                "name": "categories",
                "description": "The user set categories.",
                "dataType": ["text[]"]
            }
`

ClientError: Argument "where" has invalid value {operator: ContainsAny, valueText: ["affiliate marketing", "amazon affiliate program "], path: ["categories"]}.
In field "valueText": Expected type "String", found ["affiliate marketing", "amazon affiliate program "].
In field "operator": Expected type "GetObjectsJustBlogArticleChunkWhereOperatorEnum", found ContainsAny.

**Comment by trengrj** [comment]
@WilliamWhispell please try with the latest weaviate python client. There was a delay in this feature being released in Weaviate and full client support.

@YanDavKMS can you please double check your weaviate python client version? Running python client (3.23.2) and docker image (1.21.2) I get:

```
In [16]: from importlib.metadata import version

In [17]: version("weaviate-client")
Out[17]: '3.23.2'

In [18]: client = weaviate.Client("http://localhost:8080")

In [19]: client.data_object.create({"name": "Movie description", "permissions": [1,2,3,4], "hierarchy_permissions": ["one", "two", "three"]}, "Movie")
Out[19]: 'ecffa938-4e60-4cab-94fe-f3934d99d3ef'

In [20]: client.query.get("Movie", ["name", "permissions"]).with_where({"operator": "ContainsAny", "path": ["permissions"], "valueNumber": [2,3]}).do()
Out[20]: 
{'data': {'Get': {'Movie': [{'name': 'Movie description',
     'permissions': [1, 2, 3, 4]}]}}}

In [21]: client.query.get("Movie", ["name", "permissions", "hierarchy_permissions"]).with_where({"operator": "ContainsAny", "path": ["hierarchy_permissions"], "valueText": ["one", "two"]}).do()
Out[21]: 
{'data': {'Get': {'Movie': [{'hierarchy_permissions': ['one', 'two', 'three'],
     'name': 'Movie description',
     'permissions': [1, 2, 3, 4]}]}}}

In [22]: client.cluster.get_nodes_status()
Out[22]: 
[{'batchStats': {'queueLength': 0, 'ratePerSecond': 0},
  'gitHash': '8e46731e4',
  'name': 'semi.local',
  'shards': [{'class': 'Movie', 'name': 'ZYgHxtTRO98k', 'objectCount': 1}],
  'stats': {'objectCount': 1, 'shardCount': 1},
  'status': 'HEALTHY',
  'version': '1.21.2'}]
  ```
  
I'm going to close this issue as #3370 has been released now in 1.21. Please feel free to raise any client issues on the relevant client repo or [community forum](https://forum.weaviate.io/).

**Comment by YanDavKMS** [comment]
I have tested the latest one. It has the same error.

**Comment by trengrj** [comment]
@YanDavKMS here is a notebook showing how it works with python client `3.23.2` and weaviate `1.12.1` https://colab.research.google.com/drive/1OiV8J4SupmoDBWJXTFBnI551oBg17DqU

**Comment by liechtym** [comment]
Everything is working for me! Thanks for this helpful update.
