### ISSUE TITLE
Add where filters to BM25(F) and Hybrid Search

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#2393]
As requested by @zoltan-fedor in #2134

**Comment by zoltan-fedor** [comment]
I think this (filters with sparse (BM25(F)) and hybrid search) is important to have, as I see the ability to combine vector searching with filtering efficiently one of the main selling points of using Weaviate.

Until that is not supported for the sparse (BM25(F)) and the hybrid search, only for the pure-vector search, that seriously limits the practical usability of those two and will force people to use alternative tools for the filtered sparse searching (incl hybrid search), like Elasticsearch.

**Comment by lakshaykc** [comment]
+1 to @zoltan-fedor point. I also think BM25 filtering is important in practice when dealing with large datasets.

**Comment by zoltan-fedor** [comment]
Thanks @lakshaykc. I agree, I can hardly imagine a scenario where my app would be fine to use BM25 without filtering. Sure, maybe not all queries require filtering, but even if 5% does, then not having filtering is a showstopped.

Please vote for this issue (thumbs up on the original post), as I was told that the Weaviate devs do lookk at the number of "votes" enhancement requests like this receive to determine what to deliver in what release.
Thanks

**Comment by etiennedi** [comment]
Awesome response, great to see the number of upvotes come in! Already 9 votes in less than 24h. This is now on the roadmap for `v1.18`, i.e., just one release after the initial Hybrid release.

**Comment by zoltan-fedor** [comment]
Thanks @etiennedi !
It will be great to see this delivered in `v1.18`!
Once that is out, I will enable that in Haystack too.

**Comment by eostis** [comment]
And compatibility with aggregation? (mandatory for e-commerce)

**Comment by alexanderfrey** [comment]
Dont want to hijack but is this also related to sorting with hybrid mode ?

**Comment by hsm207** [comment]
@eostis @alexanderfrey  Thank you for your feedback. Could you please open a new issue to describe the feature you want? This will give other community members a chance to vote on it and help us prioritise too.
