### ISSUE TITLE
Expand the description of this repo

### ISSUE THREAD

**Issue by dandv** [weaviate/weaviate#2397]
<img width="349" alt="image" src="https://user-images.githubusercontent.com/33569/204703679-9a8d6fb7-37d0-40de-a634-c3a918583306.png">

Just "vector search engine" at https://github.com/semi-technologies/weaviate is an understatement :)

**Comment by etiennedi** [comment]
@bobvanluijt can you coordinate this with @dandv – I believe you were the last one to make changes here :-)
