### ISSUE TITLE
I've created a cluster with the `text2vec-openai, text2vec-huggingface` modules. When I navigate to `/v1`, I see references to contextionary, even though it's not used:

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#2400]
I've created a cluster with the `text2vec-openai, text2vec-huggingface` modules. When I navigate to `/v1`, I see references to contextionary, even though it's not used:

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/33569/204394051-e7159d32-4d13-4738-bc23-50fc31b19902.png">

Navigating to those hrefs produces a 404, e.g. for `/v1/modules/text2vec-contextionary/extensions`.

__Originally posted by @dandv in https://github.com/semi-technologies/wcs-frontend/issues/45__

**Comment by hsm207** [comment]
@etiennedi I would like to fix this

**Comment by hsm207** [comment]
@etiennedi should references to the modules that are loaded (in this case,  `text2vec-openai`, `text2vec-huggingface`) be part of the response when a user navigates to `/v1`?
