### ISSUE TITLE
Replication: Tunable Write Consistency Level

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#2407]
When inserting data, I want to be able to choose between `ONE`, `QUORUM`, and `ALL`. The goal is that the cluster always replicates to all replication nodes, but the user request is acknowledged as soon as the specified consistency is reached. This way, writing is possible even when a node is down (for example by writing with `QUORUM`).

**Comment by etiennedi** [comment]
Completed in `v1.18.0` for all REST endpoints.

**Comment by dandv** [comment]
The [/v1/objects](https://weaviate.io/developers/weaviate/api/rest/objects#list-all-data-objects) REST endpoint seems to ignore the `consistency_level` parameter, because if I pass an invalid one, it doesn't complain.
