### ISSUE TITLE
Wildcard support for class names

### ISSUE THREAD

**Issue by trengrj** [weaviate/weaviate#2414]
Currently Weaviate can query multiple classes like below but this will return results from two separate queries:

```python
{
    Get {
        A1 {
            title
        }
        A2 {
            title
        }
    }
}
```

Would be nice to have a feature where wildcards or comma separated class names could be merged together (similar to how multiple shards are currently handled).

```python
{
    Get {
        A* {
            title
        }
    }
}
```

**Comment by etiennedi** [comment]
I like the idea, but I have no idea if that is feasible from a GraphQL perspective. Since it's all statically typed, I don't know if we can just dynamically merge fields at query time. This would definitely work with an equivalent REST API though.
