### ISSUE TITLE
AUTOSCHEMA_ENABLED set to true on WCS ?

### ISSUE THREAD

**Issue by eostis** [weaviate/weaviate#2429]
Hi,

It looks like the AUTOSCHEMA_ENABLED is defaulted to true on WCS clusters.

Is there a way to change that, or at least add a setting in the class API to change it?

**Comment by etiennedi** [comment]
@antas-marcin or @harrlight00 - do you think this is something we could easily add to the free tier WCS? To make this configurable.

**Comment by eostis** [comment]
Free and not free tier !

**Comment by eostis** [comment]
@etiennedi Are there some news yet?

This issue is preventing WooCommerce/WordPress owners from quickly testing Weaviate with OpenAI, HuggingFace, or Cohere on WCS with https://www.wpsolr.com. 
Not so many of them are able to install the whole stack, as most WP hosting is done on read-only VMs.

**Comment by eostis** [comment]
@etiennedi Do you have a plan for this issue, or even a workaround?

I'd prefer to use WCS for my clients who use an embedding API (OpenAI, Cohere, Hugging Face). 

I can install a K8s Weaviate instance on my own, and I need to for CLIP or other local models, but WCS is far more convenient with embedding APIs.

If it is not possible, which is totally fine, please just let me know. Thanks.

**Comment by trengrj** [comment]
Hi @eostis, custom variables like `AUTOSCHEMA_ENABLED` in the WCS beta are definitely supported. This feature is not currently able to be changed in sandboxes.

**Comment by eostis** [comment]
I'll just continue to install my customers out of WCS then. Thanks.

**Comment by eostis** [comment]
> Hi @eostis, custom variables like `AUTOSCHEMA_ENABLED` in the WCS beta are definitely supported. This feature is not currently able to be changed in sandboxes.

Hey @trengrj, is there a documentation of setting custom variables like `AUTOSCHEMA_ENABLED` in WCS serverless managed clusters?
