### ISSUE TITLE
No Question Answering module on WCS ? 

### ISSUE THREAD

**Issue by eostis** [weaviate/weaviate#2430]
<img width="1296" alt="image" src="https://user-images.githubusercontent.com/1785759/206858588-9178fa18-ef64-471f-997e-997852b03cad.png">

It looks like no QA module (transformer or OpenAI) is available on WCS.

**Comment by etiennedi** [comment]
Hi @eostis, we're in the process of enabling `qna-openai` by default. I'll keep this issue open until that's live.
