### ISSUE TITLE
[text2vec-openai] support arbitrary model names

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#2452]
Right now weaviate assembles the model name based on `model`, `modelVersion` (introduced in v1.16.8), and `docType`. But to support fine-tuned models, it would be nice to be able to override it, for example using something like

```json
{
  "documentModelOverride": "my-fine-tuned-model-doc",
  "queryModelOverride": "my-fine-tuned-model-query"
}
```

⬆️ is just a draft, there may be a better API

cc @eostis

**Comment by dirkkul** [comment]
we are supporting model names now
