### ISSUE TITLE
Non deterministic GQL query results for near text / near vector when using where filter.

### ISSUE THREAD

**Issue by vade** [weaviate/weaviate#2457]
Hello. I have isolated what I believe to be incorrect, or unexpected behavior with Weaviate with respect to combining a near vector query along with a where filter.

I am running Weaviate 1.16.8 - and have noticed this behavior with 1.16.5

One important detail - multiple objects in my data store return the same distance values for the results, ie multiple objects have the exact text: "I know what it's like Ava" vectorized by contextuary. This is *correct* for my data set, and an expected use case to have collisions on distances. 

Note that, I dont know if I have a strong opinion on what the order should be in that case (date created, etc?), but I do believe that the order changing is incorrect (?) or at least, unintuitive.

For example, this query produces, on my schema, deterministic results every time I run the query.

```
{
  Get {
    MySchemaObject(
      nearText: {concepts: ["I know what it's like Ava"], certainty: 0.96}
    ) {
      _additional {
        id
        distance
      }
    }
  }
}
```

Results for the above query, and note that distances returned for the top results are the same, but the order never changes. 

```
{
  "data": {
    "Get": {
      "MySchemaObject": [
        {
          "_additional": {
            "distance": 0.031876445,
            "id": "088b9402-7835-5896-b2b5-64e08e0e05ae"
          }
        },
        {
          "_additional": {
            "distance": 0.031876445,
            "id": "368b70e2-5cc6-55a7-becb-b22a52697a53"
          }
        },
        {
          "_additional": {
            "distance": 0.031876445,
            "id": "b8f36a99-9606-5668-93e6-3dd421b63f8b"
          }
        },
        {
          "_additional": {
            "distance": 0.031876445,
            "id": "c8dc048b-9c7c-5d33-9066-5c05d7d76afb"
          }
        },
        {
          "_additional": {
            "distance": 0.031876445,
            "id": "48d5a188-6f26-5d28-b7a7-17912dc95be9"
          }
        },
        {
          "_additional": {
            "distance": 0.046277523,
            "id": "ed272b59-c3b6-539b-b1f7-ba457117c121"
          }
        },
... snip for brevity

```

whereas this query - every time I run it, the ids returned appear shuffled:

```
{
  Get {
    MySchemaObject(
      nearText: {concepts: ["I know what it's like Ava"], certainty: 0.96}
      where: {path: ["childObject", "ChildObjectClassName", "id"], operator: Equal, valueString: "f3abce0f-d7db-5925-9b3f-c245b0467252"}
    ) {
      _additional {
        id
        distance
      }
    }
  }
}
```

One result:

```
{
  "data": {
    "Get": {
      "MySchemaObject": [
        {
          "_additional": {
            "distance": 0.031876445,
            "id": "48d5a188-6f26-5d28-b7a7-17912dc95be9"
          }
        },
        {
          "_additional": {
            "distance": 0.031876445,
            "id": "b8f36a99-9606-5668-93e6-3dd421b63f8b"
          }
        },
        {
          "_additional": {
            "distance": 0.031876445,
            "id": "088b9402-7835-5896-b2b5-64e08e0e05ae"
          }
        },
```
Another result:

```
{
  "data": {
    "Get": {
      "MySchemaObject": [
        {
          "_additional": {
            "distance": 0.031876445,
            "id": "c8dc048b-9c7c-5d33-9066-5c05d7d76afb"
          }
        },
        {
          "_additional": {
            "distance": 0.031876445,
            "id": "088b9402-7835-5896-b2b5-64e08e0e05ae"
          }
        },
        {
          "_additional": {
            "distance": 0.031876445,
            "id": "48d5a188-6f26-5d28-b7a7-17912dc95be9"
          }
        },
```

My presumption is, probably to add a manual sort to the query, but I wanted to run this behavior and start a discussion on it. 

Thank you.

**Comment by etiennedi** [comment]
Fair point. When distances are identical, we could add a flag that introduces a specific tie-breaker, for example, the creation date.

**Comment by vade** [comment]
Thanks! Just to be super clear, the behavior without a where filter is totally perfect. The introduction of the where filter seems to break whatever standard ordered retrieval happens even when there are distance metric collisions.
