### ISSUE TITLE
Improve BM25 performance in large scale setups

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#2480]
Weaviate `v1.17` introduces BM25 and Hybrid Search. The main focus point in `v1.17` is to get the correct results. @CShorten has done some great work to evaluate the implementation using BEIR and other datasets (yet to be published). This makes Weaviate's hybrid solution great for small and medium-scale use cases. Large-scale performance has not yet been in focus and as a result, BM25 latencies are higher than they could be on large datasets. This issue is about improving the performance for big use cases.

**Comment by eostis** [comment]
(following up https://github.com/weaviate/weaviate/issues/2554)

I could index my demo on your WCS cluster, and send you some Weaviate Hybrid slow queries.

You'll be able to monitor them as you wish.

But we need first to fix https://github.com/weaviate/weaviate/issues/2429

**Comment by etiennedi** [comment]
After some initial analysis, here are some ideas for performance improvements that have a significant impact grouped by how much effort they are to implement:

## Little Effort (v1.18)
- ### WAND Operator
  A WAND operator reduces the number of required distance calculations considerably. I expected WAND to be somewhat complex, but now that we have a working prototype, this has the best cost/reward ratio.

- ### Fix stopwords
  BM25 in `v1.17.1` seems to ignore the stopword configuration and scores all words, including stopwords. While stopword lists are a bit of a cheat for performance, at least some minimal stopword lists would always be used in practice. Just removing `the`, `of`, `a`, etc. in English already removes the posting lists with the most hits and, therefore, the highest cost. 

## Medium Effort (nice-to-have for v1.18)

- ### Improvements in `bucket.MapList`
  The current `sortedMapMerger` in `bucket.MapList` has high overhead when lists have little overlap. This could be fixed (#2561). This is most notable when no stopwords are used or on very large datasets. 

## High Effort (out of scope for v1.18, but interesting for the future)

- ### Zero-Initialization Map strategy
  The entire `Map` strategy in the `lmskv` bucket suffers from similar issues as described in #2511, mainly costly decode/parse steps. Because `Map` builds on top of `Collection` it even has two decode steps in a row. Even with the map merger fixed, this overhead would still be there. The idea is built a zero-initialization strategy similar to #2515, possibly making better use of compression, etc.
- ### BlockMax-WAND
  BlockMax-WAND requires a different kind of index, so there is plenty of overlap with the previous segment. In my opinion, this is not worth it at the moment because with WAND in place, scoring is no longer the bottleneck, it's disk retrieval. Therefore, I consider this the lowest priority at the moment. 

## Conclusion

If we consider an "average use case" to have 10-20M objects and a minimal stopword list in place, then sub-100ms latencies should be achievable with the above on average in v1.18. Further reducing latencies (or running without any stopword lists) requires more substantial (indexing) changes that are out-of-scope for v1.18.

**Comment by eostis** [comment]
@etiennedi Do you also check BM25 perfs with (many) filters/aggregations?

I tried the Hybrid search on a 2,000 products WooCommerce shop, with facets and filters,  and it's quite slow. It's fine with nearText though.

**Comment by etiennedi** [comment]
Filters aren't supported yet with BM25, but that will be coming soon (#2061).

For Aggregations, the part that aggregates is identical whether the results came from `bm25` or `nearText`. So if they are slower with `bm25` it's most likely because `bm25` itself is slower. So, yes this will also improve with `bm25`. An exception here would be if `bm25` returns far more results than `nearText`: An aggregation of more objects is going to be more expensive than with fewer.

So, short answer: Yes, but one step at a time, first we need to make `bm25` itself faster, then all derivatives :-)

**Comment by dirkkul** [comment]
superseeded by https://github.com/weaviate/weaviate/issues/2766
