### ISSUE TITLE
OpenAI add text-davinci-003 model

### ISSUE THREAD

**Issue by ym259** [weaviate/weaviate#2488]
Hi, 

I would like to request to upgrade the model of text-davinci-002 to text-davinci-003 for text2vec-openai.
It looks to me that it is going to be a few lines change in 'modules/qna-openai/config/class_settings.go' to make it work?
I just wanted to check if this was never requested or hasn't been done for some reason.

* I just started experimenting weaviate for my side-project a few days ago, so apologies if I missed anything...!

**Comment by creatorrr** [comment]
Can confirm the error also for `qna-openai` module:

```
weaviate.exceptions.UnexpectedStatusCodeException: Create class! Unexpected status code: 422, with response body: {'error': [{'message': "module 'qna-openai': wrong OpenAI model name, available model names are: [text-ada-001 text-babbage-001 text-curie-001 text-davinci-002]"}]}.
```

**Comment by byronvoorbach** [comment]
Thanks for the feedback. We will add support for the additional models!

**Comment by byronvoorbach** [comment]
@ym259 & @creatorrr 

Waiting for review and merge of pull request.
