### ISSUE TITLE
Support for asymmetric embedding retrieval techniques

### ISSUE THREAD

**Issue by creatorrr** [weaviate/weaviate#2497]
Many of the current SOTA retrieval methods like [instructor](https://instructor-embedding.github.io/) use asymmetric embeddings where the query `Q` and the document `D` use different embedding methods/prefixes (albeit in the same number of dimensions). How should we handle that? At the application level or possibly at the API level?

**Comment by trengrj** [comment]
Thanks @creatorrr. With asymmetric embeddings the current work-around would be to supply your own vectors (i.e. using sentence transformers directly https://huggingface.co/flax-sentence-embeddings/multi-QA_v1-mpnet-asymmetric-A), write the vectors to weaviate, and then use near vector to search in Weaviate.

ccing @antas-marcin for built-in asymmetric support for the vectorizer modules.
