### ISSUE TITLE
FR: Have a graphql query that works the same way as the GET /v1/objects endpoint

### ISSUE THREAD

**Issue by hsm207** [weaviate/weaviate#2498]
Users may want to retrieve an object by the object's id. The way to do this in graphql is with a where filter e.g `where_filter = {"path": ["id"], "operator": "Equal", "valueString": object_id}`.  This can be slow compared to using the [/v1/objects](https://weaviate.io/developers/weaviate/current/restful-api-references/objects.html) which does a lookup and does not need to navigate the HSNW graph.

It would be great if the graphql query is able to do the same when the query is essentially a lookup by object id.

**Comment by byronvoorbach** [comment]
Hi @hsm207 

Something like:
```
{
  Get {
    Paragraphs(
      id: ["123e4567-e89b-12d3-a456-426614174000", "123e4567-e89b-12d3-a456-426614174001"]
    ) {
      title
      content
    }
  }
}
```

@etiennedi would there be a reason not to do this??
