### ISSUE TITLE
Hybrid does not show objects from reference

### ISSUE THREAD

**Issue by bhavnicksm** [weaviate/weaviate#2506]
Hi, I am facing an issue where under hybrid search, the properties that refer to other objects are not being rendered in the search results for all alpha>0.

At alpha=0, they are being shown properly. 

I am using weaviate v1.17

**Comment by bhavnicksm** [comment]
Not a complete reproducing example since that would require proprietary data, but I can describe how to reproduce this. 

Let's say you have a weaviate database with two classes, Article and Metadata. 

For each article, there is a reference to Metadata object. Multiple Articles can have the same Metadata reference. 

Once this is loaded up in the weaviate engine, you can use the hybrid search query with alpha=1 and alpha=0 to see if the reference to metadata is coming in the search results or not. 

I hope this helps!

**Comment by etiennedi** [comment]
Fixed in Weaviate `v1.17.2`.
