### ISSUE TITLE
Slow Hybrid search

### ISSUE THREAD

**Issue by eostis** [weaviate/weaviate#2554]
(Weaviate 1.17.1)

![image](https://user-images.githubusercontent.com/1785759/213470101-eeed2144-524a-4f4d-83bb-cb79d776c60a.png)

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/1785759/213470355-40d39322-b953-47f1-a155-39a5c46b08d1.png">

**Comment by etiennedi** [comment]
Thanks for the report. The simple answer is; we're aware of and working on speed improvements for v1.18, see #2480.

I suggest that we move the conversation there. I'm interested in some general numbers: dataset size, queries, latencies, expected latencies etc.

Our current strategy is to evaluate performance with a wide variety of [BEIR datasets](https://github.com/beir-cellar/beir#beers-available-datasets), but the closer we can get our test cases to real examples, the better.

**Comment by eostis** [comment]
I could index my demo on your WCS cluster, and send you some Weaviate slow queries.

You'll be able to monitor them as you wish.

But we need first to fix #2429

**Comment by eostis** [comment]
Working on https://github.com/weaviate/weaviate/issues/2480 from now.
