### ISSUE TITLE
FR: Namespace /  multi DB support

### ISSUE THREAD

**Issue by samos123** [weaviate/weaviate#2565]
## Update May 2023 by @etiennedi 

Please see the new [proposal here](https://github.com/weaviate/weaviate/issues/2970) and leave your feedback as comments in the respective issue.

I'll leave this one open because it has all the votes and is visible in the roadmap, but would like to move the discussion about the actual feature to the linked issue. Thank you.

## Original issue by @samos123:

The ability for Weaviate to have a concept of namespaces or database like in MySQL where you can have multiple Databases with the same table name. In Weaviate, similarly we could have a concept of Namespace (naming TBD) which would allow you to have the same class name but in a different namespace. In the future the namespace could also be used for more granular permissions.

Please upvote if this feature is important to you by giving a thumbs up

**Comment by hadfield** [comment]
My use case for this involves keeping Customer data in separate spaces (Customer1, Customer2, ...) such that a query scoped to a namespace for a Customer would not find data for a different Customer and that the vector spaces were kept separated such that customer data does not affect each other for things like query performance and classification.

**Comment by kubre** [comment]
So other than filtering there is no way to achieve this?

**Comment by kubre** [comment]
@byronvoorbach Are there limits on how many classes can be created

**Comment by etiennedi** [comment]
> @byronvoorbach Are there limits on how many classes can be created

There are no theoretical limits. However, we currently see that a user with 2-6,000 classes encounters occasional performance issues, especially when changing the schema. Those are tracked and addressed in #2785. We expect most of those issues to be resolved by the time the v1.19 release is out.

**Comment by kubre** [comment]
Right now I'm using a single class where I first prefilter using one of the properties, do you think this has any disadvantage over multiple classes

**Comment by RonB** [comment]
Is there any development in this? We think namespace or db separation is crucial before encountering we will encounter possible data-leaks or hack attempts. Our use-case is that many customers can use our services so instances of Weaviate per customer is not a viable solution. @kubre: using properties to filter customer data seems even more dangerous to me.

**Comment by etiennedi** [comment]
Yes, a native multi-tenancy approach (using namespaces/partitions under the hood) will be the main focus point of v1.20.

The current goals/requirements are:

- strict separation of tenants in storage (compliance, etc)
- impossible to query across tenants through the API
- any request that refers to an object must also provide the partitioning key (to identify the tenant)
- supports millions of tenants with at least 10s of thousands of tenants per node

**Comment by kubre** [comment]
@RonB That is understandable but we were using weaviate in kind of a demo mode till the multi-tenancy support is added

@etiennedi When will the v1.20 come?

**Comment by etiennedi** [comment]
Please see the new [proposal here](https://github.com/weaviate/weaviate/issues/2970) and leave your feedback as comments in the respective issue.

I'll leave this one open because it has all the votes and is visible in the roadmap, but would like to move the discussion about the actual feature to the linked issue. Thank you.

**Comment by dirkkul** [comment]
I think this is multi tenancy :)
