### ISSUE TITLE
FR: Distribute pre-compiled binaries for common architecture/OS combinations with releases

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#2573]
Title says it all.

**Comment by indrasn0wal** [comment]
is the issue still open?

**Comment by h4shk4t** [comment]
I would like to take this issue

**Comment by h4shk4t** [comment]
Im getting the following errors while compiling for GOOS=windows

**Comment by h4shk4t** [comment]
I'm getting the following errors while creating the binaries for GOOS=windows
`# github.com/weaviate/weaviate/adapters/repos/db/lsmkv
adapters/repos/db/lsmkv/segment.go:83:26: undefined: syscall.Mmap
adapters/repos/db/lsmkv/segment.go:83:81: undefined: syscall.PROT_READ
adapters/repos/db/lsmkv/segment.go:83:100: undefined: syscall.MAP_SHARED
adapters/repos/db/lsmkv/segment.go:152:17: undefined: syscall.Munmap
adapters/repos/db/lsmkv/segment_precompute_for_compaction.go:55:26: undefined: syscall.Mmap
adapters/repos/db/lsmkv/segment_precompute_for_compaction.go:55:80: undefined: syscall.PROT_READ
adapters/repos/db/lsmkv/segment_precompute_for_compaction.go:55:99: undefined: syscall.MAP_SHARED
adapters/repos/db/lsmkv/segment_precompute_for_compaction.go:60:16: undefined: syscall.Munmap
# github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw
adapters/repos/db/vector/hnsw/condensor_mmap_reader.go:46:28: undefined: syscall.Mmap
adapters/repos/db/vector/hnsw/condensor_mmap_reader.go:47:11: undefined: syscall.PROT_WRITE
adapters/repos/db/vector/hnsw/condensor_mmap_reader.go:47:31: undefined: syscall.MAP_PRIVATE
adapters/repos/db/vector/hnsw/condensor_mmap_reader.go:58:20: undefined: syscall.Munmap`

**Comment by h4shk4t** [comment]
Also binaries for linux and darwin for amd64 and arm64 have been compiled successfully... Where should I push them?

**Comment by YASHpPATIL7** [comment]
This issue is still open , i would like to contribute.

**Comment by h4shk4t** [comment]
cc. @etiennedi

**Comment by samos123** [comment]
they should be pushed as part of a github actions workflow. You mind if I help with this because I need this for another feature?

Also could we please ensure binaries are compiled with `CGO_ENABLED=0`? otherwise they won't work in some notebook environments.
