### ISSUE TITLE
[feature] Optionally provide Huggingface endpoint URL/path in `text2vec-huggingface`

### ISSUE THREAD

**Issue by kcm** [weaviate/weaviate#2576]
The [Huggingface endpoint in t2v-hf](https://github.com/weaviate/weaviate/blob/abf30eac8656cf3bf1b471d9eb1416695777a53d/modules/text2vec-huggingface/clients/url.go) is hardcoded to the public HF endpoint.

Azure (and possibly others) offer [hosted endpoints](https://huggingface.co/blog/hugging-face-endpoints-on-azure), so making this URL and path optionally user-configurable would allow arbitrary deployment endpoints to be used.

This would provide appreciable cost and security benefits for users.

@hsm207

**Comment by ssuygun** [comment]
Also, See [link](https://weaviate-org.slack.com/archives/C039ZLWKHB7/p1674833800959789).

**Comment by hsm207** [comment]
Also, see the service's [documentation ](https://azure.microsoft.com/en-us/solutions/hugging-face-on-azure/#overview)on azure.

**Comment by TheAthleticCoder** [comment]
I would like to take up this issue

**Comment by TheAthleticCoder** [comment]
cc: @etiennedi @kcm

**Comment by TheAthleticCoder** [comment]
cc: @hsm207 
Pushed the commit for further review.

**Comment by hsm207** [comment]
@TheAthleticCoder have you at least manually tested the new setting using azure's hosted endpoint?
