### ISSUE TITLE
Bug: Schema update coordinator behaves different than every one else -> possibility for inconsistency

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#2616]
* The coordinator receives a schema update and broadcasts it in the first phase to all nodes
* All nodes ACK
* The coordinator proceeds to commit
* A node does not respond to the commit (e.g. because it died during the update)
* Now the coordinator does not apply the change itself anymore. 
* This is incorrect because the coordinator told all other nodes to commit, yet it does not commit itself
* As a result the coordinator will be out of sync with everyone else

**Comment by dirkkul** [comment]
should also be solved by RAFT
