### ISSUE TITLE
Bug: Prometheus Port is read from config, but ignored, actual value is hard-coded

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#2621]
A user can set a custom port here: https://github.com/weaviate/weaviate/blob/fcc1f8470bfbe5f71a6efb45075a3e06f66f5f40/usecases/config/environment.go#L44-L51

Only for Weaviate to completely ignore the config and use a hard-coded port number anyway: https://github.com/weaviate/weaviate/blob/fcc1f8470bfbe5f71a6efb45075a3e06f66f5f40/adapters/handlers/rest/configure_api.go#L119

Note to the contributor: Please base your contribution branch on `stable/v1.17` (or newer if present) and mark the same branch as the merge target, this way this can be released as a patch. (`master` would indicate the next minor).

**Comment by srini047** [comment]
Hi @etiennedi!  I am working on this issue. You can expect PR within EOD.

**Comment by srini047** [comment]
I have started working and I want to know whether my understanding of the Issue is correct or not:

- Currently in the `configure-api.go` the port value is hardcoded.
- Instead, get the port number from `environment.go` and use it in-place

Please let me know if I am correct or not.

**Comment by riteshsonawane1372** [comment]
Hey,@etiennedi if @srini047 is not working on this issue I would like to do it.

**Comment by etiennedi** [comment]
Thanks, @riteshsonawane1372. It's been six weeks since the last update, so assuming this was abandoned is fair. Feel free to fix and open a PR.
