### ISSUE TITLE
Regarding hybrid vector search and custom scoring

### ISSUE THREAD

**Issue by xiankgx** [weaviate/weaviate#2641]
https://weaviate.io/developers/weaviate/api/graphql/vector-search-parameters#hybrid

With reference to the above, is it possible to perform a hybrid search by some aggregation of the score from KNN/ANN and conventional search?

I could have a field for each document and the aggregated score could be the cosine similarity from KNN/ANN and the value of a field in the document, for e.g. cosine similarity (=0.6) + download_score (=0.8) = 1.4.

Is this doable in weaviate?

**Comment by xiankgx** [comment]
Also, the query at least in Python needs to be specified as a string, is it possible to do complex query for example just searching on a subset of fields?

**Comment by trengrj** [comment]
Apologies for the delay.

For the first question, this is not supported right now. CCing @CShorten for feedback on adding different ranking functions.

For the second question you can customize the hybrid sparse fields by the `properties` field i.e. `properties: ["title^3", "summary"]`. The dense fields are controlled by how you create the vector.
