### ISSUE TITLE
ref2vec: cannot create vector using python client's batch

### ISSUE THREAD

**Issue by hsm207** [weaviate/weaviate#2654]
I have a Article class that has a cross reference to a Paragraph class

I want to use ref2vec to create a vector for an Article based on its Paragraph.

This way of creating the Article class works i.e. the article's `_additional.vector`  is not empty:

```python
# create article B in weaviate
article_title = "B"
article_paragraphs = articles[article_title]

article_uuid = client.data_object.create(
    {
        "title": article_title,
    },
    class_name="Article",
)

for paragraph in article_paragraphs:
    paragraph_uuid = client.data_object.create(
        {
            "content": paragraph,
        },
        class_name="Paragraph",
    )

    client.data_object.reference.add(
        from_uuid=article_uuid,
        from_property_name="paragraphs",
        to_uuid=paragraph_uuid,
        from_class_name="Article",
        to_class_name="Paragraph",
   
```

but this does not:

```python
# create article A in weaviate
article_title = "A"
article_paragraphs = articles[article_title]

with client.batch as batch:
    article_uuid = batch.add_data_object(
        {
            "title": article_title,
        },
        class_name="Article",
    )

    for paragraph in article_paragraphs:
        paragraph_uuid = batch.add_data_object(
            {
                "content": paragraph,
            },
            class_name="Paragraph",

        )

        batch.add_reference(
            from_object_uuid=article_uuid,
            from_object_class_name="Article",
            from_property_name="paragraphs",
            to_object_uuid=paragraph_uuid,
            to_object_class_name="Paragraph",
        )
```

Why does article A not have a vector?

[Here ](https://gist.github.com/hsm207/ffb2122acade111c081b120b1db367e3)is the notebook to reproduce the example.

**Comment by shelbywhite** [comment]
Same error on my end. When batching the vector is not added and the results are inconsistent each time I index.

**Comment by parkerduckworth** [comment]
Hey @hsm207, ref2vec-centroid does not support centroid calculations using batch. Unfortunately this limitation is not documented (which I will fix now). Also, I plan on removing this limitation very soon.

Here are the only methods currently supported for updating a centroid vector:
https://weaviate.io/developers/weaviate/modules/retriever-vectorizer-modules/ref2vec-centroid#updating-the-centroid

**Comment by parkerduckworth** [comment]
To clarify, centroid vectors *can* be produced by creating *objects* in a batch, which have references attached to them. Adding batch references alone will not.

This is because the batch reference feature was specifically built to be efficient by avoiding the cost of updating the vector index.

That being said, if there is a serious need for batch reference creation which produces centroids, we can certainly consider adding it.

**Comment by dirkkul** [comment]
this should work:

```
    collection = client.collections.create(
        properties=[Property(name="Name", data_type=DataType.TEXT)],
        vectorizer_config=Configure.Vectorizer.none(),
    )
    collection.config.add_reference(
        ReferenceProperty(name="self", target_collection=collection.name)
    )

    uuid1 = collection.data.insert({"name": "A"})
    uuid2 = collection.data.insert({"name": "B"})

    batch_return = collection.data.insert_many(
        [
            DataObject(
                properties={"name": "C"},
                references={"self": uuid1},
            ),
            DataObject(
                properties={"name": "D"},
                references={"self": [uuid1, uuid2]},
            ),
            DataObject(
                properties={"name": "E"},
                references={"self": uuid1},
            ),
            DataObject(
                properties={"name": "F"},
                references={"self": [uuid1, uuid2]},
            ),
        ]
    )
```

WIll close this and let the docs team know that the documentation for ref2vec needs an update
