### ISSUE TITLE
[UX] Weaviate should be runnable without any env vars or cli args set

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#2656]
It should then pick reasonable defaults for everything.

**Comment by etiennedi** [comment]
The funniest one is `QUERY_DEFAULTS_LIMIT`. If it's not set, the default limit on `GET /v1/objects` is `0` ... which is very confusing.

**Comment by preetham** [comment]
@etiennedi Can I pick this up ?

**Comment by VishalPraneeth** [comment]
Hey @etiennedi, if this issue is still open can I take it?

**Comment by preetham** [comment]
@VishalPraneeth please take it ahead, I didn't have time to pick it up.

**Comment by VishalPraneeth** [comment]
`environment:
      LOG_LEVEL: "debug"
      CONTEXTIONARY_URL: contextionary:9999
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "./data"
      DEFAULT_VECTORIZER_MODULE: text2vec-contextionary
      ENABLE_MODULES: text2vec-contextionary
      PROMETHEUS_MONITORING_ENABLED: 'true'
      PROMETHEUS_MONITORING_GROUP_CLASSES: 'true'
      CLUSTER_GOSSIP_BIND_PORT: "7100" 
      CLUSTER_DATA_BIND_PORT: "7101`

out of these which env vars or cli args should be replaced or removed?

**Comment by trengrj** [comment]
@VishalPraneeth this is the minimal config required currently to start weaviate as a binary

```
export PERSISTENCE_DATA_PATH="./data"
export AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED="true"
./weaviate --host 0.0.0.0 --port 8080 --scheme http
```

**Comment by VishalPraneeth** [comment]
> @VishalPraneeth this is the minimal config required currently to start weaviate as a binary
> 
> ```
> export PERSISTENCE_DATA_PATH="./data"
> export AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED="true"
> ./weaviate --host 0.0.0.0 --port 8080 --scheme http
> ```

Can I remove or comment out the rest of them and open a PR?

**Comment by trengrj** [comment]
The main task here would be setting good defaults and we wouldn't want the arguments removed for backwards compatibility.

- `PERSISTENCE_DATA_PATH` a good default would be `./data` if not set
- `QUERY_DEFAULTS_LIMIT` should default to 10 (I missed this above but weaviate does start without this)
- host default to `localhost`
- post default to `8080`
- scheme default to `http`

The tricky one would be `AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED`. @etiennedi what are your thoughts on a default for this? My preference is we would autogenerate an api key in this scenario.

**Comment by MatthiasReumann** [comment]
Hey! Is anyone working on this? If not, may I work on this issue?

**Comment by avirlrma** [comment]
@trengrj @etiennedi For non-server arguments, I was able to fill in the defaults in `config_handler.go`, however for server arguments: `scheme` and `port`, only approach I got was to set them in `main.go` (ref: https://github.com/go-swagger/go-swagger/issues/2363#issuecomment-662607212). Please note that we can't change the default scheme in `go-swagger` as it will lead to a lot of unintented changes as well.

I am working on the test cases for config_handler, however if we want to have a discussion over this I can raise a draft PR.

**Comment by avirlrma** [comment]
I've opened a PR to demonstrate what I mean, please have a look.
