### ISSUE TITLE
[Q] Difference between Ask and nearVector

### ISSUE THREAD

**Issue by mauserzjeh** [weaviate/weaviate#2673]
Is there a difference between Ask and nearVector when doing a vector search? 

ie.: If my purpose is to get the most relevant text from the database, passing a question like "What color is the sky?" to the AskBuilder will produce the same results as If I would pass the same string to the nearVector? Or does the AskBuilder do something with the given string before making a search for the relevant text?

Thanks!

**Comment by trengrj** [comment]
Please see https://weaviate.io/developers/weaviate/modules/reader-generator-modules/qna-transformers#how-it-works-under-the-hood for details. Essentially `Ask` is a higher level operator that will first do a vector search to get the top ranked object. It will then as a second phase use the Q&A module to pull out the answer from the object.

**Comment by mauserzjeh** [comment]
Yes, I have read the documentation before posting this question here. What I still didn't get an answer for is that, do these two use the same method when retrieving the top ranked object? I particularly don't use the answer of the `Ask`. Just use it to retrieve the most relevant objects. **My question is can I just use `nearVector` by passing the same string as to `Ask`? Will it produce the same results in terms of getting the same relevant contexts or they work differently when retrieving the most relevant object?**

**Comment by trengrj** [comment]
`Ask` does a `nearText` query (which converts the query into a vector and then does `nearVector` search) under the cover. You can see the implementation here https://github.com/weaviate/weaviate/blob/ef75f0189f25c738ace735e4d5d6a412e1e88018/modules/qna-transformers/ask/searcher.go#L33.
