### ISSUE TITLE
Only allow authenticated access to /v1 

### ISSUE THREAD

**Issue by dirkkul** [weaviate/weaviate#2678]
For reference: https://weaviate.slack.com/archives/C017EG2SL3H/p1677178331583509

Currently it is possible to query /v1 with any user that has a valid access token from the auth provider. Eg if you use WCS as the auth provider anyone with valid WCS credentials can query the /v1 endpoint if part of the admin list or not.

Steps to reproduce:

- Start docker with [docker-compose file](https://github.com/weaviate/weaviate/files/10823085/docker_compose_wcs_auth.txt) (rename to .yml)
- Get an access token using [this script](https://weaviate.io/developers/weaviate/configuration/authentication#manually-obtaining-and-passing-tokens)
- Query /v1 with header `Authorization: Bearer *Access_token_from_last_step*`

Note that this only seems to apply to the /v1 endpoint, other endpoints (eg v1/objects) return the correct error.

**Comment by etiennedi** [comment]
Is this a problem? The `/v1` page is essentially a home page with links to other places. Does that really need to be protected? It's like what you see on a website before you log in – you still see the navigation.

**Comment by dirkkul** [comment]
If authentication is enabled, you get an authentication error if you query /v1 without an access token. But then every access_token that is provided by the issuer is accepted.

If we are sure that this page only contains non-sensible information, we could also remove the authentication requirement alltogether. But this "half-protected" state is weird and confusing.

**Comment by etiennedi** [comment]
Oh, thanks for elaborating; yes, that makes perfect sense. It should either be completely free from authentication and authorization or adhere to both. Just one of two is indeed confusing.

**Comment by dirkkul** [comment]
fixed in https://github.com/weaviate/weaviate/pull/2743
