### ISSUE TITLE
I'd like to connect text-search-davinci-query-001,   text-search-davinci-doc-001 respectively

### ISSUE THREAD

**Issue by yspaik** [weaviate/weaviate#2702]
text2vec open api with model name `text-search-davinci-query-001` and `text-search-davinci-doc-001` and some other 'query' 'doc' style models are available on OpenAI as of today.

I'd like to apply these names but the names occur error.
The error seems to be caused by the code below.

https://github.com/weaviate/weaviate/blob/abf30eac8656cf3bf1b471d9eb1416695777a53d/modules/text2vec-openai/vectorizer/class_settings.go

The available ai model in the code line 35 limits the model to 4 cases. 
However, the new name snippets such as `query`, `doc` are additionally added between the model name for example `davinci` and version number `001`.

~~~
var availableOpenAIModels = []string{
	"ada",     // supports 001 and 002
	"babbage", // only suppports 001
	"curie",   // only suppports 001
	"davinci", // only suppports 001
}
~~~

**Comment by trengrj** [comment]
Resolved in slack https://weaviate.slack.com/archives/C018K3TCUEL/p1678073841011409

> text2vec-openai uses query (for nearText ) and doc (for vectorisation) endpoints internally you just need to apply properly moduleConfig for your class like so and all will work properly:
> ```
> "moduleConfig": {
>   "text2vec-openai": {
>     "model": "davinci",
>     "modelVersion": "001",
>     "type": "text"
>   }
> }
> ```
