### ISSUE TITLE
Support gpt-3.5-turbo and gpt-3.5-turbo-0301

### ISSUE THREAD

**Issue by mjiangcn** [weaviate/weaviate#2715]
There are two new models released by OpenAI: gpt-3.5-turbo and gpt-3.5-turbo-0301, which are 1/10 cost compared to davinci.

**Comment by copeus** [comment]
yeah! 
How to activate it? The idea with 
```
          "qna-openai": {
            model: "gpt-3.5-turbo",
            maxTokens: 50,
            temperature: 0.3,
            topP: 0.7,
            frequencyPenalty: 0.0,
            presencePenalty: 0.0,
          },
```

doesn't work

**Comment by copeus** [comment]
@byronvoorbach thanks! 
btw just announced that `gpt-4` is available primarily. It also uses the same Chat Conversation API as `gpt-3.5-turbo`. So it's very needed.
it goes with an 8K context window (about 13 pages of text) and will cost $0.03 per 1K prompt tokens and $0.06 per 1K completion tokens.

**Comment by copeus** [comment]
in announce they declared the same API as `gpt-3.5-turbo` 
I hope it would be enough to bypass `gpt-4` and `gpt-4-32k` instead of `gpt-3.5-turbo`  to get it run

**Comment by byronvoorbach** [comment]
When adding support for 3.5 turbo, we can do 4 at the same time as well. Mostly depends on whether we can successfully test gpt4 before releasing support in Weaviate

**Comment by etiennedi** [comment]
I put the `planned-1.19` label on this. We are most likely going to release that much sooner as part of a `1.18.x` patch. The idea behind the label is to indicate that this is prioritized and coming soon. (shows up on top of the Roadmap page this way).

**Comment by prabhupb** [comment]
Do you not support the new [chat completion api ](https://platform.openai.com/docs/api-reference/chat/create)? In other words, can we not use `gpt-3.5-turbo` model for `qna-openai` module?

**Comment by dirkkul** [comment]
i think this was added - if some detail is missing please open a new issue, thanks!
