### ISSUE TITLE
Feature request: get distinct values from Weaviate objects

### ISSUE THREAD

**Issue by klehmann** [weaviate/weaviate#2748]
We would like to use Weaviate as the primary database for our applications. While the query functionality to select and sort objects is already very powerful and a great match, we need additional functionality to extract distinct values from the selected objects.

For example, users can add keywords/tags to objects (with no fixed list of values, allowing new values) and we need to:

- Filter all objects using hybrid search.
- Retrieve a distinct list of used keywords/tags without traversing them all in application code.

We can then use this list to populate a dropdown box of a filter form, draw a tag cloud, or display the objects in a tree component so that users can drill down their data. Hopefully, you can use an existing index to improve performance even for large datasets.

**Comment by trengrj** [comment]
@klehmann the groupby Aggregation feature could be what you want ref https://weaviate.io/developers/weaviate/api/graphql/aggregate#groupby-argument

**Comment by klehmann** [comment]
Looks good! I also tried to add where filters.

```java
		Field meta = Field.builder()
				.name("meta")
				.fields(new Field[]{
						Field.builder().name("count").build()
				}).build();
		Field groupedBy = Field.builder()
			      .name("groupedBy")
			      .fields(new Field[]{
			        Field.builder().name("value").build(),
			        Field.builder().name("path").build()
			      }).build();
		
		WhereFilter where1 = WhereFilter.builder()
                .path(new String[]{ "category" })
                .operator(Operator.Equal)
                .valueText("ANIMALS")
                .build();

		WhereFilter where2 = WhereFilter.builder()
                .path(new String[]{ "category" })
                .operator(Operator.Equal)
                .valueText("SCIENCE")
                .build();

		WhereFilter whereOr = WhereFilter.builder()
                .operator(Operator.Or)
                .operands(new WhereFilter[] {where1, where2})
                .build();

		Result<GraphQLResponse> response = client.graphQL().aggregate()
				.withClassName("Question")
				.withFields(meta, groupedBy)
				.withWhere(whereOr)
				.withGroupBy("category")
				.run();
```

Thanks a lot!
