### ISSUE TITLE
Proposal: Deprecate `string`, enrich `text` tokenization options, more fine-grained indexing

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#2751]
This proposal combines the following ideas:

1. Deprecate `string` and merge it with `text`. Instead, use `tokenization` to control the behavior of each prop
2. Add new tokenization options for more fine-grained (and more obvious) control of how something is tokenized
3. Give the user control of whether a `text` prop should be indexed for filtering (with roaring bitmaps), for BM25, or both
4. Remove the filter cache because it is no longer necessary and actually a performance hindrance in some cases.

## Tokenization options

Quoting @trengrj how came up with a great idea:

* `word` same as current behavior on `text` (i.e. only keep alpha-numeric, lowercase all, split on whitespace)
* `whitespace` same as `word` on `string` right now (i.e. keep all chars, don't change casing, split on whitespace)
* `lowercase` whitespace + lowercase (i.e. keep all chars, but lowercase, split on whitespace)
* `field` same as current on `string` (i.e. don't change anything, index whole field exactly as is)

## Indexing options

Right now there is a single `indexInverted` prop which always leads to `Map` indexing on both `string` and `text` props. Instead this should be split into `indexFilterable` and `indexSearchable` whereas the former creates a roaring set index and the latter creates a `BM25-suitable` Map index. For backward, compatibility, both would be on by default.

## Deprecation of `string`
* Any existing class can be migrated according to the tokenization rules above at first startup
* If the user still specifies `string` on a new class it will be stored as `text` with the correct tokenization config and a deprecation warning will be printed

## Removal of filter cache
* For any bitmap-indexed object there is no considerable benefit of the cache
* While investigating cross-ref filters, it showed that the hash bucket checks required for the cache even add considerable overhead
* For users with many classes (multi-tenancy) the limits of the cache can become unpredictable, as each class could in theory have a cache that grows up to 500MB.
* As a result we would now be better off removing the cache completely

**Comment by trengrj** [comment]
👍 For the removal of the filter cache we need bitmap-indexed text fields available and testing for any regressions.

**Comment by etiennedi** [comment]
> For the removal of the filter cache we need bitmap-indexed text fields available and testing for any regressions.

Bitmap-indexed text fields will be part of this change. Agreed on the testing. If you have any specific test scenarios that you can come up with, feel free to contribute to a test scenario. We could also turn this into a performance test that runs on CI to prevent future regressions and monitor the performance over time.

During the improvements for #2756, we already disabled the filter cache for some cross-ref specific scenarios because on a cache-miss it was actually slower to check for a cache. At the same time, the speed-up for a cache hit was insignificant with the fast retrieval of the native roaring bitmap.

Completely removing the cache will also come with a few other nice benefits:
- Simpler Code: there is now one path to retrieve a filter instead of two
- Smaller Disk footprint: we will no longer need to store the hash buckets for each prop
- Fewer compactions and async loops (after the removal of hash buckets): This mainly relates to #2785 where we see issues with many classes and props
- More predictable resource usage. At the moment, the cache can dynamically allocate between 0 and 500MB per class which makes it hard to estimate the resource requirements when many classes are present.

**Comment by etiennedi** [comment]
Closed as complete.
