### ISSUE TITLE
Unable to run BM25 search on string[] property type

### ISSUE THREAD

**Issue by shelbywhite** [weaviate/weaviate#2762]
Hello,

I encountered an issue while attempting to run a `BM25` search on a property type of string[]. It seems like the implementation for this property type is missing. I've looked through the documentation but couldn't find any information about this specific use case. Currently, it only appears to work on the string property type.

As noted by the Weaviate team already, this issue is known.

Here's the error message I received:

Error:
`'message': 'explorer: get class: vector search: object search at index media: shard media_IUtkjgcgoqoC: wand: cannot handle datatype string[]'`

Please note that the field in question is using the `multi2vec` vector.

**Comment by dirkkul** [comment]
will be 1.18.1
