### ISSUE TITLE
Occasional "Schema could not be retrieved" error

### ISSUE THREAD

**Issue by zoltan-fedor** [weaviate/weaviate#2782]
After upgrading the client from v3.11 to v3.15.2 we started seeing occasional "Schema could not be retrieved" error from `weaviate/schema/crud_schema.py` line 462 when using `weavaite_client.schema.get()`.

Any idea?

EDIT: looking at the logs it turns out this error was happening even while we were on v3.11, so it might not be related to the newer versions.

**Comment by dirkkul** [comment]
This sounds more like a weaviate problem. DId you maybe update weaviate?

**Comment by zoltan-fedor** [comment]
Thanks @dirkkul
I am on Weaviate v1.18.0 for a while with classes set with replication factor 2.
Sorry, I don't have the logs prior to 1.18, so I can't tell whether this error was happening before that too.

**Comment by dirkkul** [comment]
Hi, can you give us anyhints what to look for?

Is there anything in the Weaviate (server-side) logs? Anything special that you're doing?

**Comment by zoltan-fedor** [comment]
@dirkkul,
Unfortunately there isn't many hints to provide and I don't think we are doing anything special.

I use Weaviate v1.18.3 on Kubernetes is a 2-instance setup.
All our classes are setup with the replication factor of 2.

Queries against these classes work fine - most of the times, but occasionally the queries to Weaviate fail with the `Schema could not be retrieved` error. Retrying the same query usually succeed.
The server logs don't register anything.

For now we just added a retry logic when this error occurs.

**Comment by dirkkul** [comment]
we reworked the schema logic, so this probably does not appy anymore. Please open a new issue in case this is happening again
