### ISSUE TITLE
[Replication] Support tunable consistency in GraphQL Get requests including search

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#2787]
As outlined in the title, we want to support tunable consistency for replication-enabled setups for:
- `Get {}` list requests
- `near<Media>` vector search
- `bm25` search
- `hybrid` search

**Comment by avirlrma** [comment]
Hey @etiennedi,
I just want to confirm if this is done? I did see a related PR: https://github.com/weaviate/weaviate/pull/2781

**Comment by dirkkul** [comment]
think this is implemented
