### ISSUE TITLE
New metric: HTTP errors

### ISSUE THREAD

**Issue by byronvoorbach** [weaviate/weaviate#2790]
Would be good to be able to have the option to keep track of the 400/500 HTTP error codes and have them added to our current metric setup. This way it becomes easy for users to track the amount of errors thrown by Weaviate.

Proposal for addition:

```
    HttpErrors: promauto.NewCounterVec(prometheus.CounterOpts{
       Name: "http_errors",
       Help: "Errors",
    }, []string{"code", "method", "path"}),
```

Note: This implementation would not support on a per-class basis, that would require a specific implementation per use-case.

**Comment by etiennedi** [comment]
Agreed. Besides metrics, we should also log any errors. Otherwise, it's the responsibility of the caller to log any error which can't be guaranteed. Especially in a SaaS setup, an error that isn't logged on the server would not be tracked at all.

**Comment by etiennedi** [comment]
See #3116
