### ISSUE TITLE
[UX] Improve handling of parallel attempts to update Schema

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#2798]
## Problem
Weaviate does not allow concurrent schema updates. The schema logic requires strong consistency and if multiple requests come in in no specific order one or many of them will fail with a `concurrent transaction` error. From a tech perspective, this is expected, but it leads to a bad UX. In languages such as Javascript async is the default and the user could be sending parallel requests without even thinking about it.

## Possible Solution
Instead of failing the request immediately, Weaviate could recognize the concurrent transaction and retry up to `n` times with a random backoff to reduce congestion.

**Comment by dirkkul** [comment]
solved with RAFT :)
