### ISSUE TITLE
OpenCLIP compatibility

### ISSUE THREAD

**Issue by yekta** [weaviate/weaviate#2846]
Hey, we are trying to make make this work with txt2vec-transformers in our own deployment: https://huggingface.co/laion/CLIP-ViT-H-14-laion2B-s32B-b79K

It's compatible with AutoModel, AutoTokenizer and AutoProcessor but we couldn't manage to get it working. We aren't getting particularly descriptive errors. I'm wondering if there is a way to make it work or am I missing something?

```ERROR: Exception in ASGI application
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/fastapi/encoders.py", line 152, in jsonable_encoder
data = dict(obj)
TypeError: 'torch.dtype' object is not iterable
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/fastapi/encoders.py", line 157, in jsonable_encoder
data = vars(obj)
TypeError: vars() argument must have __dict__ attribute```

**Comment by antas-marcin** [comment]
@yekta support for OpenCLIP models is coming this week to `multivec-clip` module (look at this [PR](https://github.com/weaviate/multi2vec-clip-inference/pull/21)) I will let you know once a release will be available

**Comment by yekta** [comment]
Thanks for the fast response. We’ll keep an eye on it.
