### ISSUE TITLE
Make OpenAI API endpoint configurable

### ISSUE THREAD

**Issue by e-001** [weaviate/weaviate#2854]
We [use a caching proxy](https://github.com/6/openai-caching-proxy-worker) for speed and cost when querying OpenAI. The API endpoint should be user configurable.

**Comment by pdaddyo** [comment]
This would be super useful and seems like a pretty safe change - what would it take to get this merged (we use WCS)?

**Comment by merits11** [comment]
Also needed for Azure OpenAI config.

https://github.com/weaviate/weaviate/blob/master/modules/text2vec-openai/clients/vectorizer.go#L54

We have a wrapper around it but could not use the wrapper since endpoint is hard coded.

**Comment by byronvoorbach** [comment]
For Azure OpenAI config, there's no way for Weaviate to know which embedding model is deployed under this URL. This could cause issues when calling a model that has a different dimensionality.

**Comment by dirkkul** [comment]
you can configure the endpoint now
