### ISSUE TITLE
Make openai api support Azure config

### ISSUE THREAD

**Issue by DreamerLark** [weaviate/weaviate#2855]
i use asure openai api now, and openai api not support api_type,api_version config

**Comment by byronvoorbach** [comment]
Hi @DreamerLark!

We just released Azure support in our latest release:
https://github.com/weaviate/weaviate/releases/tag/v1.18.4

Closing this issue

**Comment by younisshah** [comment]
Is the documentation updated on how to use Azure OpenAI? How does one go about using the Azure OpenAI?
