### ISSUE TITLE
[BUG] Vector additional property doesn't get returned for most hybrid search queries. 

### ISSUE THREAD

**Issue by jpleoAR** [weaviate/weaviate#2858]
# Problem

Adding `vector` as an `_additional` property when using a hybrid search returns an empty list EXCEPT when `alpha == 0` .

It can be seen in this [example](https://link.weaviate.io/40xERQL). The vectors only return when `alpha` is 0. 

# Steps to reproduce

Run a hybrid search query with `alpha` set to 0 and with `vector` in `_additional`. This will return the embedded vectors with the data object as expected. 

To see the issue, run a hybrid search query with `alpha` set to anything other than 0 and with `vector` in `_additional`. The `vector` fields return the embedded vectors with the data object as expected. 

# Screenshots

`alpha = 0.1`

![image](https://user-images.githubusercontent.com/125312623/229201549-c5ebcb34-24b4-49da-a1c0-10facf0dbdef.png)

`alpha = 0`

![image](https://user-images.githubusercontent.com/125312623/229201587-14f48241-46fb-4aea-b5ae-9702ee4b5352.png)

**Comment by etiennedi** [comment]
Thanks for the detailed report, we'll take it from here.
