### ISSUE TITLE
Hardening cluster apis for unauthenticated usage

### ISSUE THREAD

**Issue by DengYiping** [weaviate/weaviate#2860]
Currently, there is no authentication method for peer to peer connections. We need to either:
 - put TLS in front of it
 - do a basic token auth

**Comment by etiennedi** [comment]
Great point. We'll discuss this internally and see what a good solution would be. Ideally, something that can be automated in the helm chart creation, so users don't have to worry about an additional step during setup.

**Comment by etiennedi** [comment]
Closed in #3476, released as a 1.21.x patch.
