### ISSUE TITLE
Integration with Nvidia Triton Inference Server

### ISSUE THREAD

**Issue by junwang-wish** [weaviate/weaviate#2861]
Hi, I have a custom-built Triton inference server that can be called like
```
input_json = {
   "inputs":[
      {	
      "name": "text",
      "shape": [1, 1],
      "datatype": "BYTES",
      "data": ["hello world"]
      }
   ]
}
res = requests.post('http://localhost:8000/v2/models/text_encoder/versions/1/infer', json=input_json).json()
```
with res looking like
```
{'model_name': 'text_encoder',
 'model_version': '1',
 'parameters': {'sequence_id': 0,
  'sequence_start': False,
  'sequence_end': False},
 'outputs': [
  {'name': 'text_embedding',
   'datatype': 'FP32',
   'shape': [1, 512],
   'data': [-0.150348961353302,
    -0.2633885443210602,
    -0.5655118227005005,
    ...
   }
]
```
Triton is widely used in industry to deploy models, does Weaviate have integration for Triton? Or I have to implement a custom module? Since its API (based on kserve) is significantly different from Cohere / OpenAI, I assume both part 1 and 2 mentioned here https://weaviate.io/developers/contributor-guide/weaviate-modules/how-to-build-a-new-module need to be customized? Would appreciate if there are any pointers, doing the integration between Triton and Weaviate would open doors to wide industry adoption.

**Comment by antas-marcin** [comment]
Nice! Which models is your nvidia triton inference container able to run? all text to vector models?
You can create a module based on [text2vec-cohere](https://github.com/weaviate/weaviate/tree/master/modules/text2vec-cohere) one, the only part that you would have to change is the [client](https://github.com/weaviate/weaviate/tree/master/modules/text2vec-cohere/clients) part and adjust the requests / responses that would match your API

**Comment by junwang-wish** [comment]
Thanks @antas-marcin yeah for working with weaviate, it'd be all text2vec model. Will look into your pointers.

**Comment by bobvanluijt** [comment]
Hi @junwang-wish - I just wanted to say this looks very interesting! So I'll be 👀 developments

**Comment by bobvanluijt** [comment]
PS:
Are you on our [Slack](https://weaviate.io/slack)?

**Comment by junwang-wish** [comment]
Thanks @bobvanluijt I don't have Slack, at the moment, I am still researching the right tools for my use case:

- 1 billion 512/768 dim vectors in E-commerce space
- P95 latency < 50ms
- Allow filtering, for example, similar products under 5 dollars with attribute_a=val_b
- Make deploy with k8s simple
- Access control so random people in the company cannot delete my data
- Redundancy so if one k8s pod dies, it doesn't make a dent to downstream teams

Once the research gets to a more mature stage, I will keep you posted.
