### ISSUE TITLE
graphql will return null for bigint(snowflakeID).

### ISSUE THREAD

**Issue by GargantuaX** [weaviate/weaviate#2862]
graphql will return null for bigint(snowflakeID). Data can be normally obtained through weaviate's restApi /v1/objects/uuid

graphql response:
```
{
	"data": {
		"Get": {
			"Chunk": [{
				"_additional": {
					"distance": null,
					"id": "d07d6590-2742-4c12-b745-827ffc0b04a0",
					"score": "0.008196721"
				},
				"chunk_id": null,
				"created_at": "2023-03-31T02:26:55.952Z",
				"document_id": null,
				"origin_page_number": 39,
				"text": "***",
				"user_id": null
			}]
		}
	}
}
```

/v1/objects/d07d6590-2742-4c12-b745-827ffc0b04a0 response:
```
{
	"class": "Chunk",
	"creationTimeUnix": 1680230844444,
	"id": "d07d6590-2742-4c12-b745-827ffc0b04a0",
	"lastUpdateTimeUnix": 1680230844444,
	"properties": {
		"chunk_id": 1641628187827904800,
		"created_at": "2023-03-31T02:26:55.952Z",
		"document_id": 1641628109553799200,
		"origin_page_number": 39,
		"text": "***",
		"user_id": 1641320646480760800
	},
	"vectorWeights": null
}
```

**Comment by etiennedi** [comment]
See https://github.com/weaviate/weaviate/issues/1563. It's a limitation of the GraphQL spec which does not support `int64` because of JS compatibility. No good solution at the moment other than to convert the `int64` into a string.

**Comment by GargantuaX** [comment]
> See #1563. It's a limitation of the GraphQL spec which does not support `int64` because of JS compatibility. No good solution at the moment other than to convert the `int64` into a string.

As you said, I used string instead of int64 to store bigint.
I am more concerned, will using strings reduce weavite query efficiency? We know that comparing numbers is easier than strings.

**Comment by etiennedi** [comment]
In Weaviate v1.18, filters on `string`/`text` do not use bitmap indexing yet. But they will in v1.19. So, yes, there would be a small penalty using filters (only if they match many objects). But that should go away with the next version.

**Comment by GargantuaX** [comment]
Thank you for your reply. I have fully understood it
