### ISSUE TITLE
UX suggestion: set vectorizer if module config is set

### ISSUE THREAD

**Issue by bobvanluijt** [weaviate/weaviate#2869]
I noticed that _not_ setting a `vectorizer` when creating a schema _with_ setting a vectorizer in the `moduleConfig`, results in the vectorizer defaulting to `none`.

Suggestion: if a user sets a vectorizer config, but the user doesn't explicitly set the vectorizer to `none` _or_ when auto-schema is used. Can the class config default to the vectorizer that's set in the configuration?

E.g.,

```json
{
    "classes": [
        {
            "class": "Publication",
            "moduleConfig": {
                "text2vec-openai": {
                    "model": "ada",
                    "modelVersion": "002",
                    "type": "text"
                }
            },
            "properties": []
        }
    ]
}
```

This sets `vectorizer` to `none`, but might be good to default to `text2vec-openai`

**Comment by dirkkul** [comment]
as we are moving away from users having to write the schema by hand and having the clients generate it for them, I think we should leave it like it is
