### ISSUE TITLE
Batch add_reference() error while links to other class objects property..

### ISSUE THREAD

**Issue by dilipmane** [weaviate/weaviate#2874]
We are trying to achieve some class object property reference links to other class objects property with same types in order to reduce process time for the vectorization and memory. But We are facing issue with below error when calling to batch.add_reference() error as
`{'error': [{'message': "ref batch: write inverted batch: write additions: no bucket for prop 'section_content__meta_count' found"}]}`
**Setup for test:** We are using weaviate 1.18.2 version:
We followed steps as per reference example https://weaviate.io/developers/weaviate/client-libraries/python#manual-batching
Can you please provide complete setup of example or is there any bug in provided example steps.

**Comment by databyjp** [comment]
Hi @dilipmane - I just tried this exactly by copy/pasting the code exactly to a blank local instance, using a clean Docker-compose file from the website (https://weaviate.io/developers/weaviate/installation/docker-compose) and it worked. 

(Instantiated with:)
```
import weaviate
client = weaviate.Client("http://localhost:8080")
```

Did you copy/paste the code exactly when you encountered this error? (Note the code block has a copy button on the top right corner.)

**Comment by dirkkul** [comment]
closing for lack of response
