### ISSUE TITLE
Cannot pass string[] as a datatype

### ISSUE THREAD

**Issue by koussay-khelil** [weaviate/weaviate#2879]
While creating the schema I am doing the following 
`{
      dataType: [
        "string[]", // array of strings
      ],
      description: "The documents",
      name: "documents",
    },`
But I get the following error 
`Error: usage error (422): {"error":[{"message":"property 'documents': invalid dataType: Unknown primitive data type 'string[]'"}]}`
Not sure if am doing something wrong, but everything appears to be done while respecting the docs. 
I tried it on python and on TS and I get the same error on both.

**Comment by rahuldhagote** [comment]
> While creating the schema I am doing the following `{ dataType: [ "string[]", // array of strings ], description: "The documents", name: "documents", },` But I get the following error `Error: usage error (422): {"error":[{"message":"property 'documents': invalid dataType: Unknown primitive data type 'string[]'"}]}` Not sure if am doing something wrong, but everything appears to be done while respecting the docs. I tried it on python and on TS and I get the same error on both.

try "text[]" instead of "string[]" it might work

**Comment by rahuldhagote** [comment]
try "text[]" instead "string[]" it might work

**Comment by etiennedi** [comment]
What Weaviate (Server) version are you using?

**Comment by koussay-khelil** [comment]
Could it be an image issue, the docker image that I am using is semitechnologies/weaviate:1.1.0

**Comment by koussay-khelil** [comment]
It was a versioning issue, updating to version 1.18.0 fixed that problem. Thank you guys for your help, closing this now.
