### ISSUE TITLE
BM25 variable name "query" and property field names incorrectly used as search terms

### ISSUE THREAD

**Issue by amcgeough** [weaviate/weaviate#2894]
The BM25 variable name "query" and the property field names ("title" in below example) are incorrectly getting used as search terms by the BM25 operator, this is visible in the response field explainScore if the text field being searched contains the terms "query" or "title".

`import weaviate

client = weaviate.Client("http://localhost:8080")

bm25 = {
  "query": "fox",
  "properties": ["title"],  # by default, all properties are searched
}

result = (
  client.query
  .get("Article", ["title", "_additional {score explainScore} "])
  .with_bm25(bm25)
  .do()
)

print(result)`

**Comment by hsm207** [comment]
@amcgeough you can't pass `bm25`  to `with_bm25`. You need to splice it i.e. `with_bm25(**bm25)`.

Details here: weaviate/weaviate-python-client#270
