### ISSUE TITLE
caching vectors

### ISSUE THREAD

**Issue by rahuldhagote** [weaviate/weaviate#2896]
while using inbuilt vectorizer is there any cache saving or parameter to avoid vectorization of repetative rows.

**Comment by trengrj** [comment]
For updates there is detection https://github.com/weaviate/weaviate/blob/db36c56403037e69366b3191f8b9b0ab6672dc07/modules/text2vec-transformers/vectorizer/objects.go#L127-L130 to only update the vector if dependent fields are updated.
