### ISSUE TITLE
How does BM25 score the documents?

### ISSUE THREAD

**Issue by chasingegg** [weaviate/weaviate#2918]
In `inverted/bm25_searcher.go`, there is a function `func (b *BM25Searcher)  createTerm...`, it computes idf by `termResult.idf = math.Log(float64(1)+(N-n+0.5)/(n+0.5)) * float64(duplicateTextBoost)`, I'm wondering if the N, n is the metric just in one shard not the whole collection?

**Comment by etiennedi** [comment]
Correct, `N` only refers to the local shard. The same applies to the mean property length which also only knows the means within it's shard. This is similar to Elasticsearch where sharding also influences BM25 scoring.
