### ISSUE TITLE
I am trying to run the nearText demo from the manual, it returns an error saying unknown argument nearText

### ISSUE THREAD

**Issue by teowave** [weaviate/weaviate#2924]
Hi

I am trying to run the nearText demo from the manual, it returns an error saying unknown argument nearText

# my code: 

import os
import json
import weaviate

import config
import json_prettify

debug = True

auth_config = weaviate.auth.AuthApiKey(api_key=config.WEAVIATE_API_KEY)

#Instantiate the client with the authentication configuration
client = weaviate.Client(
    url="https://semantic-help-jduh3m7i.weaviate.network", 
    auth_client_secret=auth_config,
    additional_headers={
        "X-OpenAI-Api-Key": config.OPENAI_API_KEY
    }
)

if debug: 
    #confirm connection
    try:
        meta_info = client.get_meta()
        print("Connected to Weaviate instance.")
        print(f"Weaviate version: {meta_info['version']}")
    except weaviate.exceptions.CommunicationError as e:
        print(f"Error: {e}")

#json_prettify.prettify(client.schema.get())

if debug: 
    print("\n--- Normal query data follows\n")
    json_prettify.prettify(client.data_object.get())

nearText = {"concepts": ["biology"]}

result = (
    client.query
    .get("Question", ["question", "answer", "category"])
    .with_near_text(nearText)
    .with_limit(2)
    .do()
)

print("\n--- neartext query data follows\n")
print(json.dumps(result, indent=2))

# **** The results of the run: 
Connected to Weaviate instance.
Weaviate version: 1.18.3

--- Normal query data follows

{
  "deprecations": null,
  "objects": [
    {
      "class": "Question",
      "creationTimeUnix": 1681910855730,
      "id": "1e397458-c8cc-48b9-a8b7-331e3584999e",
      "lastUpdateTimeUnix": 1681910855730,
      "properties": {
        "answer": "Antelope",
        "category": "ANIMALS",
        "question": "Weighing around a ton, the eland is the largest species of this animal in Africa"
      },
      "vectorWeights": null
    },
    {
      "class": "Question",
      "creationTimeUnix": 1681910855730,
      "id": "28c4a765-bc33-44ff-9eda-3b36364e86d2",
      "lastUpdateTimeUnix": 1681910855730,
      "properties": {
        "answer": "Liver",
        "category": "SCIENCE",
        "question": "This organ removes excess glucose from the blood & stores it as glycogen"
      },
      "vectorWeights": null
    },
    {
      "class": "Question",
      "creationTimeUnix": 1681910855730,
      "id": "2c81bb9b-c0af-47e5-ad54-6e994c7d2a08",
      "lastUpdateTimeUnix": 1681910855730,
      "properties": {
        "answer": "Elephant",
        "category": "ANIMALS",
        "question": "It's the only living mammal in the order Proboseidea"
      },
      "vectorWeights": null
    },
    {
      "class": "Question",
      "creationTimeUnix": 1681910855730,
      "id": "3b282c8c-42bc-4ead-b715-84c3e9840b69",
      "lastUpdateTimeUnix": 1681910855730,
      "properties": {
        "answer": "the diamondback rattler",
        "category": "ANIMALS",
        "question": "Heaviest of all poisonous snakes is this North American rattlesnake"
      },
      "vectorWeights": null
    },
    {
      "class": "Question",
      "creationTimeUnix": 1681910855730,
      "id": "3f2f1d2b-86be-48a5-a536-eb6f10dceb12",
      "lastUpdateTimeUnix": 1681910855730,
      "properties": {
        "answer": "the atmosphere",
        "category": "SCIENCE",
        "question": "Changes in the tropospheric layer of this are what gives us weather"
      },
      "vectorWeights": null
    },
    {
      "class": "Question",
      "creationTimeUnix": 1681910855730,
      "id": "6ab4b5e1-d375-41d3-ab62-b029b167c6f3",
      "lastUpdateTimeUnix": 1681910855730,
      "properties": {
        "answer": "DNA",
        "category": "SCIENCE",
        "question": "In 1953 Watson & Crick built a model of the molecular structure of this, the gene-carrying substance"
      },
      "vectorWeights": null
    },
    {
      "class": "Question",
      "creationTimeUnix": 1681910855730,
      "id": "76e3f20f-d15b-4684-b584-a553a8889ea0",
      "lastUpdateTimeUnix": 1681910855730,
      "properties": {
        "answer": "species",
        "category": "SCIENCE",
        "question": "2000 news: the Gunnison sage grouse isn't just another northern sage grouse, but a new one of this classification"
      },
      "vectorWeights": null
    },
    {
      "class": "Question",
      "creationTimeUnix": 1681910855730,
      "id": "819de221-220d-466b-bac9-fcf4f517cf4b",
      "lastUpdateTimeUnix": 1681910855730,
      "properties": {
        "answer": "the nose or snout",
        "category": "ANIMALS",
        "question": "The gavial looks very much like a crocodile except for this bodily feature"
      },
      "vectorWeights": null
    },
    {
      "class": "Question",
      "creationTimeUnix": 1681910855730,
      "id": "c6899778-603a-4e2e-99b4-1f9829f4de36",
      "lastUpdateTimeUnix": 1681910855730,
      "properties": {
        "answer": "wire",
        "category": "SCIENCE",
        "question": "A metal that is ductile can be pulled into this while cold & under pressure"
      },
      "vectorWeights": null
    },
    {
      "class": "Question",
      "creationTimeUnix": 1681910855730,
      "id": "ff0ef458-8339-4fea-aebf-ef23fca9e702",
      "lastUpdateTimeUnix": 1681910855730,
      "properties": {
        "answer": "Sound barrier",
        "category": "SCIENCE",
        "question": "In 70-degree air, a plane traveling at about 1,130 feet per second breaks it"
      },
      "vectorWeights": null
    }
  ],
  "totalResults": 10
}

--- neartext query data follows

{
  "errors": [
    {
      "locations": [
        {
          "column": 24,
          "line": 1
        }
      ],
      "message": "Unknown argument \"nearText\" on field \"Question\" of type \"GetObjectsObj\". Did you mean \"nearVector\" or \"nearObject\"?",
      "path": null
    }
  ]
}

# The error message: 
{
  "errors": [
    {
      "locations": [
        {
          "column": 24,
          "line": 1
        }
      ],
      "message": "Unknown argument \"nearText\" on field \"Question\" of type \"GetObjectsObj\". Did you mean \"nearVector\" or \"nearObject\"?",
      "path": null
    }
  ]
}

I am copying things straight from the manual, asked GPT4, no results as to the source of the error

Grateful for some steering here.

**Comment by trengrj** [comment]
Near text requires a vectorizer module to be used. This will convert the text into a vector for both objects stored in Weaviate and queries. Our quickstart shows how to do this using OpenAI https://weaviate.io/developers/weaviate/quickstart/end-to-end. If you don't have a vectorizer module enabled you need to supply your own vectors (using near vector).
