### ISSUE TITLE
Weaviate python library doesn't have needed methods for the abstractions

### ISSUE THREAD

**Issue by Ryangr0** [weaviate/weaviate#2935]
Using
```
langchain~=0.0.146
openai~=0.27.4
haystack~=0.42
tiktoken~=0.3.3
weaviate-client~=3.15.6
aiohttp~=3.8.4
aiodns~=3.0.0
python-dotenv~=1.0.0
Jinja2~=3.1.2
pandas~=2.0.0
```

```
def create_new_memory_retriever():
    """Create a new vector store retriever unique to the agent."""

    client = weaviate.Client(
        url=WEAVIATE_HOST,
        additional_headers={"X-OpenAI-Api-Key": os.getenv("OPENAI_API_KEY")},
        # auth_client_secret: Optional[AuthCredentials] = None,
        # timeout_config: Union[Tuple[Real, Real], Real] = (10, 60),
        # proxies: Union[dict, str, None] = None,
        # trust_env: bool = False,
        # additional_headers: Optional[dict] = None,
        # startup_period: Optional[int] = 5,
        # embedded_options=[],
    )
    embeddings_model = OpenAIEmbeddings()

    vectorstore = Weaviate(client, "Paragraph", "content", embedding=embeddings_model.embed_query)
    
    return TimeWeightedVectorStoreRetriever(vectorstore=vectorstore, other_score_keys=["importance"], k=15)  
```
Time weighted retriever
```
...
    def get_salient_docs(self, query: str) -> Dict[int, Tuple[Document, float]]:
        """Return documents that are salient to the query."""
        docs_and_scores: List[Tuple[Document, float]]
        docs_and_scores = self.vectorstore.similarity_search_with_relevance_scores( <----------======
            query, **self.search_kwargs
        )
        results = {}
        for fetched_doc, relevance in docs_and_scores:
            buffer_idx = fetched_doc.metadata["buffer_idx"]
            doc = self.memory_stream[buffer_idx]
            results[buffer_idx] = (doc, relevance)
        return results
...
```

`similarity_search_with_relevance_scores` is not in the weaviate python client.

Whose responsibility is this? Langchains? Weaviates? I'm perfectly fine to solve it but I just need to know on whose door to knock.

All of langchains vectorstores have different methods under them and people are writing implementation for all of them. I don't know how maintainable this is gonna be.

**Comment by hsm207** [comment]
@Ryangr0 is `similarity_search_with_relevance_scores` just another name for doing a bm25 query and returning the results and scores? If yes, then the `similarity_search_with_relevance_scores` implementation in langchain can wrap the bm25 search in the python client (example [here](https://weaviate.io/developers/weaviate/api/graphql/vector-search-parameters#example-query))

**Comment by Ryangr0** [comment]
https://github.com/hwchase17/langchain/blob/master/langchain/vectorstores/faiss.py

This is what's being used in the example from the documentation: https://python.langchain.com/en/latest/use_cases/agent_simulations/characters.html?highlight=generative%20agents

I've made that code work for weaviate, but then I ran into another issue which actually is also gonna happen for FAISS. And now I'm running into something else of which I'm unsure what it is of why it's happening:

```
  File "/opt/venv/lib/python3.11/site-packages/langchain/retrievers/time_weighted_retriever.py", line 72, in get_salient_docs
    docs_and_scores = self.vectorstore.similarity_search_with_relevance_scores(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/langchain/vectorstores/base.py", line 94, in similarity_search_with_relevance_scores
    docs_and_similarities = self._similarity_search_with_relevance_scores(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/langchain/vectorstores/weaviate.py", line 412, in _similarity_search_with_relevance_scores
    docs_and_scores = self.similarity_search_with_score(query, k=k)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/langchain/vectorstores/weaviate.py", line 383, in similarity_search_with_score
    score = np.dot(res["_additional"]["vector"], self._embedding.embed_query(query))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in dot
ValueError: shapes (384,) and (1536,) not aligned: 384 (dim 0) != 1536 (dim 0)
```

**Comment by hsm207** [comment]
the error means that the dimension of the vectors stored inside weaviate is 384 but the query embedding is 1536.

how did you get the vectors into weaviate?

also, i recommend implementing the search using `near_vector`  (see [example](https://weaviate.io/developers/weaviate/api/graphql/vector-search-parameters#example)) and ` .with_additional("certainty")` to get the score (make sure to set the distance metric to cosine). That way, you can rely on the backend to do the retrieval and scoring.

**Comment by Ryangr0** [comment]
I understand what was wrong, I made a mistake and was using the wrong model in my embedding. Other than that, the responsibility for the change in code that's needed for this to work (I passed my test) lies in the langchain repo, so I'll move over there and close this. Thank you for your help! In the process I found two other bugs.
