### ISSUE TITLE
text2vec-openai organization header

### ISSUE THREAD

**Issue by clotodex** [weaviate/weaviate#2979]
Right now weaviate only accepts the KEY as an environment variable and uses it internally for the authorization header. However if you are part of multiple organizations, setting the ORG header is also necessary, and right now not possible.

```
curl https://api.openai.com/v1/... \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -H "OpenAI-Organization: $OPENAI_ORG_ID"
```

The current workaround is to either set the default org in openai or to have multiple accounts - both are not very flexible, so it would be amazing if weaviate could support this.

**Comment by dirkkul** [comment]
this is supported now: https://weaviate.io/developers/weaviate/modules/qna-openai#organization-name
