### ISSUE TITLE
Deleting class does not drop all caches, cause OOMkill in kubernete

### ISSUE THREAD

**Issue by nvbkdw** [weaviate/weaviate#2981]
Deleting a class is not able to delete all cache from memory. I use client.schema.delete_class to delete a class. But after the deletion, the vector index still has some cache still remain in memory and not be clean up by GC. 

For example,[compressedVectorsCache has initial size of 25000, and not be dropped when dropping the index.](https://github.com/weaviate/weaviate/blob/244bf2cede66febfaa58d36aa1668dc7428e2f48/adapters/repos/db/vector/hnsw/index.go#L612-L617)

**Comment by etiennedi** [comment]
Thanks for raising this, @nvbkdw and @vikasmehta-ib

@dirkkul, this might be a good opportunity to see if anything else is not adequately cleaned up on a class delete. E.g. create 1000 classes, delete them again and compare the heap profile before and after.

**Comment by dirkkul** [comment]
Closed by https://github.com/weaviate/weaviate/pull/2997

We do not create the cache anymore for the uncompressed case, so we cannot forget to clean it up.
The other elements in the heap that are connected with a deleted class are getting cleaned up over time (at least on my machine), eg if you wait for a few minutes they should disappear
