### ISSUE TITLE
Only one cycle manager per shard

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#2983]
Currently, all buckets (and the HNSW index) spawn their own cycle managers. This leads to >20 cycle managers per class, even with few properties. 

_Note: This investigation was done before the filter cache was removed, so there were still a lot of hash buckets. The removal of hash buckets probably reduces that number. Nevertheless, we need to reduce the number_.

Instead, anything that requires a cycle manager should get an option to get an outside cycle manager passed in to. This addresses multiple problems:

- We gain control over how we want cycle events to fire. For example, if 20 buckets all need to flush, we can control if we want to flush them sequentially or in parallel. With independent cycle managers, this is more or less random and when they all decide to flush at the same time, it's easy to spawn over 10,000 hardware threads.
- We reduce the number of active timers. In my test in #2947, I managed to run 37,000 shards on one node. That lead to almost 800,000 cycle managers. I could see `runtime.adjustTimers` take up a huge percentage of CPU time.

**Comment by trengrj** [comment]
Closed by https://github.com/weaviate/weaviate/pull/3025
