### ISSUE TITLE
Deactivate/Activate shard/tenant in MT setting (experimental)

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#3007]
In line with the shard temperature idea mentioned in #2970, it could be helpful to tell Weaviate to explicitly "deactivate" a class (or a tenant in a multi-tenancy situation) without deleting it. Deactivated would simply mean that the class is not initialized and therefore not consuming memory. It cannot be queried (Alternative: it will be auto-activated when receiving a query), but also consumes no resources.

cc @nvbkdw @vikasmehta-ib

**Comment by etiennedi** [comment]
I vaguely remember @ju-bezdek mention something similar quite a while ago.

**Comment by ju-bezdek** [comment]
Wow, your memory must be powered by weaviate... even I had trouble recalling discussing this with you🤣

I think in the past I was thinking about some kind of archive function. The files would be still on disk, but not actively loaded into memory until request.

Feature to "offload" class from memory and bring it back without the need to restart weaviate would be cool.

I'd also consider a more complex scenario - if you have 1000+ classes, it is very likely that many of them are dormant for most of the time. Keeping all the data in memory is an overkill, however. I know that you guys are doing something like that on WCS, I assume it is being done on the k8s level by turning on/off the pod. This is not a viable way for the class-based multitenancy nor for the new proposal. If weaviate could handle this (you'd allow such a feature on the class level), that would be ultra cool:). This is probably a whole new Proposal, but I think it is good to consider it in the context of this one. In the end, both "solutions" are targeting the same problem (high memory consumption for dormant data).

**Comment by etiennedi** [comment]
> Wow, your memory must be powered by weaviate... even I had trouble recalling discussing this with you🤣

Or I'm just hallucinating 😆 

Awesome, thanks for the feedback and great points. Once the ability to switch between active and inactive exists, it should be fairly trivial to add a "automatically turn inactive if idle for x" kind of setting.

**Comment by ju-bezdek** [comment]
> Or I'm just hallucinating 😆
... it's not even that surreal to be suspicious that you're an LLM powered bot anymore;)

>  it should be fairly trivial to add a "automatically turn inactive if idle for x" kind of setting.
cool, just keep this in mind when implementing multitenancy, since after that, disabling just class won't be "fine enough" anymore.

**Comment by trengrj** [comment]
Completed in https://github.com/weaviate/weaviate/pull/3353
