### ISSUE TITLE
how to check for vectors which don't have a particular property through the where_filter

### ISSUE THREAD

**Issue by ravi160822** [weaviate/weaviate#3017]
I have a property named "excluded" which I set to True, when I want to exclude a vector, but I don't have this property for every vector, how do I write a where_filter condition which would consider the vectors for which "excluded" property is not there or "excluded" property is set to False

**Comment by dandv** [comment]
You can do this using a [nested `where` filter](https://weaviate.io/developers/weaviate/search/filters#nested-multiple-conditions):

```graphql
{
  Get {
    MyClass(where: {
      operator: Or
      operands:[
        {
      	  path: "excluded"
      	  operator: IsNull
      	  valueBoolean: true
        },
        {
          path: "excluded"
          operator: Equal
          valueBoolean: false
        }
      ]
    }) {
      excluded
    }
  }
}
```

For the `IsNull` to work, you need to [configure indexing nulls in the class definition](https://weaviate.io/developers/weaviate/api/graphql/filters#filter-by-null-state).
