### ISSUE TITLE
Error 401 with a Openshift deployment and text2vec-openai vectorizer

### ISSUE THREAD

**Issue by mcapitanio** [weaviate/weaviate#3043]
Hi,

I am getting this kind of error in a Openshift (v 3.11) deployment of Weaviate version 1.19.0

`{'error': [{'message': 'update vector: failed with status: 401%!!(MISSING)(EXTRA string=)'}]}`

I am using the same configuration I use with a local instance, for which I can correctly index using the text2vec-openai vectorizer configured for Azure OpenAI.

I have checked the schema and it has the correct valorizaton for moduleConfig (the one it is working locally).
Also the variable for the Azure OpenAI api key is correctly valorized in the Openshift pod, so I can't understand the reason of this error which seems a not managed error.

Someone has already faced this kind of problem?

**Comment by antas-marcin** [comment]
@mcapitanio which version of Weaviate are you using?

**Comment by antas-marcin** [comment]
> I am getting this kind of error in a Openshift (v 3.11) deployment of Weaviate version 1.19.0


ohhh it's Weaviate `v1.19.0` I have read it too fast

**Comment by mcapitanio** [comment]
Hi @antas-marcin,

yeah, v1.19.0. Is it a known problem or am I missing something in my configuration to make Weaviate work on OpenShift?

**Comment by antas-marcin** [comment]
@mcapitanio can you share the schema config with me? especially I'm interested in the `moduleConfig` part

**Comment by antas-marcin** [comment]
and are you sure you are on `v1.19.0` version not on `v1.18.0`? can you also show me a response from `/v1/meta` endpoint?

**Comment by mcapitanio** [comment]
We have just moved on Openshift 4 and on that OCP version the error does not occur anymore with v1.18.0.

Then we also moved to v.1.19.5, but under OCP 4, not tested on OCP 3.

**Comment by antas-marcin** [comment]
@mcapitanio Thanks! just closed it
