### ISSUE TITLE
The offset parameter is not working with hybrid search

### ISSUE THREAD

**Issue by junbetterway** [weaviate/weaviate#3076]
We have tried using [Weaviate hybrid search](https://weaviate.io/developers/weaviate/api/graphql/vector-search-parameters#hybrid) for our search platform and it provides better results as it can now catch both keywords matching and vector search. 

However, unlike `nearText` search - it seems that the **offset** parameter is not working though you are allowed to configure it, as can be seen below:

```
    HybridArgument hybridArg = weaviateClient.graphQL().arguments().hybridArgBuilder()
            .query(request.getQuery())
            .alpha(0.5f)
            .build();
    Get getBuilder = weaviateClient.graphQL().get()
            .withClassName(className)
            .withFields(...)
            .withLimit(25)
            .withOffset(25)
            .withHybrid(hybridArg);
```

From above configuration regardless of the configured **offset** - it will always return the top 25 results and will not get the next 26 - 50 items (even if offset was set to 25)

Hence, is this an expected behavior for hybrid search and there is no way for me to get a somehow paginated or offset-based results using hybrid?

**Comment by bobvanluijt** [comment]
Addressed here: https://github.com/weaviate/weaviate/pull/3083

**Comment by bobvanluijt** [comment]
I'm assuming it will become part of the next release (@etiennedi)

**Comment by etiennedi** [comment]
Thanks - will take care of it.

**Comment by etiennedi** [comment]
Update: There were some unresolved review comments which is why it wasn't merged yet. They have since been resolved and this will indeed be included in `v1.19.8` coming in the next 24h.

**Comment by junbetterway** [comment]
Thanks to you both @etiennedi @bobvanluijt - can't wait to try this new release. Cheers!

**Comment by junbetterway** [comment]
I can confirm this is now working after upgrading to `1.19.8` 🍻

**Comment by junbetterway** [comment]
I can confirm this is now working after upgrading to 1.19.8 🍻
