### ISSUE TITLE
Handle and Retry on Azure OpenAI Rate Limit exceptions

### ISSUE THREAD

**Issue by felixthekraut** [weaviate/weaviate#3095]
When using `text2vec-openai`, in particular with Azure, it is possible to hit the rate limit of the Azure APIs. The API communicates this via a HTTP 429 response and the following message:

> Requests to the Embeddings_Create Operation under Azure OpenAI API version 2022-12-01 have exceeded call rate limit of your current OpenAI S0 pricing tier. Please retry after 9 seconds. Please go here: https://aka.ms/oai/quotaincrease if you would like to further increase the default rate limit.

Ideally this error should be caught and the client should wait to retry the operation after the wait period indicated in the error message.

This issue occurs frequently when using `weaviate-cli` to import large batches of objects.

**Comment by dirkkul** [comment]
there is rate limit control for openAI available :)
