### ISSUE TITLE
Chinese tokenization support

### ISSUE THREAD

**Issue by Wohoholo** [weaviate/weaviate#3102]
Hi,
I want to use both chinese search and vector search with bm25.How can i set properties tokenization?
It seems to not work when i set tokenization: "word"

**Comment by trengrj** [comment]
Hi @Wohoholo we don't have a feature supporting Chinese tokenization right now but would be open to adding it. Would adding a `tokenization: "chinese"` option using https://github.com/go-ego/gse suit?

**Comment by Wohoholo** [comment]
thanks! I would try to add it by myself and expect your implement!

**Comment by Wohoholo** [comment]
> I want to use Japanese tokenization for BM25 and hybrid search. I hope this feature will be implemented.

I am using jieba to tokenize chinese texts and joining  splitted word with whitespace for now.
Like "你好朋友" -> "你好 朋友"，save this text and can use bm25. Because English tokenization is using whitespace

**Comment by syanatan1997** [comment]
Thank you!!
I will use your method as workaround.

However, save text with whitespace may increase the token of ChatGPT 3.5, so I still want Chinese, Japanese Tokenization feature.
My ideal is that weaviate run tokenization during only BM25 search to get answer.

**Comment by shadowlinyf** [comment]
> Hi @Wohoholo we don't have a feature supporting Chinese tokenization right now but would be open to adding it. Would adding a `tokenization: "chinese"` option using https://github.com/go-ego/gse suit?

This sounds great.

**Comment by shadowlinyf** [comment]
> 

do the whitespaces also be embedded by embedding model?
could this effect the search performance in vector seach aspect?

**Comment by Wohoholo** [comment]
whitespace will be embedded if your input text with whitespace.
In my method, raw text will be embbed and keyword with whitespace will be saved.
Like this:
raw_text = "xxxxx"
embed = embedding_model(raw_text) # saved for vector search 
keyword = " ".join(tokenizer(raw_text)) # saved for bm25 search

embed will be saved in vector property of my schema
keyword will be saved as text in my schema

**Comment by shadowlinyf** [comment]
> whitespace will be embedded if your input text with whitespace. In my method, raw text will be embbed and keyword with whitespace will be saved. Like this: raw_text = "xxxxx" embed = embedding_model(raw_text) # saved for vector search keyword = " ".join(tokenizer(raw_text)) # saved for bm25 search
> 
> embed will be saved in vector property of my schema keyword will be saved as text in my schema

if kyword and embed are in to field can you still use hybrid search?

**Comment by Wohoholo** [comment]
yep，like this
response = (
    client.query
    .get("JeopardyQuestion", ["question", "answer"])
    .with_hybrid(
        query="food",
        vector=vector
    )
    .with_limit(3)
    .do()
)

**Comment by shadowlinyf** [comment]
> yep，like this response = ( client.query .get("JeopardyQuestion", ["question", "answer"]) .with_hybrid( query="food", vector=vector ) .with_limit(3) .do() )

Thank you

**Comment by yangboz** [comment]
> do the whitespaces also be embedded by embedding model?
> could this effect the search performance in vector seach aspect?

for Chinese tokenizer , GanymedeNil/text2vec-large-chinese  is the  solution.

**Comment by dirkkul** [comment]
we support chinese now, see here: https://weaviate.io/developers/weaviate/config-refs/schema#gse-and-trigram-tokenization-methods
