### ISSUE TITLE
Difference between bm25 and nearText search

### ISSUE THREAD

**Issue by warjiang** [weaviate/weaviate#3115]
can anyone explained that the difference between bm25 and nearText mentioned in [similarity search](https://weaviate.io/developers/weaviate/search/similarity). I already know that bm25 is a common algorithm in reversted indices. Then how nearText implemented in weaviate

**Comment by warjiang** [comment]
And any plan to support to multi language tokenizer like chinese, we always use jieba tokenizer for sentence or content in chinese. It seems that if i extend tokenizer type and implement customize tokenizer, i will work:
![image](https://github.com/weaviate/weaviate/assets/6478745/8b17835c-fc08-484e-bee4-e38fa2122fec)

**Comment by dirkkul** [comment]
bm25: search by keyword
near_text: semantic search using vector embeddings

We support tokenizers for japanese, chinese and korean: https://weaviate.io/developers/weaviate/config-refs/schema#gse-and-trigram-tokenization-methods
