### ISSUE TITLE
Metrics for Status Codes: OK vs User Error vs Server Error

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#3116]
We want to be able to easily observe what fraction of requests succeed, what fraction fails due to user errors, and what fails due to server errors. Similarly, we want to be able to track this over time to see if ratios change, e.g. after a significant update. 

## Goals
1. Three new counter metrics are introduced which track
    1. number of successful requests (i.e. 2xx status code)
    2. number of requests failed due to user error (i.e. 4xx status code)
    3. number of requests failed due to server error (i.e. 5xx status code)
2. Any time a user makes a request one of those 3 counters is increased
3. In addition, the error is logged (structured logging) in a way that it is easy to identify. The use case is the following: If the operator sees an increase of error rate, the next step for them is to check the logs and see which errors occurred.
4. Verify that existing status codes are used correctly. Most importantly we don't want to have any "false positives" for server errors. I.e. something that was a user error, but was incorrectly tracked as a server error will look like an issue in the metrics when it's not. 

## Tech Notes
Note that the GraphQL spec does not actually use HTTP status codes. The actual status code is always `200 OK` even when the `errors` field is filled. In this case, we don't want to track the actual status code, but rather the cause of the failure. Some examples:
- User uses invalid GraphQL syntax and GraphQL can't be parsed -> user error
- User has valid GraphQL, but a logical error (for example using two arguments at the same time where only one is allowed) -> user error
- The user did everything correctly, but the request still failed for any reason -> server error

## Priorities
Ideally, we would have metrics + logs for every single request. If time is limited then we should proceed in the following order:
1. Metrics for all GraphQL `Get {}` requests
2. Error logs for all GraphQL `Get {}` requests
3. Metrics for all `/v1/objects` requests
4. Error logs for all `/v1/objects` requests
5. Metrics + Error logs for everything else

**Comment by antas-marcin** [comment]
Metrics added. Closing issue.

```
requests_total{api="graphql",class_name="n/a",query_type="",status="ok"} 839
requests_total{api="graphql",class_name="n/a",query_type="",status="user_error"} 3
requests_total{api="graphql",class_name="n/a",query_type="Aggregate",status="user_error"} 8
requests_total{api="graphql",class_name="n/a",query_type="Explore",status="user_error"} 3
requests_total{api="graphql",class_name="n/a",query_type="Get",status="user_error"} 28
requests_total{api="rest",class_name="n/a",query_type="batch",status="ok"} 1143
requests_total{api="rest",class_name="n/a",query_type="classification",status="ok"} 9
requests_total{api="rest",class_name="n/a",query_type="misc",status="ok"} 14
requests_total{api="rest",class_name="n/a",query_type="nodes",status="ok"} 12
requests_total{api="rest",class_name="n/a",query_type="objects",status="ok"} 839
requests_total{api="rest",class_name="n/a",query_type="objects",status="server_error"} 4
requests_total{api="rest",class_name="n/a",query_type="objects",status="user_error"} 56
requests_total{api="rest",class_name="n/a",query_type="schema",status="ok"} 552
requests_total{api="rest",class_name="n/a",query_type="schema",status="user_error"} 55
```
