### ISSUE TITLE
index_name being modified when querying with python client

### ISSUE THREAD

**Issue by rlancemartin** [weaviate/weaviate#3132]
hi all,

im auditing all of LangChain's vectorstore integrations. 

this works:
```
# Init 
weaviate_url = url
client = Client(url=weaviate_url, auth_client_secret=auth.AuthClientPassword(xxx,xxx))
embeddings = OpenAIEmbeddings()
vectorstore= Weaviate.from_texts(splits, embeddings, client=client)
```

i run search:
```
# Search
query = "What is micrograd?"
matched_docs = vectorstore_new.similarity_search(query,k=1)
matched_docs
```
 
and it works.

under the hood, a random `index_name` is created and text key is hard-coded [here](https://github.com/hwchase17/langchain/blob/6ac120f29957c569741db665de1f0c662c555193/langchain/vectorstores/weaviate.py#L416):
```
Index - LangChain_214a4ded03fd4121ad5f5d0c0c36e051
Text key - text
```

now, I want to get this index that I've created (e.g., in another process or session):
```
# Create connection
vectorstore_weviate = Weaviate(client=client)
```

this will fail because we need  `'index_name'` and `'text_key'`:
```
TypeError: __init__() missing 2 required positional arguments: 'index_name' and 'text_key'
```

so, i re-generate the `vectorstore` with a specific `index_name`:
```
vectorstore= Weaviate.from_texts(splits, embeddings, client=client, index_name="karpathy-gpt")
```

confirm the passed index is set [here](https://github.com/hwchase17/langchain/blob/6ac120f29957c569741db665de1f0c662c555193/langchain/vectorstores/weaviate.py#L414):
```
Index - karpathy-gpt
Text key - text
```

good. but when we run search:
```
query = "What is micrograd?"
matched_docs = vectorstore_new.similarity_search(query,k=1)
matched_docs
```

there is an error. 
```
    227     raise ValueError(f"Error during query: {result['errors']}")
    228 docs = []
--> 229 for res in result["data"]["Get"][self._index_name]:
    230     text = res.pop(self._text_key)
    231     docs.append(Document(page_content=text, metadata=res))

KeyError: 'karpathy_gpt'
```

i print the `result` [here](https://github.com/hwchase17/langchain/blob/11ab0be11aff9128c12178b5ebf62071985fb823/langchain/vectorstores/weaviate.py#L223) that we get `result = query_obj.with_near_vector(vector).with_limit(k).do()`:

```
{'data': {'Get': {***'Karpathy_gpt'***: [{'text': "would like to take you through building of micrograd. Now micrograd is this library that I released on GitHub about two years ago but at the time I only uploaded the source code and you'd have to go in by yourself and really figure out how it works. So in this lecture I will take you through it step by step and kind of comment on all the pieces of it. So what is micrograd and why is it interesting? Thank you. Micrograd is basically an autograd engine. Autograd is short for automatic gradient"}]}}}
```

we see that the index_name has been modified with an **upper case start char `Karpathy_gpt`.**

this results in a key error when we use our index_name key, `karpathy_gpt`:

it's possible that the index-name is being modified somewhere on the `Weaviate` side?

`result` from Weaviate [here](https://github.com/hwchase17/langchain/blob/11ab0be11aff9128c12178b5ebf62071985fb823/langchain/vectorstores/weaviate.py#LL219C9-L219C71) includes the modified index name.

**Comment by hsm207** [comment]
@rlancemartin in weaviate, index name must [start with a capital letter](https://weaviate.io/developers/weaviate/configuration/schema-configuration#create-a-class).

If the user does not do this, then the weaviate client will do it, [starting in 3.2.4](https://github.com/weaviate/weaviate-python-client/blob/4104c3a0bea3e129a332d335c0b2e29bb3cc0e73/docs/changelog.rst#L484-L488).

**Comment by rlancemartin** [comment]
Ah, ok! That explains it :)
