### ISSUE TITLE
Bug report: Faulty Result for `with_where` filter  with whole sentence

### ISSUE THREAD

**Issue by MaxHam** [weaviate/weaviate#3141]
Hi,

I have a database with a class where I want to filter a sentence value like 'What is love' for multiple properties.
I use the Python SDK.

The filter looks like the following:
```python
withFilter = {
        "operator": "Or",
        "operands": [
                    {
                        "path": [column1],
                        "operator": "Like",
                        "valueText": "*What is love*"
                    }, 
                    ...,
                    {
                        "path": [columnN],
                        "operator": "Like",
                        "valueText": "*What is love*"
                    }
        ]
    }
```

For some reason the query does not return results that contain this sentence but a lot more results. The results seem to look like they match one of the words in the sentence and not the whole sentence as one.

Is this a known bug ? Is there a way how I can rephrase the filter to achieve what I intended?

**Comment by dandv** [comment]
While not entirely intuitive, this is known behavior. You may want to [change the tokenization](https://forum.weaviate.io/t/weaviate-faq/128#why-does-the-equal-operator-on-a-text-field-return-objects-that-_include_-the-operand-3) of the schema. Suggestions to better document this are welcome.

**Comment by MaxHam** [comment]
Hi,
thanks for responding so fast ! 
I would suggest adding the `Like` operand [here](https://weaviate.io/developers/weaviate/api/graphql/filters#filter-behavior-of-multi-word-queries-in-equal-operator) as well. I guess thats why I did not find it in the docs.

**Comment by MaxHam** [comment]
Yes, exactly 👍
