### ISSUE TITLE
Unknown argument "nearText"

### ISSUE THREAD

**Issue by rlancemartin** [weaviate/weaviate#3142]
I'm using the python client with langchain -
```
from langchain.vectorstores import Weaviate
from langchain.embeddings.openai import OpenAIEmbeddings
index_name = "Karpathy_gpt"
embeddings = OpenAIEmbeddings()
vectorstore_new = Weaviate.from_texts(splits, embeddings, client=client, index_name=index_name, text_key = "text")
```

test it -
```
query = "What is micrograd?"
matched_docs = vectorstore_new.similarity_search(query,k=1)
matched_docs
```

it works.

now, i try to connect -
```
vectorstore_weviate = Weaviate(client=client,index_name=index_name,text_key = "text")
```

and re-test -
```
query = "What is micrograd?"
matched_docs = vectorstore_weviate.similarity_search(query,k=1)
matched_docs
```

error -
```
Cell In[17], line 2
      1 query = "What is micrograd?"
----> 2 matched_docs = vectorstore_weviate.similarity_search(query,k=1)
      3 matched_docs

File ~/Desktop/AI/langchain-fork/langchain/vectorstores/weaviate.py:170, in Weaviate.similarity_search(self, query, k, **kwargs)
    160 """Return docs most similar to query.
    161 
    162 Args:
   (...)
    167     List of Documents most similar to the query.
    168 """
    169 if self._by_text:
--> 170     return self.similarity_search_by_text(query, k, **kwargs)
    171 else:
    172     if self._embedding is None:

File ~/Desktop/AI/langchain-fork/langchain/vectorstores/weaviate.py:202, in Weaviate.similarity_search_by_text(self, query, k, **kwargs)
    200 result = query_obj.with_near_text(content).with_limit(k).do()
    201 if "errors" in result:
--> 202     raise ValueError(f"Error during query: {result['errors']}")
    203 docs = []
    204 for res in result["data"]["Get"][self._index_name]:

ValueError: Error during query: [{'locations': [{'column': 28, 'line': 1}], 'message': 'Unknown argument "nearText" on field "Karpathy_gpt" of type "GetObjectsObj". Did you mean "nearVector" or "nearObject"?', 'path': None}]
```

**Comment by hsm207** [comment]
the first vectorstore is:

```
vectorstore_new = Weaviate.from_texts(splits, embeddings, client=client, index_name=index_name, text_key = "text")

```

the second one is:
```
vectorstore_weviate = Weaviate(client=client,index_name=index_name,text_key = "text")
```

you did not specify an embeddings in the second one and did not set up weaviate with a vectorizer too. Therefore, [nearText is unknown to weaviate](https://weaviate.io/developers/weaviate/api/graphql/vector-search-parameters#neartext).

This issue has been discussed before in the langchain repo. See hwchase17/langchain#4742

**Comment by rlancemartin** [comment]
> the second one is:

i want to re-connect to my initial vectorstore, `vectorstore_new` e.g., in another process or session.

how can i do that?

i assumed supplying: `Weaviate(client=client,index_name=index_name,text_key = "text")` is sufficient?

**Comment by hsm207** [comment]
Reusing the same client will reconnect to the same vector store. The problem is that the query that langchain passes to the weaviate client for execution is different (even though you are calling the same search function) for reasons explained in the langchain issue I linked to in my previous reply. I recommended stepping through the langchain code in both examples to understand the difference.

**Comment by rlancemartin** [comment]
Hmm. Had a quick look, but it's not quite clear if a fix has been implemented. What concrete next steps should be taken? If we cannot easily connect to and query an existing index, then then we should fix ASAP. I'm happy to help, but will need guidance on what specifically needs to be done as I don't have context.

**Comment by rlancemartin** [comment]
In particular, you mentioned that [this PR](https://github.com/hwchase17/langchain/pull/4365)
resolved the above linked ticket. 
Is that true?

Or, does my query need to be modified in order to query from an existing index? If so, please advise.

But, if we cannot (1) create an index and then (2) later context to it / query from it easily, we need to fix as this is basic functionality that every vectorstore should support.

**Comment by rlancemartin** [comment]
> > In particular, you mentioned that https://github.com/hwchase17/langchain/pull/4365
> 
> resolved the above linked ticket. Is that true?
> 
> 
> 
> it is fixed in the sense that passing `by_text=False` when you initialise the weaviate vector store avoids this problem.

Interesting. Will test tmrw!

**Comment by hsm207** [comment]
@rlancemartin just to be sure we are on the same page, here's a [demo notebook](https://gist.github.com/hsm207/99fa2c0edee75826f277dbba8e604ea7) to show you what I mean

**Comment by rlancemartin** [comment]
Thanks! Very helpful. Yes I saw the by_test in original docs, but was not sure what it did or that it is critical for proper function. This is great to know.
