### ISSUE TITLE
Is there a plan to support aggregation with hybrid search?

### ISSUE THREAD

**Issue by junbetterway** [weaviate/weaviate#3159]
In Weaviate Aggregate search, one can combine a vector search (**e.g.,** nearText) with an aggregation, in case you want to know the total results found for a given query.

Is there a plan to support aggregation with hybrid search?

**Comment by nfleury** [comment]
Same here, I'm currently using hybrid search with limit, but no way to get the total results of a query (not great if you want to paginate)

Could the total results be added as an aditional field ? That would be more optimal than having to run another aggregate query

**Comment by BradAtGames** [comment]
+1 we were able to do aggregations on hybrid searches via graphql in 1.22, but certain things don't work as expected 

- There is no properties field in AggregateObjects${class}HybridInpObj
- AggregateObjects${class}WhereInpObj seems to be ignored or buggy (i.e. valueText white matches documents where that path is set to green).

**Comment by junbetterway** [comment]
We would love this to be supported 🙏 but at the same time, know what lies on the complexity if it will not be prioritized.  Thanks!

**Comment by graphinglife** [comment]
+1

This is a massive need from our team and would love for this to be supported.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dirkkul** [comment]
This is supported since a while, maybe the documentation is missing 🤔 

Here is an example for the python client (which uses GQL under the hood for aggregations): https://github.com/weaviate/weaviate-python-client/blob/0332fb5a1e4531ed18641e44f4b05e8f246e7a50/integration/test_collection_aggregate.py#L303
