### ISSUE TITLE
[Bug][UX] Add strict vectorization timeout, have clear error message

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#3165]
Occasionally a 3rd-party vectorizer like OpenAI or Cohere times out. The user interprets this as "an issue with Weaviate". Instead, we should make sure that:

* A vectorization request takes at most `n seconds` where `n` is a reasonable value that is long enough to make sure vectorization completes on the happy path, but short enough to fail before any kind of infra-level (e.g. loadbalacner) timeout hits
* After the timeout has occurred, the error message should be very clear to indicate that the (3rd-party) vectorizer has timed out and this is not a Weaviate issue.

**Comment by Valdegg** [comment]
I was the user that raised this issue.

Maybe add a reminder to the error message, telling the user that since e.g. OpenAI's text-embedding-ada-002 is temporarily not working, that you the user can try out a different embedding model.

**Comment by dirkkul** [comment]
I think this was done, there is a PR that adds it and I remember seeing error messages with a timeout
