### ISSUE TITLE
Does Weaviate allow for implementing brute force KNN search?

### ISSUE THREAD

**Issue by zekriHichem** [weaviate/weaviate#3182]
Does Weaviate allow for implementing brute force KNN search?

**Comment by Ponkkkkk** [comment]
Is there any update regarding this?

**Comment by ahmedharbaoui** [comment]
+1

**Comment by zekriHichem** [comment]
Hello,
 I am confident that the correct response to this question is "NO."
Weaviate has not natively implemented force KNN search. This response is
based on my own experience and not from the development team.

Thank you.
Hicham
Le dim. 24 sept. 2023 à 07:43, ahmedharbaoui ***@***.***> a
écrit :

**Comment by dirkkul** [comment]
https://weaviate.io/developers/weaviate/concepts/vector-index#flat-index

AFAIK this is brute force
