### ISSUE TITLE
generative-palm - cannot unmarshal  prediction.predictions.safetyAttributes

### ISSUE THREAD

**Issue by atomicjets** [weaviate/weaviate#3206]
Just started receiving the error:
 
 "error": "unmarshal response body: json: cannot unmarshal array into Go struct field prediction.predictions.safetyAttributes of type clients.safetyAttributes",
 
 When trying to run a generative-palm command.
 
 Tested with docker latest and docker semitechnologies/weaviate:1.19.11

**Comment by systemz64** [comment]
We have a managed WCS instance on 1.20.5 and that also shows the same issue. this is a pretty big blocker!

**Comment by byronvoorbach** [comment]
@atomicjets & @systemz64 Google updated the response API for their generative output. Working on a fix

**Comment by byronvoorbach** [comment]
PR is ready: https://github.com/weaviate/weaviate/pull/3418

**Comment by StefanBogdan** [comment]
@antas-marcin @byronvoorbach I think this can be closed, it was fixed, no?
