### ISSUE TITLE
Feature request: Cross-tenant queries

### ISSUE THREAD

**Issue by nstiurca** [weaviate/weaviate#3242]
I'm very excited about the upcoming multi-tenancy feature. I'd like to additionally request the ability to provide multiple tenant keys for a single query to handle cases where users belong to multiple tenancies.

Some details about my use case:

My use case is around loose groups of small (~5) groups of users. But group composition can change, and a user can be in multiple groups. I expect that normally a group will contain <10 users, and a user will normally be in less than 5 groups. Power users might be in maybe a few dozen groups (let's say <50), and power groups might have up to 20 users. Two groups might incidentally contain some or all of the same users.

With the current MT feature, I have to make an awkward tradeoff of what maps to a tenant. 

Option 1 is I will map tenants to users. So each user will have a tenantcy they own, and possibly a few tenantcies that are shared with them. I can then query ~1-5 tenants at the same time on the user's behalf depending on which data they want to access, and just do some merging of weaviate results as needed. The main problem with this approach though is for some queries I might retrieve ~5x as much data as I'm interested in, and there's query time overhead to merge the results. Eg, say a user is looking for the top 10 objects relating to, I dunno, cats. Potentially, there could be a few relevant results coming from each other user (tenant) in the group they're in, or all the results might be from one user (tenant) of the group. So if that group has 5 users (tenants), I'd have to query each user (tenant) for 10 documents, and throw 40 of the 50 away after I merge the results.

The alternative would be to map tenants to groups. Then each user request would be a single query against the relevant group (tenant). (Users wouldn't need to access multiple groups simultaneously in my case.) That would simplify queries, but would instead introduce overhead if a user wants to copy data to multiple groups they're in. Most users would want most/all of their data available in each group they're in, so this would basically blow up the size of the overall DB by like 5x. Not to mention potential synchronization issues...

Summary: for my use case, there isn't a clear mapping of tenants to a set of documents which users are accessing due to sharing of documents across users in loose, non-exclusive groups. With the current MT feature, I have to either have some significant inefficiencies when querying data, or when storing data. The ability to query against a small handful of tenants simultaneously would solve my issues.

**Comment by nstiurca** [comment]
Alternative solution for sharing data across tenants: perhaps objects could have more than 1 tenant key associated with it. Ie, the vector could be added to multiple indexes, but the rest of data doesn't need to be replicated.

**Comment by etiennedi** [comment]
Thanks for the request. Looks like, we forgot to add the `backlog` label, so that this would appear on the Roadmap page for voting. Another user has since request the same thing [here](https://github.com/weaviate/weaviate/issues/3242).

Let's move it to the other one. Feel free to repost your motivation there and don't forget to upvote. Thanks!
