### ISSUE TITLE
RelativeScoreFusion not working with BM25 results in hybrid search

### ISSUE THREAD

**Issue by TimonTjeH** [weaviate/weaviate#3243]
When i try to do a hybrid search with a relativeScoreFusion, an alpha of 0.5 and a autocut of 1. Only vector results are returned in the result set. But i also want to have all the keyword results. Is this a bug or is this done on purpose?

For example:

Alpha: 0.5
fusionType: rankedFusion
query: "Example 1"
results set 1:
- Example 1 (BM25)
- Example 2 (Vector)
- Example 3 (Vector)
- Example 4 (Vector)
- Example 5 (Vector)
- Example 6 (Vector)

Alpha: 0.5
fusionType: relativeScoreFusion
query: "Example 1"
results set 1:
- Example 2 (Vector)
- Example 3 (Vector)
- Example 4 (Vector)

**Comment by dirkkul** [comment]
Hi,

what do you mean with "only vector results are returned in the result set"? 

Would it be possible to create a small example? Or a query with a public dataset (like here https://pypi.org/project/weaviate-demo-datasets/)?

**Comment by TimonTjeH** [comment]
In these images you can see the query and the result. When the fusionType is rankedFusion the first result is a BM25 result (elementId 15291) as you can see in the explainScore. But when i change my fusionType to relativeScoreFusion the BM25 result (elementId 15291) is not in the result as you can see. Only results based on vector are there, while i am expecting the BM25 (elementId 15291) result to be included. It looks like when the fusionType is relativeScoreFusion it is a full context search and keyword matches become irrelevant.

![Scherm­afbeelding 2023-07-11 om 11 38 22](https://github.com/weaviate/weaviate/assets/74238242/28e3aa04-ff8e-4468-b860-669bf733cc35)
![Scherm­afbeelding 2023-07-11 om 11 38 05](https://github.com/weaviate/weaviate/assets/74238242/e70cf66f-3728-4a52-bcd6-c3376e6378f2)

**Comment by dirkkul** [comment]
can you give this image a try? semitechnologies/weaviate:preview-fix-explain-score-with-new-hybrid-algo-8c563f2

the scores were summed up correctly before, but explainscore wasn't and only contained the vector search part.

**Comment by TimonTjeH** [comment]
I still have the same issue with the new image. I think i found the issue, in the image below you can see that the score of the BM25 result gets normalized to 0. I think thats why the expected result is never given because the score is just to low. I hope i gave you enough information to solve this problem.

![Scherm­afbeelding 2023-07-11 om 15 20 28](https://github.com/weaviate/weaviate/assets/74238242/94f920f9-23fc-42f2-a2f1-009e469f0829)

**Comment by dirkkul** [comment]
Could you give this image a try? semitechnologies/weaviate:preview-fix-explainscore-with-hybrid-search-and-relativescorefusion-7696126

If there is only a single BM25 result for your query the old image would asign a score of 0 to it. That could explain why you don't see it

**Comment by TimonTjeH** [comment]
I tried that image and that fixed the problem for me :)

**Comment by dirkkul** [comment]
Thanks for confirming, will be in the next stable release
