### ISSUE TITLE
is it possible to self host the console ?

### ISSUE THREAD

**Issue by atnomoverflow** [weaviate/weaviate#3246]
is it possible to self host the console ?

**Comment by mlmetzner** [comment]
cant you just connect to your self hosted instance via the normal console link?

**Comment by atnomoverflow** [comment]
it's a business requirement to have the console self hosted.

**Comment by genandre** [comment]
+1 This might stop us from adopting Weaviate as a solution. AFAIK most of the other vector search solutions give a self-hosted admin console.

**Comment by khu834** [comment]
+1 to this

**Comment by Dawn1iu** [comment]
+1 to this

**Comment by shanzhaigege** [comment]
+1 thanks

**Comment by xpatronum** [comment]
+1 thanks

**Comment by andrewisplinghoff** [comment]
It is quite easy to run your own GraphiQL application for accessing Weaviate. Not sure if it has all the functionality offered in the cloud-hosted console, but AFAIK it is also the backbone of the cloud-hosted console.

As a start, you need to create a React application if you do not already have one - e.g. here is a simple tutorial for creating a Hello World application: https://medium.com/@shubhamnagar234/create-react-app-hello-world-cb501aa9d9f1.
Now to add the GraphiQL UI to your application, you can find instructions here:
https://github.com/graphql/graphiql/blob/main/packages/graphiql/README.md#using-as-package

To have GraphiQL access your Weaviate instance, create the `createGraphiQLFetcher` similar to the following (you'll need to retrieve your Weaviate API Key from somewhere or remove the headers part if you are running an unsecured instance):
```
const fetcher: Fetcher = createGraphiQLFetcher({
    url: "<WEAVIATE_URL>/v1/graphql",
    headers: {
        Authorization: `Bearer ${weaviateApiKey}`
    },
});
```

**Comment by dirkkul** [comment]
we dont offer the console for selfhosting atm, personally I use https://firecamp.io/ to send local requests

**Comment by smoothdvd** [comment]
Try working on it...

Next.js + shadcn/ui

<img width="1335" alt="Screenshot 2024-12-21 at 11 45 59 PM" src="https://github.com/user-attachments/assets/f1808a48-967b-4da0-bac7-07f129abf12b" />

Any advice or comment ?
