### ISSUE TITLE
422v 

### ISSUE THREAD

**Issue by mdabir1203** [weaviate/weaviate#3253]
Creating vector store...
Error: usage error (422): {"error":[{"message":"class name \"Document\" already exists"}]}
    at file:///mnt/c/Users/user/Downloads/Projects_Hack/Chat-i-nette/App/node_modules/weaviate-ts-client/dist/index.mjs:1:7218
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at run (/mnt/c/Users/user/Downloads/Projects_Hack/Chat-i-nette/App/ingest.ts:116:5)

**Comment by etiennedi** [comment]
Hi, you can use the [Weaviate Support Forum](https://forum.weaviate.io/c/support/6) for getting help with how to use Weaviate and support.
