### ISSUE TITLE
Alarming costs with the Reranker - Cohere API

### ISSUE THREAD

**Issue by eostis** [weaviate/weaviate#3266]
<img width="1195" alt="image" src="https://github.com/weaviate/weaviate/assets/1785759/f8542e8d-e6c7-48cc-9432-84984885b026">

In the last few days, I got a tremendous increase of Cohere's charges, due to the Reranker - Cohere API .
(It has been settled with the Cohere support team)

Calls were made from automated tests to rerank 10 titles. Let say 100 tests. Titles are pretty short, like "Post title keyword".

100 calls with 10 titles should cost $0.1, according to the pricing:
<img width="728" alt="image" src="https://github.com/weaviate/weaviate/assets/1785759/65c5e7bb-9a94-43c3-8e6e-c91d84dd3d12">

I'm still trying to understand if I need to warn my WooCommerce customers !

**Comment by antas-marcin** [comment]
@eostis we are aware of this issue. I'm working on fixing this ASAP. Our next patch release will have a fix for this issue included. I will let you know once it will done.

**Comment by antas-marcin** [comment]
@eostis please upgrade to [v1.20.2](https://hub.docker.com/layers/semitechnologies/weaviate/1.20.2/images/sha256-ec396e3f692e8207e72124991f8128442e03e4eb6cb7740c1189d31f5adc1eb1?context=explore) it contains a fix for this issue

**Comment by eostis** [comment]
@antas-marcin Looks good indeed. Thanks.

<img width="1470" alt="image" src="https://github.com/weaviate/weaviate/assets/1785759/b4595e40-957d-4ec6-97ee-27f2139266d9">
