### ISSUE TITLE
[Proposal] Development/Preview/Beta Release

### ISSUE THREAD

**Issue by ashokrajab** [weaviate/weaviate#3294]
It's great to see that Weaviate is constantly rolling out patches/updates. Having said that, it would be great if we have a development/preview release before the roll out of the stable release. This development/preview release should always be up-to-date with all the merged pull requests since the last stable release. 

- This will helpful for the issue reporter to test whether the bugfix resolves the reported issue.
- Get feedback from the community on bleeding edge features before a stable release.

**Comment by dirkkul** [comment]
we build an image for each PR after after each merge into stable/XX + main - these can be always used to try things out and provide feedback
