### ISSUE TITLE
Hybrid Search Scoring improvements with small limits (Overfetching)

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#3317]
With small limits, minor changes to the limit can lead to differences in Hybrid scoring and therefore different results and scores. With the new oversearch capability for Hybrid Search the internal search limit is higher than the user-specified one and results are cut-off at the end. This stabilizes results when limits change.

**Comment by bhavnicksm** [comment]
Hey! 
I am noticing this issue as well. 

Whenever I set a very high limit in v1.18.3, I would get the same MRR score as when I used v1.21.2 with limit < 10. But the quality of search goes down, since the scoring is not that accurate. 

What ended up happening is my system became **worse** when I moved from v1.18.3 --> v1.21.2 when limit was set to 1.

I hope this gets resolved sooner.

**Comment by dirkkul** [comment]
Hi @bhavnicksm,

just to be sure I'm understanding it correctly:
- With high limits (eg limit==100) the results in 1.18.3 and 1.21.2 are the same but bad
- With a low limit (eg limit <10) the results in 1.18.3 are good but are bad in 1.21.2

We recently introduced a new fusion algo (relative score fusion) that should give better results in general - could you try that out and see if it solves your problem? See here: https://weaviate.io/developers/weaviate/api/graphql/search-operators#hybrid

**Comment by bhavnicksm** [comment]
> Hi @bhavnicksm,
> 
> just to be sure I'm understanding it correctly:
> 
> * With high limits (eg limit==100) the results in 1.18.3 and 1.21.2 are the same but bad
> * With a low limit (eg limit <10) the results in 1.18.3 are good but are bad in 1.21.2
> 
> We recently introduced a new fusion algo (relative score fusion) that should give better results in general - could you try that out and see if it solves your problem? See here: https://weaviate.io/developers/weaviate/api/graphql/search-operators#hybrid

Yes! That's exactly right what's happening. 

Also, thanks for the suggestion, @dirkkul! I would try it out. :))
