### ISSUE TITLE
Docs Say Weaviate is on the AWS Marketplace

### ISSUE THREAD

**Issue by Robbie-Palmer** [weaviate/weaviate#3338]
Weaviate does not appear on the AWS Marketplace: https://aws.amazon.com/marketplace/search/results?searchTerms=weaviate

![image](https://github.com/weaviate/weaviate/assets/8760191/e7daf17d-9cef-43ee-9814-d3605fe24c46)

While the docs says it does: https://weaviate.io/developers/weaviate/installation/aws-marketplace

**Comment by MarionNehring** [comment]
Dear @Robbie-Palmer ,
Thank You so much for the valuable Feedback - WOW you are an early bird adopter of our docs - I love that!
Please have a look now again into the AWS Marketplace - it is there now :D 
Please also let us know if you have more feedback for us - we really value this to improve.

**Comment by etiennedi** [comment]
Please be aware that it is not officially launched yet. For example, currently rollout is limited to specific regions in NA and EU. There is also a chance that there would still be breaking changes (e.g. restructuring the deployment templates) etc. before the official release.

We will let everyone know through an official announcement when it's considered ready. Apologies for making it seem ready when it's still in the testing phase.

**Comment by dirkkul** [comment]
I think we are there now :)
