### ISSUE TITLE
Weaviate OpenAI modules currently don't work for OpenAI organization-level accounts.

### ISSUE THREAD

**Issue by kirby-jobber** [weaviate/weaviate#3340]
# Problem

Right now, vectorization calls with the following schema config **will fail** when the OpenAI API key is associated with an organization in OpenAI.

```
schema = {
    "vectorizer": "text2vec-openai",
    "moduleConfig": {
        "text2vec-openai": {
        "model": "ada",
        "modelVersion": "002",
        "type": "text"
        }
    },
    ... 
```

# Solution

This is because the `text2vec-openai` module configures the client with an API key but not an organization ID.  When an OpenAI API key is associated with an OpenAI organization, clients must be configured with the corresponding organization ID.   Please allow the `text2vec-openai` module to include a `OPENAI_ORGANIZATION_ID` environment variable, and use it to initialize the OpenAI clients.

[Right here in the codebase](https://github.com/weaviate/weaviate/blob/master/modules/text2vec-openai/module.go#L110) we see 

```go
	openAIApiKey := os.Getenv("OPENAI_APIKEY")
	azureApiKey := os.Getenv("AZURE_APIKEY")

	client := clients.New(openAIApiKey, azureApiKey, logger)
```

This should include an optional `os.Getenv("OPENAI_ORGANIZATION_ID")` environment variable.  The relevant `clients.New` function [right here](https://github.com/weaviate/weaviate/blob/master/modules/text2vec-openai/clients/vectorizer.go#L72)  also needs to be configured to accept the organization ID.

I assume this should happen in the other OpenAI modules as well.

**Comment by kirby-jobber** [comment]
It looks like this could be solved by this PR:

https://github.com/weaviate/weaviate/pull/3305

**Comment by kirby-jobber** [comment]
In the meantime, I'm looking for a workaround with [this stackoverflow question](https://stackoverflow.com/questions/76838224/is-it-possible-to-pass-additional-http-headers-along-with-weaviate-module-reques).

Will post any answer here.

**Comment by dirkkul** [comment]
we added support for this in the meantime
