### ISSUE TITLE
Nodes and replicas?

### ISSUE THREAD

**Issue by phlegx** [weaviate/weaviate#3355]
Hi Guys,

with 3 nodes and 3 replicas, isn't it correct that one node/replica then can fail for to be weaviate still be readable and writable?

it seems when I put one node down `read` is still possible:

```
curl -H "Authorization: Bearer xxx" http://weaviate.weaviate.svc.cluster.local/v1/schema
{"classes":[]}
```

but write isn't:

```
curl     -X POST     -H "Authorization: Bearer xxx"     -H "Content-Type: application/json"     -d '{
        "class": "Article",
        "description": "A written text, for example a news article or blog post",
        "properties": [
            {
            "dataType": [
                "string"
            ],
            "description": "Title of the article",
            "name": "title"
            },
            {
            "dataType": [
                "text"
            ],
            "description": "The content of the article",
            "name": "content"
            }
        ]
    }'     http://weaviate.weaviate.svc.cluster.local/v1/schema
{"error":[{"message":"open cluster-wide transaction: broadcast open transaction: tx does not tolerate node failures: node(s) weaviate-2 unhealthy or unavailable"}]}
```

What we have set in Weaviate was: QUORUM (n/2+1)

Weaviate Version: `1.20.5`
Helm Chart Version: `16.4.0`

best 
Martin

**Comment by etiennedi** [comment]
> It seems that for creating schema all nodes/instances are needed to be online since schema uses the `ALL` concept.

This is correct. Schema currently requires `ALL`. We've started discussing alternatives for the schema as well, as `ALL` doesn't really scale to massive clusters. @redouan-rhazouani can say more about this, he is on PTO at this moment though.

**Comment by phlegx** [comment]
@etiennedi Perfect, thanks for the explanation!

Yes it would be really good if also Schema could be created with (in our case) only 2 out of 3 nodes resp. generally speaking with `QUORUM (replication_factor / 2 + 1) `. instead of `ALL`.

I"m sure you guys will find a good solution!

**Comment by phlegx** [comment]
@etiennedi I have one more question that is related to this topic. We are currently doing the backup via API like this:

```
curl --silent --show-error -X POST \
    -H 'Content-Type: application/json' \
    -H "Authorization: Bearer $API_KEY" \
    "http://weaviate.weaviate.svc.cluster.local/v1/backups/s3" -d "$json"
```

But when only 2 out of 3 instances are online we get this error back:

`{"error":[{"message":"cannot resolve hostname for \"weaviate-0\""}]}`

Is this also by design that a backup is not working if not all nodes/instances are up, or i this another issue?

**Comment by etiennedi** [comment]
You bring up a very good point with the backups. Backups were designed before replication existed. Therefore a node being down would mean that you'd always miss data. With replication enabled, that is no longer true.

I've created an [issue here](https://github.com/weaviate/weaviate/issues/3382). Feel free to upvote it.

**Comment by dirkkul** [comment]
closing this - not an issue anymore with RAFT
