### ISSUE TITLE
Long warmup time

### ISSUE THREAD

**Issue by 404-html** [weaviate/weaviate#3357]
I am running Weavieate 1.19.5 with img2vec-pytorch:resnet50  using `docker-compose`.
Database records count: 5 238 881, storage used: 255 GB
Right after spinning the instance with Docker the query is very slow, often times out. After performing some queries (needs to be different image each time) the memory usage increases and the time needed to perform the query decreases. But it needs some time to reach satisfying speed (<1s instead of +10s).

I did some profiling with `pprof`, files can be viewed here:
https://drive.google.com/drive/folders/1bEphE0ewsR6zh3T-CdxJxpMAs1p8nXPy?usp=sharing

Looks like Weaviate needs some time to work on the full speed, and the only way to speed that up is to bomb it with queries. I wonder if that's expected and is there's any other way to achieve full speed quickly?

**Comment by dirkkul** [comment]
We recently invested some time in improving the performance after a restart - in case it is still slow for you, could you provide an example?

Closing this as it is quite old, feel free to create a new one or reopen
