### ISSUE TITLE
Document Config

### ISSUE THREAD

**Issue by jlewi** [weaviate/weaviate#3366]
Is there documentation of the config object anywhere? I couldn't find any documentation or any examples. I searched the repo for "weaviate.conf.json" and "conf.json" and didn't find any sample JSON files.

The code also lacks comments.
https://github.com/weaviate/weaviate/blob/230617ddb1d54d2464344028e113040e2778331f/usecases/config/config_handler.go#L70

The closest I could find to a sample config file was in the helm package.
https://github.com/weaviate/weaviate-helm/blob/master/weaviate/templates/weaviateConfigMap.yaml

It would be great if the Config object could be documented and included in the reference API documentation.

**Comment by jlewi** [comment]
Looks like the configuration file is actually deprecated.

```
{"action":"config_load","config_file_path":"./weaviate.conf.json","level":"info","msg":"Usage of the weaviate.conf.json file is deprecated and will be removed in the future. Please use environment variables.","time":"2023-08-08T07:35:56-07:00"}
```

So probably not worth documenting. Might be worth updating the `help` command so that people know to look at environment variables rather than trying to figure out how to set config.json only to then realize its being deprecated.

**Comment by dandv** [comment]
I've also run into the [strange lack of documentation of the config file](https://forum.weaviate.io/t/how-to-run-weaviate-using-a-binary/100/3?u=aidandv). 

As of v1.25.2, the CLI still claims JSON is the default config file, so this issue should be reopened.

![image](https://github.com/weaviate/weaviate/assets/33569/b0f95dc7-b682-452b-bf68-13c479c43876)

Anyway, the YAML format isn't officially documented either.
