### ISSUE TITLE
Tuning search params

### ISSUE THREAD

**Issue by Ponkkkkk** [weaviate/weaviate#3379]
Hi, is it possible to change the ef search for vector indexing after I create the class and insert all my data? Because from the documentation it seems that I need to reinsert every data in order to change the params.

**Comment by etiennedi** [comment]
You can update `ef` (the search time parameter) any time you like. Only `efConstruction` and `maxConnections` are immutable.

Can you point us to the docs section where the docs imply `ef` cannot be updated, so we can fix it? Thanks.

**Comment by Ponkkkkk** [comment]
Sorry I am new to this, there might be a way to do it in the docs but I can only find the ef params using VectorIndexConfig in the schema. How do you configure it after creating the class?

**Comment by Ponkkkkk** [comment]
So I did some digging around and I am able to find the documentation, kind of embarrassing sorry. But I met an error in crud_schema.pyc,  line 292, in update_config which refer to validate_schema.py, line 85, check_class.
I taken a look at the check class function and print the class_definition.keys() and it returns dict_keys(['class', 'invertedIndexConfig', 'multiTenancyConfig', 'properties', 'replicationConfig', 'shardingConfig', 'vectorIndexConfig', 'vectorIndexType', 'vectorizer']). There seems to exist multiTenancyConfig and replicationConfig whcih are not part of CLASS_KEYS. I do not add any of these keys into the update_config() function. Is there something I am doing wrong?

**Comment by Ponkkkkk** [comment]
There is also error in PROPERTY_KEYS, the returned keys are dict_keys(['dataType', 'indexFilterable', 'indexSearchable', 'name']).

What I did was just call client.schema.update_config('Test', { "vectorIndexConfig": { 'ef': 16 } })

**Comment by dirkkul** [comment]
it looks like your python client is outdated - can you make sure you're running the latest version?

**Comment by dirkkul** [comment]
Can you double check?

The latest client contains these fields, see here https://github.com/weaviate/weaviate-python-client/blob/f5a6864901d57c27764270dc009545cce31539bf/weaviate/schema/validate_schema.py#L22

Are you maybe running some code in an old virtual environment or something?

**Comment by Ponkkkkk** [comment]
I tried uninstalling everything and reinstall it and it doesn’t have this problem. Probably an error in the previous install process.

**Comment by Ponkkkkk** [comment]
I tried uninstalling everything and reinstall it and it doesn’t have this problem. Probably an error in the previous install process.
