### ISSUE TITLE
Support `groupBy` in `hybrid` search queries

### ISSUE THREAD

**Issue by danielknode** [weaviate/weaviate#3408]
Using `groupBy` within a `Get`  query to back out to a higher "Document" granularity when doing searches is an extremely helpful concept that drastically simplifies crazy client-side code.
However, right now, hybrid search is not supported with `groupBy`. It is limited to `near<Media>`  searches. From my perspective, hybrid searches are almost always superior to vector searches. So this causes a situation where users need to choose which feature is more valuable to them since they are mutually exclusive.

Feature request: Add support for using `groupBy` for hybrid searches.

**Comment by rryan2** [comment]
please

**Comment by gopidon** [comment]
+1. In version 1.21.2, this combination was erroring out. In 1.21.4, there is no error but looks like groupBy is ignored when combined with hybrid.

**Comment by dudanogueira** [comment]
Hi! This was added in 1.25+
https://weaviate.io/developers/weaviate/search/hybrid#group-results

Closing this issue! Thanks!
