### ISSUE TITLE
Bug: Multi-node setup: Concurrent Class Delete & Batch Import spawns auto-schema, leads to deadlock & out-of-sync schema

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#3427]
It seems there is a race that is specific to multi-node setups:

* An import is occurring
* The user sends a request to delete a class
* Importing now spawns auto-schema
* The cluster is out of sync, some nodes have the class others don't
* There is a deadlock, all schema-related requests time out until restart
* After restart, nodes don't start up anymore due to the out-of-sync schema

**Comment by VjDharnish** [comment]
Hii Etienne Dilocker, I am Currently Facing the issue you mentioned above, I asked in community forum , didn't receive  the solution yet
{"action":"startup_cluster_schema_sync","diff":["local has 29 classes, but cluster has 30 classes","class Sample_31 exists in cluster, but not in local"],"level":"error","msg":"mismatch between local schema and │
│ {"action":"startup","error":"could not load or initialize schema: sync schema with other nodes in the cluster: corrupt cluster: other nodes have consensus on schema, but local node has a different (non-null) sc

**Comment by dirkkul** [comment]
this was pre-RAFT, so this should not occur anymore
