### ISSUE TITLE
Mention in documentation that ImageBind licensing is non-commercial

### ISSUE THREAD

**Issue by eostis** [weaviate/weaviate#3449]

**Comment by databyjp** [comment]
Hi @eostis thanks for pointing this out. I've added clauses like this to our docs where  OSS models might be used. This is the multi2vec-bind one, for example. 

https://weaviate.io/developers/weaviate/modules/retriever-vectorizer-modules/multi2vec-bind#model-licenses

I have not gone as far to interpret the license itself, however, as I don't want to wade into the territory of legal interpretation. :) 

Thanks!
