### ISSUE TITLE
Improve PQ DX: Remove multi-step process (import, pause, fit, continue importing)

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#3462]
Currently to import with PQ multiple steps are required:

1. Import a specific fraction of the dataset 
2. Pause import to enable PQ
3. Poll API to wait for fitting to complete
4. Continue import

Instead (by making use of [async importing](https://github.com/weaviate/weaviate/issues/3463)) the user should be able to turn on PQ before they even start importing. Then they just import and Weaviate will figure out the rest.

**Comment by trengrj** [comment]
Completed in https://github.com/weaviate/weaviate/pull/3771
