### ISSUE TITLE
[Question] weaviate function

### ISSUE THREAD

**Issue by infordb** [weaviate/weaviate#3469]
I'm testing weaviate, and I have a few questions.

1. Scale Out
Is there a way to redistribute existing class shards when node scales out?
It seems that only newly created classes are assigned shards to added nodes.

2. Scale In
Is there any way to reduce the number of nodes?
drain node

3. repair
Do you provide tools other than read repair to restore data consistency?

3. move shard
Is there a command to move a shard to another node?

**Comment by etiennedi** [comment]
Hi, thanks for the questions.

There are feature requests for all of the above. Please give them an upvote - this will help with our prioritization:

- Dynamic Scaling: https://github.com/weaviate/weaviate/issues/2228 <-- this should cover your points 1+2+4
- Async Replication: https://github.com/weaviate/weaviate/issues/2405 <-- this should cover your point 3

Let me know if those are helpful. Feel free to advocate these feature requests among other users and get them to upvote as well. Thanks!

**Comment by infordb** [comment]
Thank you for your response.
I look forward to adding these features soon.
