### ISSUE TITLE
Replicated shards have different number of objects.

### ISSUE THREAD

**Issue by infordb** [weaviate/weaviate#3470]
### Test Env
Helm Chart : weaviate-16.4.0
weaviate : 1.20.0
weaviate-client :3.23.0
node : 4 
replication factor : 3

### Question
Replicated shards have different number of objects.
During the test, both client and weaviate had no problems.

When I check with the get_nodes_status() api, 
the number of objects in the shard (4QN69jK7p5Bz) is different for each node.

shard : 4QN69jK7p5Bz
weaviate-0 : "objectCount": 1368
weaviate-1 : "objectCount": 1473
weaviate-3 : "objectCount": 1480

```
>>> nodes_status = client.cluster.get_nodes_status()
>>> print(json.dumps(nodes_status, indent=2))
[
  {
    "gitHash": "7865a4a",
    "name": "weaviate-0",
    "shards": [
      {
        "class": "Article",
        "name": "4QN69jK7p5Bz",
        "objectCount": 1368
      },
      {
        "class": "Article",
        "name": "kkj6PqMQNVMO",
        "objectCount": 1920
      }
    ],
    "stats": {
      "objectCount": 3288,
      "shardCount": 2
    },
    "status": "HEALTHY",
    "version": "1.20.0"
  },
  {
    "gitHash": "7865a4a",
    "name": "weaviate-1",
    "shards": [
      {
        "class": "Article",
        "name": "4QN69jK7p5Bz",
        "objectCount": 1473
      },
      {
        "class": "Article",
        "name": "g8IbryVR1FGH",
        "objectCount": 1553
      }
    ],
    "stats": {
      "objectCount": 3026,
      "shardCount": 2
    },
    "status": "HEALTHY",
    "version": "1.20.0"
  },
  {
    "gitHash": "7865a4a",
    "name": "weaviate-2",
    "shards": [
      {
        "class": "Article",
        "name": "g8IbryVR1FGH",
        "objectCount": 1462
      },
      {
        "class": "Article",
        "name": "kkj6PqMQNVMO",
        "objectCount": 1923
      }
    ],
    "stats": {
      "objectCount": 3385,
      "shardCount": 2
    },
    "status": "HEALTHY",
    "version": "1.20.0"
  },
  {
    "gitHash": "7865a4a",
    "name": "weaviate-3",
    "shards": [
      {
        "class": "Article",
        "name": "4QN69jK7p5Bz",
        "objectCount": 1480
      },
      {
        "class": "Article",
        "name": "g8IbryVR1FGH",
        "objectCount": 1552
      },
      {
        "class": "Article",
        "name": "kkj6PqMQNVMO",
        "objectCount": 1846
      }
    ],
    "stats": {
      "objectCount": 4878,
      "shardCount": 3
    },
    "status": "HEALTHY",
    "version": "1.20.0"
  }
]
```
### schema
```

class_obj = {
    "class": "Article",
    "description": "A written text, for example a news article or blog post",
    "properties": [
        {
            "dataType": ["int"],
            "description": "Title of the article",
            "name": "title",
        },
        {
            "dataType": ["text"],
            "description": "The content of the article",
            "name": "content"
        }
    ],
	"replicationConfig": {
        "factor": 3,
   },
   'shardingConfig': {
     'virtualPerPhysical': 128,
     'desiredCount': 3,
     'desiredVirtualCount': 384,
     'key': '_id',
     'strategy': 'hash',
     'function': 'murmur3'
   }   
}

client.schema.create_class(class_obj)
```

### Client Example
```
import weaviate
import json
import random
import time
from weaviate.data.replication import ConsistencyLevel


client = weaviate.Client("http://xxx.xxx.xxx.xxx:80")


def insert(class_name, num, dim):
	
    class_name = class_name
    data_objs=[{'title': num,'content': f"content_{num}"}]

    vectors = [[random.random() for _ in range(dim)] for _ in range(1)]

    with client.batch() as batch:
        for i, data_obj in enumerate(data_objs):
            batch.add_data_object(
                data_obj,
                class_name,
                vector=vectors[i]
            )	
    return vectors[0]


	
def main():

    class_name = "Article"

    # search parameter
    search_params = {
        "metric_type": "L2", 
        "params": {"nprobe": 10}
    }
    
    ## RUN
    total = 1
    while total < 6000:
       
        ## timestamp
        now = time
        stringNow = now.strftime('%Y-%m-%d %H:%M:%S')	
        print("time : {0}".format(stringNow))
        
        ## insert
        vectors = insert(class_name, total, 2)			
        print("Insert vector id {0} / vectors {1} ".format(total, vectors))		
		
        ## search

        response = (
            client.query
            .get("Article", ["title"])
            .with_near_vector({
                "vector": vectors
            })
            .with_limit(1)
            .with_additional(["distance"])
        	.with_additional("id")
           	.with_additional("vector")			
            .do()
        )
        print(json.dumps(response, indent=2))
		
		
		
        ##print("Search Result id {0}  / distance {1} ".format(results[0].ids, results[0].distances))	
        
		
        time.sleep(1)	
		
        if total == 6000:
            print("end of test")

        total = total +1	
	

if __name__ == '__main__':
    main()

```

**Comment by etiennedi** [comment]
Thanks for the report. Can you describe your import process or even provide a script to reproduce this? Especially the fact that you mention there were no errors is unexpected. What consistency level did you specify during importing?

**Comment by redouan-rhazouani** [comment]
Thanks @infordb , for your inquiry.

I conducted a similar tests with the specified settings 
- Weaviate-1.20
- 4 nodes
- 3 shards
- Replication factor 3
- Consistency level set to QUORUM
- Load test to import  25000 objects


**Results:**
The number of objects remained consistent across replicated shards on all nodes (see table below). This consistency arises from a healthy cluster where each node successfully replicated received objects.

```
node=‘weaviate1’ stats={'objectCount': 16428, 'shardCount': 2}
------------------
shard=GnKP9lJwQIiQ, count=8401
shard=uRLggVLvQBMI, count=8027

node=’weaviate2’ stats={'objectCount': 16973, 'shardCount': 2}
------------------
shard=GnKP9lJwQIiQ, count=8401
shard=MMVdOFinRjUc, count=8572

node=’weaviate3’ stats={'objectCount': 16599, 'shardCount': 2}
------------------
shard=MMVdOFinRjUc, count=8572
shard=uRLggVLvQBMI, count=8027

node=’weaviate4’ stats={'objectCount': 25000, 'shardCount': 3}
------------------
shard=GnKP9lJwQIiQ, count=8401
shard=MMVdOFinRjUc, count=8572
shard=uRLggVLvQBMI, count=8027
```
**Replication**
It's essential to note that a successful import job under a specified [consistency level](https://weaviate.io/developers/weaviate/concepts/replication-architecture) doesn't guarantee that all objects have been replicated on all replicas. For instance, write request can succeed even if three out of four nodes are down, except the serving node. An exception to this is when you specify consistency level ALL; in this case, a successful import job ensures consistency in the number of objects.

> Question
> 
> Replicated shards have different number of objects.
> During the test, both client and weaviate had no problems.

This indicates that replication was successful under the specified settings. However, it doesn't necessarily guarantee that objects have been replicated across all replicas. If strong consistency is a requirement, setting the consistency level to ALL is necessary. However, it's essential to note that this might introduce additional latency.

> When I check with the get_nodes_status() api,
> the number of objects in the shard (4QN69jK7p5Bz) is different for each node.
> 
> shard : 4QN69jK7p5Bz
> weaviate-0 : "objectCount": 1368
> weaviate-1 : "objectCount": 1473
> weaviate-3 : "objectCount": 1480

This indicates that there are inconsistencies in your data, likely due to some replicas not successfully replicating certain objects, possibly as a result of network issues.

Weaviate is designed to be eventually consistent. To mitigate any inconsistencies, we have implemented a [read repair](https://weaviate.io/developers/weaviate/concepts/replication-architecture/consistency#tunable-read-consistency) mechanism. Additionally, in the future, we plan to introduce other mechanisms such as async repair and more

**Conclusion**
It appears that Weaviate replication is functioning as intended. For more detailed information, I recommend Weaviate documentation, which explains how leaderless replication works in Weaviate

**Comment by infordb** [comment]
I added the client code used for testing.
Since I did not specify the Consistency Level, it will be Quorum.

The strange thing is that since there are no problems with both the weaviate and the client, 
shouldn't the number of data be the same regardless of the consistency level after a certain period of time?

**Comment by redouan-rhazouani** [comment]
Thanks for your question!

As I mentioned earlier, Weaviate actively addresses inconsistencies using read repair strategy. When querying objects, and based on the selected consistency level, Weaviate compares the data against other replicas, and any inconsistencies are rectified before delivering the result. 

> shouldn't the number of data be the same regardless of the consistency level after a certain period of time?

Absolutely, that will indeed be the case once we have implemented async repairs and other strategies as previously discussed.
Async repairs are on our roadmap, and they are expected to be implemented in the foreseeable future.

**Comment by infordb** [comment]
Thanks for your response.

weaviate seems to have a similar architecture to cassandra.

In the case of cassandra, as long as there is no failure, there is no problem with data consistency regardless of the consystency level.

Of course, the data may be inconsistent for a brief period of time, but after a few seconds there are usually no consistency issues.

This is the part that I find strange.

**Comment by redouan-rhazouani** [comment]
Thanks for your question!

As I mentioned earlier, Weaviate actively addresses inconsistencies using read repair strategy. When querying objects, and based on the selected consistency level, Weaviate compares the data against other replicas, and any inconsistencies are rectified before delivering the result.

> Of course, the data may be inconsistent for a brief period of time, but after a few seconds there are usually no consistency issues?

Absolutely, that will indeed be the case once we have implemented async repairs and other strategies as previously discussed.
Async repairs are on our roadmap, and they are expected to be implemented in the foreseeable future.
