### ISSUE TITLE
MultiTenancy: Add endpoint for checking if tenant exists

### ISSUE THREAD

**Issue by StefanBogdan** [weaviate/weaviate#3472]
I think it would be useful for users that on-board and off-board tenants regularly to be able to check if that tenant still exists or not. Currently it is possible only to list them and then check if it is in the list.

I think a `HEAD` request should be more than enough. 

Let me know if it makes any sense.

**Comment by litlig** [comment]
hey I made my first PR to the project, would like to get your feedback! thanks

**Comment by parkerduckworth** [comment]
Closed by #4155
