### ISSUE TITLE
broadcast_abort_transaction

### ISSUE THREAD

**Issue by fjw666-py** [weaviate/weaviate#3477]
When I try to create a class with java jdk, weaviate client returns failed to respond. The logs at weaviate-docker is {"action":"broadcast_abort_transaction","error":"host \"172.23.0.4:7105\": send http request: Delete \"http://172.23.0.4:7105/schema/transactions/bbb1ad7d-94ca-4856-8981-3cf5b7c4dca0\": context deadline exceeded","id":"bbb1ad7d-94ca-4856-8981-3cf5b7c4dca0","level":"error","msg":"broadcast tx abort failed","time":"2023-08-30T00:30:17Z"}.
The class config is :
    "class": "com.myhexin.jeebasic.aigc.vector.api.request.CollectionSchema",
    "collection_name": "Author_embeddings_2",
    "description": "author",
    "fields": [
        {
            "class": "com.myhexin.jeebasic.aigc.vector.api.request.CollectionField",
            "name": "text",
            "type": "text",
            "description": "pageContent",
            "extension_configurations": {
                "tokenization": "word",
                "index_filterable": true,
                "index_searchable": true
            }
        }
    ],
"extension_configurations": {
    "sharding_config": {
        "virtual_per_physical": 128,
        "desired_count": 1,
        "actual_count": 1,
        "desired_virtual_count": 128,
        "actual_virtual_count": 128,
        "key": "_id",
        "strategy": "hash",
        "function": "murmur3"
    },
    "vector_index_config": {
        "distance": "cosine",
        "ef": -1,
        "ef_construction": 128,
        "max_connections": 64,
        "dynamic_ef_min": 100,
        "dynamic_ef_max": 500,
        "dynamic_ef_factor": 8,
        "vector_cache_max_objects": 1000000000000000,
        "flat_search_cutoff": 40000,
        "cleanup_interval_second": 3,
        "pq": {
            "enabled": true,
            "centroids": 256
        },
        "skip": false
    },
    "replication_config": {
        "factor": 3
    },
    "inverted_index_config": {
        "index_times_stamps": true,
        "index_null_state": true,
        "index_property_length": true
    }
}
}

**Comment by etiennedi** [comment]
Hi, could you submit some steps to reproduce please?

**Comment by fjw666-py** [comment]
> Hi, could you submit some steps to reproduce please?
Thank you for answering my question. 
The problem occurs after I deploying a docker-compose cluster server days. First serveral days, it works without any problem. But after a week, I tried to created a class with factor 3 at the weaviate cluster, the client times out. Then I find  the error log at the server node:  
{"action":"broadcast_abort_transaction","error":"host "172.23.0.4:7105": send http request: Delete "[http://172.23.0.4:7105/schema/transactions/bbb1ad7d-94ca-4856-8981-3cf5b7c4dca0\](http://172.23.0.4:7105/schema/transactions/bbb1ad7d-94ca-4856-8981-3cf5b7c4dca0%5C)": context deadline exceeded","id":"bbb1ad7d-94ca-4856-8981-3cf5b7c4dca0","level":"error","msg":"broadcast tx abort failed","time":"2023-08-30T00:30:17Z"}.
It seems like it connect to the the target server node(172.23.0.4:7105) failed. And the latest logs of server((172.23.0.4)  are only hnsw_vector_cache_prefill.  But the result of /v1/nodes shows the status of all three servers is healthy. I restarted the server node(172.23.0.4), but it did not work. May I ask what the problem is? 
 
The file of docker compose is :
services:
  weaviate-node-1:
    init: true
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:latest
    ports:
    - 8080:8080
    - 6060:6060
    restart: on-failure:0
    volumes:
      - ./data-node-1:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      AUTHENTICATION_APIKEY_ENABLED: 'true'
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: 'jane-secret-key,ian-secret-key'
      AUTHENTICATION_APIKEY_USERS: 'jane@doe.com,ian-smith'
      CLUSTER_HOSTNAME: 'node1'
      CLUSTER_GOSSIP_BIND_PORT: '7100'
      CLUSTER_DATA_BIND_PORT: '7101'

  weaviate-node-2:
    init: true
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:latest
    ports:
    - 8081:8080
    - 6061:6060
    restart: on-failure:0
    volumes:
      - ./data-node-2:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      AUTHENTICATION_APIKEY_ENABLED: 'true'
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: 'jane-secret-key,ian-secret-key'
      AUTHENTICATION_APIKEY_USERS: 'jane@doe.com,ian-smith'
      CLUSTER_HOSTNAME: 'node2'
      CLUSTER_GOSSIP_BIND_PORT: '7102'
      CLUSTER_DATA_BIND_PORT: '7103'
      CLUSTER_JOIN: 'weaviate-node-1:7100'

  weaviate-node-3:
    init: true
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:latest
    ports:
    - 8082:8080
    - 6062:6060
    restart: on-failure:0
    volumes:
      - ./data-node-3:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      AUTHENTICATION_APIKEY_ENABLED: 'true'
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: 'jane-secret-key,ian-secret-key'
      AUTHENTICATION_APIKEY_USERS: 'jane@doe.com,ian-smith'
      CLUSTER_HOSTNAME: 'node3'
      CLUSTER_GOSSIP_BIND_PORT: '7104'
      CLUSTER_DATA_BIND_PORT: '7105'
      CLUSTER_JOIN: 'weaviate-node-1:7100'.

**Comment by dirkkul** [comment]
this should not be an issue anymore with RAFT
