### ISSUE TITLE
ContainsAny not working with text[]

### ISSUE THREAD

**Issue by YanDavKMS** [weaviate/weaviate#3489]
I have tried the new version client (3.23.2) and docker image (1.21.2) with ContainsAny.
int[] works fine but text[] gives an error.

I have the 2 following properties:

            {
                "name": "permissions",
                "dataType": ["int[]"]
            },
            {
                "name": "hierarchy_permissions",
                "dataType": ["text[]"]
            },

Adding documents with values for those fields works fine:

            "permissions": [1,2,3,4],
            "hierarchy_permissions": ["A1","A2","A3"]

Searching with filtering:

    "permission": [3,4],
    "hierarchy_permissions": ["A1","A2"]

fails only on the text field, "hierarchy_permissions"

'message': 'explorer: get class: vector search: object vector search at index autosuggest: shard autosuggest_EPdzpa75dwTR: build inverted filter allow list: nested query: nested clause at pos 1: value type should be []string but is string', 'path': ['Get', 'Autosuggest']

**Comment by YanDavKMS** [comment]
It was my mistake and misusage, I sent the array wrapped in quotes.

**Comment by etiennedi** [comment]
Glad you figure it out. If there's anything that should be clearer in our docs, don't hesitate to let us know. Thanks!
