### ISSUE TITLE
Add telemetry

### ISSUE THREAD

**Issue by bobvanluijt** [weaviate/weaviate#3495]
The following are the requirements for a telemetric service.

* A user should be able to disable the service with a flag: `TELEMETRY: FALSE`
* Should be on by default
* If the instance can't reach the endpoint, that's okay, and it should gracefully fail.
* Should push information with a 2.5 hour interval
* Endpoint is: `https://us-central1-semi-production.cloudfunctions.net/weaviate-telemetry`

# Payload

The following should be POSTed to the endpoint

```json
{
    "machineId": UUID_STR
    "type": STR,
    "version": STR,
    "modules": STR,
    "objs": INT
}
```

`machineId` = random UUID ID associated with the Weaviate instance (can also be cluster)
`type` = `INIT` (when starting up) 
`version` = `STR` Weaviate version
`UPDATE` (when the update is send) `TERMINATE` when the instance is shut down
`modules` = string of enabled modules (e.g., `module-a,module-b`)
`objs` = # of objects as integer

**Comment by daveatweaviate** [comment]
Some thoughts from a [slack conversation](https://weaviate-org.slack.com/archives/C06FNE2KU7L/p1706209788047359). 

Here is a summary of thoughts, please update if I've missed something.

## Endpoint
Replace `us-central1-semi-production` with a Weaviate 'branded' endpoint

## Telemetry flag
Telemetry is per instance.
Telemetry is server based.
Embedded instances work the same as standard ones.
Use an environment variable to turn telemetry on and off.

## HTTP v. HTTPS
Send telemetry info over HTTPS. 
Consider alternatives if HTTPS unavailable (TBD - encryption, not sending, something else)

## Sending interval
Every 24 hours is a better interval.
Ensure requests to all arrive at once.

## Info returned
Consider dropping machine ID
Consider adding OS information

## Logging
On telemetry startup
On telemetry shutdown
Log message sent (if short and infrequent)


## Future thoughts, ideas
Add telemetry on/off toggle to config API when it is available.
Add client type and version (eg: 'Python client v4.1', 'REST no client')
