### ISSUE TITLE
Proposal: Named Vector Properties

### ISSUE THREAD

**Issue by trengrj** [weaviate/weaviate#3501]
This proposal is to allow Named Vector Properties.

A named vector property acts like a normal property and has `dataType = vector`.
Two main use-cases are anticipated:

1. A user has multiple versions of vectors and wants to avoid creating multiple classes.
2. A user has different vectors relating to a single object (such a title vector and a content vector).

This proposal does not cover the multi-dimensional vector case (for instance an array of text chunks relating to one large document).

### Object operations

`/v1/schema` creation will be modified for a new `vector` dataType:

```bash
curl \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{
        "class": "Article",
        "properties": [
            {
                "dataType": [
                    "vector"
                ],
                "name": "titleVec"
            },
            {
                "dataType": [
                    "vector"
                ],
                "name": "contentVec"
            },
            {
                "dataType": [
                    "text"
                ],
                "name": "content"
            }
        ]
    }' \
    http://localhost:8080/v1/schema
```

`/v1/objects` Will still allow the root vector as normal and will validate `vector` types as float point arrays.

```bash
curl \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{
      "class": "Article",
      "vector": [0.3, -0.012, 0.071, ..., -0.09],
      "properties": {
          "content": "bar",
          "titleVec": [0.3, 0.2, 0.6, ..., 0.1]
          "contentVec": [0.1, 0.3, 0.6, ..., 0.2]
      }
  }' \
    http://localhost:8080/v1/objects
```

### Querying

`nearVector` and `nearObject` will only query a single vector property at once. The reason for this is to limit complexity. Hybrid search will be extended to handle multiple vectors as an extension of it already handling bm25 and vector queries.

Near vector with no `properties` set. Operates on the root vector as normal.

```graphql
{
    Get {
      Publication(
        nearVector: {
          vector: [0.1, -0.15, 0.3]
        }
      ){
        content
      }
    }
}
```

Near vector with `property` set. Now searches purely on the `titleVec` vector.  Any vector fields can be requested as normal properties. Only the root vector will be returned with `_additional { vector }`.

```graphql
{
    Get {
      Publication(
        nearVector: {
          vector: [0.1, -0.15, 0.3]
          property: "titleVec"
        }
      ){
        name
        _additional {
          certainty  // only supported if distance==cosine
          distance   // always supported
        }
      }
    }
}
```

Corresponding change to near object:

```graphql
{
    Get {
      Publication(
        nearObject: {
          id: "32d5a368-ace8-3bb7-ade7-9f7ff03eddb6"
          property: "titleVec"
        }
      ){
        name
      }
    }
}
```

A special `_vector` field will refer to the root object. This will be the default `property` if none is provided for backwards compatibility.

```graphql
{
    Get {
      Publication(
        nearObject: {
          id: "32d5a368-ace8-3bb7-ade7-9f7ff03eddb6"
          property: "_vector"
        }
      ){
        name
      }
    }
}
```

### Hybrid queries

With no text properties provided, just vector properties, hybrid search will do max pooling (the default) and return the score of the closest vector per object.
Throws an error if len(vector) != length of property vectors or incompatible distance metrics.

```graphql
{
  Get {
    Article (
      hybrid: {
        properties: ["titleVec", "contextVec"]
        vectorPooling: Max
        vector: [1, 2, 3]
      })
     {
      title
      summary
      _additional { score }
    }
  }
}
```

Average pooling could be added as well for completeness however this often performs worse than max pooling https://arxiv.org/abs/2010.06467 so shouldn't be the default.

Mixed case, will do max pooling of `titleVec` and `contextVec` to get best vector distance and then do standard hybrid search combining scores using relative fusion with the query.

```graphql
{
  Get {
    Article (
      hybrid: {
        query: "Fisherman that catches salmon"
        alpha: 0.5
        properties: ["content", "titleVec", "contentVec"]
        vectorPooling: Max
        vector: [1, 2, 3]
      })
     {
      title
      summary
      _additional { score }
    }
  }
}
```

Backwards compatibility. If no `vector` dataType is supplied in `properties` just query the root vector.

```graphql
{
  Get {
    Article (
      hybrid: {
        query: "Fisherman that catches salmon"
        alpha: 0.5
        properties: ["content"]
        vectorPooling: Max
        vector: [1, 2, 3]
      })
     {
      title
      summary
      _additional { score }
    }
  }
}
```

**Comment by sebawita** [comment]
I believe the `vectors` should be separate from `properties`. Like this:
```
{
    "class": "Article",
    "vectors" : {
        "title": [0.3, 0.2, 0.6, ..., 0.1],
        "image": [1,2,3,4],
    },
    "properties": {
        "content": "bar",
    }
}
```

**Comment by trengrj** [comment]
Completed in https://github.com/weaviate/weaviate/pull/4180

**Comment by dandv** [comment]
Great to see named vectors implemented!

> Hybrid search will be extended to handle multiple vectors

Is the implementation of hybrid search among multiple vectors being tracked somewhere?

The use case would be, in the example given above, to apply more weight to the `title` vector than to the `content` vector. Can this be done somehow?

**Comment by trengrj** [comment]
Nice to hear from you @dandv, multiple targets during search is under https://github.com/weaviate/weaviate/issues/5138 with the first set of improvements coming in 1.26.
