### ISSUE TITLE
Frequent creation and deletion of schemas and objects leads to degraded performance

### ISSUE THREAD

**Issue by aduis** [weaviate/weaviate#3536]
I was running a test where every minute a new schema is created, a new object is added, the object is updated, the object is deleted and then the schema is deleted. Over a period of approx. 2 days this leads to increasing response times (> 10sec).

When investigating this issue, the pods was at 100% CPU load. Most CPU was consumed by a component called CycleManager. When restarting the Pod, performance was back to normal. (see screenshot)

Assumption is that there is a bug in cleaning up the processes that have been handling old schemas that meanwhile are deleted. 

![image](https://github.com/weaviate/weaviate/assets/777418/7621f7c2-a31a-4a07-b06a-ac5c412bf184)

**Comment by andersfylling** [comment]
I'm interested in this as well, so I have some questions:
 - Which version are you on? 
 - How many CPU's and amount of memory is assigned?
 - how many vector objects are there? 
 - Also what are their dimensions?

**Comment by etiennedi** [comment]
Hi @andersfylling. Apologies, we missed your comment. However, if you are still interested in this topic, please check out the linked PR and also the linked test pipeline in `weaviate-chaos-engineering`. They should give you some good context on why this occurred and how it was fixed.
