### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by VjDharnish** [weaviate/weaviate#3562]
{"action":"startup","error":"init bolt_db: open \"/var/lib/weaviate/schema.db\": open /var/lib/weaviate/schema.db: permission denied","level":"fatal","msg":"could not initialize schema repo","time":"2023-09-21T07:36:16Z"}

facing this while starting weaviate

**Comment by brenkehoe** [comment]
I had this issue in aks using a managed disk volume mount and i had to set the fsGroup on the security context to resolve it:

`securityContext:
   runAsGroup: 1000
   runAsUser: 1000
   fsGroup: 1000`

**Comment by VjDharnish** [comment]
Thank you for your response . Now its working

**Comment by parkerduckworth** [comment]
Looks like this has been resolved.
