### ISSUE TITLE
Weviate error unmarshaling HTML instead of JSON

### ISSUE THREAD

**Issue by cbelsole** [weaviate/weaviate#3567]
Hey. I am currently using `text2vec-openai` with the config:

```
"moduleConfig": {
  "text2vec-openai": {
    "vectorizeClassName": True,
    "model": "ada",
    "modelVersion": "002",
    "type": "text"
  },
},
```

Occasionally, when I update a vector with Weaviate I get this error.

```json
{
  "error": [
    {
      "message": "update vector: unmarshal response body: invalid character '<' looking for beginning of value"
    }
  ]
}
```

This usually happens when the JSON marshaler encounters HTML text in an error response. Potentially, OpenAI is down and providing us with a 5XX error page instead of a valid JSON response.

**Comment by dudanogueira** [comment]
Hi! Nice catch!

I believe that with the PR #3566 it will be easier to reproduce this.

Thanks for the report!
