### ISSUE TITLE
Unable to correctly configure text2vec-openai module for Azure deployment

### ISSUE THREAD

**Issue by prandell** [weaviate/weaviate#3588]
Existing class configuration allows you to specify
```
"moduleConfig": {
  "text2vec-openai": {
    "resourceName": "<YOUR-RESOURCE-NAME>",
    "deploymentId": "<YOUR-MODEL-NAME>",
  }
}
```

which then sends embedding requests of this format:
```
https://<YOUR-RESOURCE-NAME>.openai.azure.com/openai/deployments/<YOUR-MODEL-NAME>/embeddings?api-version=2022-12-01
```

however, my companies azure deployment needs to look like:

```
https://<YOUR-RESOURCE-NAME>/openai/deployments/<YOUR-MODEL-NAME>/embeddings?api-version=2022-12-01
```
 `openai.azure.com` is not part of the resource name, and I think the assumption that all azure deployments have this extension is not correct.
There is currently no way to configure this in the python client.

**Comment by prandell** [comment]
Is there any update on this? I am currently still unable to use Weaviate with an Azure OpenAI deployment due to this issue

**Comment by brettrp** [comment]
If the Azure config allowed specification of `baseURL`  in the same way as OpenAI that would provide a way of doing this (the `resourceName` would be redundant in that case).
