### ISSUE TITLE
Multi Tenancy and different vectorizers (OpenAI vs Azure OpenAI)

### ISSUE THREAD

**Issue by flipace** [weaviate/weaviate#3605]
We're currently using the multi tenancy feature of weaviate and in our case we can configure different openai api keys for each tenant.

Depending on the tenant, the related openai api key is sent to weaviate for vectorization, which allows properly split billing depending on the tenant.

When using Azure we run into issues though since it only allows to send the API Key but it would also require the deployment and resource name to be modifiable via the request.

Is this already possible but not documented, or would it have to be (and can be) implemented?

(in general it would be fantastic if it were possible to have the option to send either all the openai or azure credentials via the vectorization request)

**Comment by clotodex** [comment]
I have the same issue - also switching between the APIs is a common use case for us. With weaviate this is impossible due to the moduleConfig being tied hard coded to the schema

**Comment by dirkkul** [comment]
this was merged recently
