### ISSUE TITLE
Proposal - consolidate & bundle API-based modules by default

### ISSUE THREAD

**Issue by databyjp** [weaviate/weaviate#3610]
**Challenge:**
All modules currently require to be manually enabled. 
- This adds to the learning curve and decision-making for new users. 
- It also makes a failure mode more likely, where a user tries to use a non-enabled module in their class definition.

**Proposal:**
1. **Consolidate API-based modules together**, so modules like `text2vec-cohere`, `text2vec-openai`, `text2vec-palm`, `generative-cohere` and so on become one module, or fewer modules (e.g. `text2vec-api`, `generative-api`). 
    - This will make it easier to configure Weaviate, and also make it less likely to miss out on a module by accident.
2. **Bundle lightweight modules** with Weaviate so they become opt-out. 
    - This will improve the experience for new users who now need to make fewer decisions to get started.
    - Propose to bundle the same modules as those enabled on WCS. This will also create a uniform "beginner" experience. 

**Discussions:**
Since the days of `text2vec-contextionary` and `text2vec-transformers` which require large NN models, Weaviate includes many API-based lightweight modules.

**Benefits**
The cost of adding API-based modules to a Weaviate instance is relatively low.
This will reduce the amount of decision-making for the user, and result in "safer" defaults at minimal cost to the container size or speed.

Manual additions would be reserved for the larger modules like: `text2vec-contextionary`, `multi2vec-clip` etc.

**Comment by dirkkul** [comment]
implemented by https://github.com/weaviate/weaviate/pull/5002
