### ISSUE TITLE
Run similarity search on embedded

### ISSUE THREAD

**Issue by pplonski** [weaviate/weaviate#3617]
I would like to use Weaviate in AutoGPT hackaton. I would like to use local version (embedded). I successfully installed the client:

```
pip install weaviate-client
```

Then I was following the docs:

```python
import weaviate
from weaviate.embedded import EmbeddedOptions

# started client and stated weaviate
client = weaviate.Client(
  embedded_options=EmbeddedOptions()
)

# add some data
uuid = client.data_object.create({
    'question': 'This vector DB is OSS & supports automatic property type inference on import',
    'answer': 'Weaviate',  # schema properties can be omitted
    'somePropNotInTheSchema': 123,  # will be automatically added as a number property
}, 'JeopardyQuestion')

# similarity search
response = (
    client.query
    .get("JeopardyQuestion", ["question", "answer"])
    .with_near_text({
        "concepts": ["animals in movies"]
    })
    .with_limit(2)
    .with_additional(["distance"])
    .do()
)

print(json.dumps(response, indent=2))
```

I got error for search:
```
{"action":"requests_total","api":"graphql","class_name":"","error":"Unknown argument \"nearText\" on field \"JeopardyQuestion\" of type \"GetObjectsObj\". Did you mean \"nearObject\" or \"nearVector\"?","level":"error","msg":"unexpected error","query_type":"","time":"2023-10-09T14:41:58+02:00"}
```

For sure, I missed some configuration, ... could you please help? Thank you!

**Comment by tsmith023** [comment]
Hi @pplonski, the problem here is that you have not specified a vectoriser to use with your Weaviate instance so when you perform the `near_text` search, Weavite doesn't know how to convert your `concepts` list into a suitable vector to use when performing similarity search.

Your best course of action is to post this question on the [community forum](https://forum.weaviate.io) and someone will get back to you in more depth!

**Comment by pplonski** [comment]
Thank you! I got this notebook https://github.com/weaviate/recipes/blob/main/similarity-search/text2vec/similarity_search_openai.ipynb from @erika-cardenas and it works very good!

**Comment by erika-cardenas** [comment]
Awesome, glad it helped @pplonski! 🙂
