### ISSUE TITLE
Incorrect GraphQL Query Results for 'Equal' Operator

### ISSUE THREAD

**Issue by andreilarin** [weaviate/weaviate#3623]
I have the schema with these properties
```js
{
  "class": "Document",
  "properties": [
    {
      "dataType": [
        "text"
      ],
      "name": "communityId",
      "moduleConfig": {
        "text2vec-openai": {
          "skip": true,
          "vectorizePropertyName": false
        }
      }
    },
    {
      "dataType": [
        "text"
      ],
      "name": "documentId",
      "moduleConfig": {
        "text2vec-openai": {
          "skip": true,
          "vectorizePropertyName": false
        }
      }
    }
  ]
}
```
And I execute this query and get the following result:
![image](https://github.com/weaviate/weaviate/assets/61755737/ee82b3c3-625a-4ff4-a021-3517777e6630)

The expected result would be to retrieve documents with "communityId" equal to "1-1". However, the response contains documents with various "communityId" values, including "1-12" and "2-1", which do not match the specified filter condition.

**Comment by trengrj** [comment]
@andreilarin the string `"1-12"` is being tokenized into `["1", "12"]` with the default `word` tokenization see https://weaviate.io/developers/weaviate/config-refs/schema#property-tokenization.

Fix would be to change the tokenization to `field` for any string id fields you have such as `communityId`.
