### ISSUE TITLE
Where is the cohere api key env var checked?

### ISSUE THREAD

**Issue by tillwenke** [weaviate/weaviate#3632]
https://github.com/weaviate/weaviate/blob/766c98c47de3bcf52173efd92b5187971917f6ea/modules/generative-cohere/clients/cohere.go#L178C38-L178C51

**Comment by trengrj** [comment]
👋  @tillwenke that would be here for the generative module

https://github.com/weaviate/weaviate/blob/766c98c47de3bcf52173efd92b5187971917f6ea/modules/generative-cohere/module.go#L65-L77
