### ISSUE TITLE
Availability of GPT4All's GPT-3.5-derived Dataset for Research

### ISSUE THREAD

**Issue by WordDealer** [weaviate/weaviate#3637]
GPT4All has created a dataset obtained from GPT-3.5, and I would like to know whether this dataset is publicly available for research. I haven't been able to find it in the project. If the dataset is accessible, could you please provide me with a link? Thank you.

**Comment by trengrj** [comment]
@WordDealer this would be best asked on https://github.com/nomic-ai/gpt4all
