### ISSUE TITLE
[PQ] Pick optimal segment parameters

### ISSUE THREAD

**Issue by trengrj** [weaviate/weaviate#3667]
Currently when enabled PQ will set the default number of segments to be the number of dimensions of the vectors. This is always guaranteed to work (as the # of segments must divide the # of dimensions), however it results in less memory savings for acceptable recall.

We should pick better defaults in an easier understandable way. Potentially something like this:

```
if dimensions >= 768 and dimensions % 6 == 0
  segments = dimensions / 6
else if dimensions >= 512 and dimensions % 4 == 0
  segments = dimensions / 4
else if dimensions >= 64 and dimensions % 2 == 0
  segments = dimensions / 2
else
  segments = dimensions
```

Abdel's experimental results showed `dimensions / 6` is best for Sphere/Ada embeddings (768, 1536) hence the first value. @abdelr @etiennedi  do you have any comments on good defaults for the other dimension sizes? We should validate if a 1M MiniLM 384 dim dataset performs well with these defaults.

**Comment by CShorten** [comment]
Maybe something to add here? - https://github.com/weaviate/weaviate/blob/stable/v1.22/adapters/repos/db/vector/hnsw/compress.go#L58

**Comment by etiennedi** [comment]
Put the `planned-1.23` label on this, but ideally we can just release that sooner as a patch already.
