### ISSUE TITLE
how can i use anthropic's claude? 

### ISSUE THREAD

**Issue by legaltextai** [weaviate/weaviate#3689]
how can i use anthropic's claude?  i 'd like to use it for generative part. 
thanks

**Comment by dudanogueira** [comment]
Following this [forum thread](https://forum.weaviate.io/t/can-i-use-claude-anthropic-for-the-generative-part/873), the idea is to keep this issue as a central point for this.

**API DOC**: https://docs.anthropic.com/claude/docs

I was not able to get access (not available in my region). So I submitted [a form to manifest my interest](https://www.anthropic.com/product).

**Comment by legaltextai** [comment]
thanks. i meant how to change the settings within weaviate from openai to anthropic

**Comment by hwang251** [comment]
I would be interested in anthropic's claude as a weaviate module too

**Comment by mikhailshilkov** [comment]
Claude 3 is a SOTA model right now, I'd love to have it available as an option

**Comment by dirkkul** [comment]
looks like this was added: https://weaviate.io/developers/weaviate/model-providers/anthropic#integrations-with-anthropic
