### ISSUE TITLE
Palm modules - Make apiEndpoint configurable

### ISSUE THREAD

**Issue by byronvoorbach** [weaviate/weaviate#3706]
Context:

We currently have a static endpoint for the text2vec & generative PaLM modules, as there was no support for different endpoints before. We should make this configurable for users to modify. 

https://developers.generativeai.google/guide/palm_api_overview#generate_embeddings

Also, these endpoints now use a KEY parameter as input for authentication.

**Comment by dirkkul** [comment]
I see an endpoint in the api for:
generative-google
text2vec-google

there is a "location" for multi2vec, which I assume is something similar?

Will close this issue, could you reopen it in case something is missing?
