### ISSUE TITLE
Exception in example code in documentation for Error Handling in Batch requests

### ISSUE THREAD

**Issue by marklysze** [weaviate/weaviate#3818]
### How to reproduce this bug?

(Note: I'm encountering this issue using the python client, so I wasn't sure if this repository or the python client one was preferred - however as it is documentation related I've put it here. Let me know if I should move it.)

I want to ensure that I can detect if a batch delete has been successful - so checking the documentation...

Under the **Error handling** section on the **References: API > RESTful API > REST - /v1/batch** page, the code in the `check_batch_result` has the following:

```
  if results is not None:
    for result in results:
      if 'result' in result and 'errors' in result['result']:
        if 'error' in result['result']['errors']:
          print(result['result']['errors']['error'])
```

This code was causing an exception on the third line where it was looking for 'errors' in result['result'].

I believe there's an `objects` element under the `results` element and that each of those object elements has an `error` element.

As I'm not sure how to cause an error in order to test for it I've updated the code, which runs, but I haven't been able to cause an error to test it.

```
  if results is not None:
    for result in results:
      if result == 'results':
        if results["results"]["objects"] is not None:
            for object in results["results"]["objects"]:
                if "error" in object and object["error"] is not None:
                    print(object['error'])
```

### What is the expected behavior?

Any error messages are printed.

### What is the actual behavior?

An exception occurs on the third line.

### Server Version

1.21.2

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by dudanogueira** [comment]
Hi! I have used this very example and added a way to force the error by adding a second object with different vector dimensions ;)

the example code worked as expected:

```
import weaviate

client = weaviate.Client("http://localhost:8080")

client.schema.delete_class("Author")

def check_batch_result(results: dict):
  """
  Check batch results for errors.

  Parameters
  ----------
  results : dict
      The Weaviate batch creation return value, i.e. returned value of the client.batch.create_objects().
  """
  if results is not None:
    for result in results:
        if 'result' in result and 'errors' in result['result']:
            if 'error' in result['result']['errors']:
                print("ERROR HERE!", result['result']['errors']['error'])

object_to_add = {
    "name": "Jane Doe",
    "writesFor": [{
        "beacon": "weaviate://localhost/f81bfe5e-16ba-4615-a516-46c2ae2e5a80"
    }]
}

with client.batch(batch_size=100, callback=check_batch_result) as batch:
  batch.add_data_object(object_to_add, "Author", "36ddd591-2dee-4e7e-a3cc-eb86d30a4303", vector=[1,2])
  batch.add_data_object(object_to_add, "Author", "36ddd591-2dee-4e7e-a3cc-eb86d30a4304", vector=[1,2, 3])
```
