### ISSUE TITLE
Bug: Multi-tenancy: Able to load data object successfully without providing tenant details on weaviate Pythonv4 client

### ISSUE THREAD

**Issue by rthiiyer82** [weaviate/weaviate#3826]
### How to reproduce this bug?

**Test environment:**
1. Weavaite v1.22.5
2. Weaviate python v4

**Pre-Condition:** 
1. You have successfully established weaviate connection on a cluster hosted on WCS console.

**Steps to reproduce the issue:**
1. Create a class/collection with multi-tenancy config enabled but without tenant information
``` # Create collection with properties and multi-tenancy config enabled
   movie_recommendation = client.collections.create(
   name="movie_recommendation_grpc",
     properties=[
        wvc.Property(name="title", data_type=wvc.DataType.TEXT),
        wvc.Property(name="genres", data_type=wvc.DataType.TEXT),
        wvc.Property(name="keywords", data_type=wvc.DataType.TEXT),
        wvc.Property(name="popularity", data_type=wvc.DataType.TEXT),
        wvc.Property(name="runtime", data_type=wvc.DataType.TEXT),
        wvc.Property(name="cast", data_type=wvc.DataType.TEXT),
        wvc.Property(name="language", data_type=wvc.DataType.TEXT),
         wvc.Property(name="tagline", data_type=wvc.DataType.TEXT),
          wvc.Property(name="revenue", data_type=wvc.DataType.TEXT),
           wvc.Property(name="director", data_type=wvc.DataType.TEXT),
     ],
     multi_tenancy_config=wvc.Configure.multi_tenancy(True)
)
```
3. Load the data objects. See actual result 1
4. Perform a simple search query . See actual result 2
```
clientDetails = client.collections.get(className)
  response= clientDetails.query.fetch_objects(limit=1, return_properties=["title", "keywords", "cast"])
    for o in response.objects:
     print(json.dumps(o.properties, indent=2))

```

### What is the expected behavior?

User should not be able to load data. An error message (as seen in weaviate pythonv3 `{'error': [{'message': 'class Movie_recommendation_grpc has multi-tenancy enabled, but request was without tenant'}]}` should have been displayed to the user at the time of loading itself.

### What is the actual behavior?

1. Data is loaded successfully.
2. `WeaviateQueryException: Query call failed with message explorer: list class: search: object search at index movie_recommendation_grpc: class Movie_recommendation_grpc has multi-tenancy enabled, but request was without tenant.` error message is displayed.

### Server Version

1.22.5

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by dirkkul** [comment]
This was resolved internally
