### ISSUE TITLE
Using aws vectorizer when crating a class throws an error

### ISSUE THREAD

**Issue by dari-o** [weaviate/weaviate#3863]
### How to reproduce this bug?

Follow the documentation provided [here](https://weaviate.io/developers/weaviate/modules/retriever-vectorizer-modules/text2vec-aws#class-configuration) to set the vectorizer for a class. This is my class configuration:
```
class_obj = {
            "class": "Article",
            "description": "A class called document",
            "vectorizer": "text2vec-cohere",
            "vectorIndexConfig": {"distance": "cosine"},
            "moduleConfig": {
                "text2vec-aws": {
                    "model": "amazon.titan-embed-text-v1",
                    "region": "eu-central-1",
                }
            },
        }
client.schema.create_class(class_obj)
```

### What is the expected behavior?

Be able to create a class as described in the documentation. When I try with another vectorizer, e.g. `text2vec-cohere` I don't get the same error. I have also set the env variable `ENABLE_MODULES` 

### What is the actual behavior?

And I get the following error:
```
weaviate.exceptions.UnexpectedStatusCodeException: Create class! Unexpected status code: 422, with response body: {'error': [{'message': 'vectorizer: no module with name "text2vec-aws" present'}]}.
```

### Supporting information

Env variables:
```
ENABLE_MODULES=text2vec-aws
DEFAULT_VECTORIZER_MODULE=text2vec-aws
```

### Server Version

3.25.3

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by dudanogueira** [comment]
Hi!

This means that the text2vec-aws is not enabled in this server. Maybe are you using a server version older then [1.22.5, when text2vec-aws was instroduced](https://github.com/weaviate/weaviate/releases/tag/v1.22.5)?

What Server version are you running? You can get you server version with 
```
client.get_meta()["version]
```

thanks!

**Comment by dari-o** [comment]
> Hi!
> 
> This means that the text2vec-aws is not enabled in this server. Maybe are you using a server version older then [1.22.5, when text2vec-aws was instroduced](https://github.com/weaviate/weaviate/releases/tag/v1.22.5)?
> 
> What Server version are you running? You can get you server version with
> 
> ```
> client.get_meta()["version]
> ```
> 
> thanks!

Hi @dudanogueira, 
I am actually using the `1.22.5` version.

**Comment by dirkkul** [comment]
Hi, you need to enable it in your weaviate instace, see for example here: https://weaviate.io/developers/weaviate/configuration/modules#enable-individual-modules

if anything is unclear please make a post in our forum: https://forum.weaviate.io/
