### ISSUE TITLE
Support moveTo and moveAwayFrom with hybrid search

### ISSUE THREAD

**Issue by BradAtGames** [weaviate/weaviate#3872]
### Describe your feature request

We would like to be able to apply moveTo and moveAwayFrom parameters to the nearMedia portion of a hybrid query.

The use case here is a user having signaled "more like this result" or "fewer like this result" wherein we would like to run the original query again, with the addition of moveTo/moveAwayFrom as appropriate.

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by dirkkul** [comment]
this has been added
