### ISSUE TITLE
nestedProperties None don't work but regular properties work

### ISSUE THREAD

**Issue by Techie5879** [weaviate/weaviate#3885]
### How to reproduce this bug?

Suppose in the schema, if I have:
```
{
            "name": "summary",
            "description": "Summary of the professional",
            "dataType": ["text"],
        },
```

and while importing objects, one has "summary" as None, that works fine and there don't seem to be errors.
However, if in the schema I have 

```

{
    "name": "platformMetrics",  
    "description": "Metrics related to the professional's activity on a development platform",
    "dataType": ["object"],
    "nestedProperties": [
        {"dataType": ["number"], "name": "p1"},  
        {"dataType": ["number"], "name": "p2"},  
        {
            "dataType": ["object"], "name": "annualContributions",  
            "nestedProperties": [
                {"dataType": ["number"], "name": "commitTotal"},  
                {"dataType": ["number"], "name": "issueTotal"},           
        ]
        },
        {"dataType": ["text"], "name": "complexProject"},  
        {"dataType": ["text"], "name": "primaryLanguages"},
    ],
    "indexSearchable": False,
    "moduleConfig": {"text2vec-openai": {"skip": True}},
}
```

and, for example, 'primaryLanguages' is None while batch importing, it gives an invalid object property error: expected type string but got type `<nil>`

Can a fix be implemented?

### What is the expected behavior?

Would import objects and set those fields to None like it does with non-nested properties

### What is the actual behavior?

errors out, expected property of type string but got `<nil>`

### Server Version

1.22.6

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by exsbandit** [comment]
hello @Techie5879 did you solve your problem ?? I have similar problem like you 

When I perform a query search in the Weaviate console as shown below, I receive the following data as a result. I want to create a GraphQL search using the 'name' and 'quantity' from the 'ingredients' key, and also use the 'color' value from the 'properties' key. How can I achieve this?

`
{
  Get {
    Adata (limit:2) {
      code
      description
      name
      ingredients {
        code
        name
        quantity
        unit
      }
      properties {
        color
        region
        viscosity
      }
    }
  }
}
`
Result:
`
{
  "data": {
    "Get": {
      "Adata": [
        {
          "code": "prd002",
          "description": "Savory Caesar Salad",
          "ingredients": [
            {
              "code": "xxx",
              "name": "Romaine lettuce",
              "quantity": "100",
              "unit": "gr"
            },
            {
              "code": "xxx",
              "name": "Grilled chicken",
              "quantity": "100",
              "unit": "gr"
            },
            {
              "code": "xxx",
              "name": "Parmesan cheese",
              "quantity": "50",
              "unit": "gr"
            },
            {
              "code": "xxx",
              "name": "Croutons",
              "quantity": "30",
              "unit": "gr"
            },
            {
              "code": "xxx",
              "name": "Caesar dressing",
              "quantity": "20",
              "unit": "gr"
            }
          ],
          "name": "Savory Caesar Salad",
          "properties": [
            {
              "color": "#a02",
              "region": "#c02",
              "viscosity": "#b02"
            }
          ]
        },
        {
          "code": "prd001",
          "description": "Sweet Strawberry Spinach Salad",
          "ingredients": [
            {
              "code": "xxx",
              "name": "Baby spinach",
              "quantity": "100",
              "unit": "gr"
            },
            {
              "code": "xxx",
              "name": "Strawberries",
              "quantity": "100",
              "unit": "gr"
            },
            {
              "code": "xxx",
              "name": "Goat cheese",
              "quantity": "50",
              "unit": "gr"
            },
            {
              "code": "xxx",
              "name": "Candied pecans",
              "quantity": "30",
              "unit": "gr"
            },
            {
              "code": "xxx",
              "name": "Balsamic glaze",
              "quantity": "20",
              "unit": "gr"
            }
          ],
          "name": "Sweet Strawberry Spinach Salad",
          "properties": [
            {
              "color": "#a01",
              "region": "#c01",
              "viscosity": "#b01"
            }
          ]
        }
      ]
    }
  }
}

`

### Server Setup Information

- Weaviate Server Version: 
semitechnologies/weaviate:1.23.10

My Schema
`
{
  "classes": [
    {
      "class": "Adata",
      "description": "Information from data",
      "vectorizer": "text2vec-openai",
      "moduleConfig": {
        "text2vec-openai": {
          "model": "ada",
          "type": "text"
        }
      },
      "properties": [
        {
          "dataType": [
            "text"
          ],
          "description": "Product name",
          "moduleConfig": {
            "text2vec-openai": {
              "skip": "false",
              "vectorizePropertyName": "false"
            }
          },
          "name": "name"
        },
        {
            "dataType": ["object"],
            "name": "ingredients",
            "nestedProperties": [
                {"dataType": ["text"], "name": "code"},
                {"dataType": ["text"], "name": "name"},
                {"dataType": ["number"], "name": "quantity"},
                {"dataType": ["text"], "name": "unit"}
            ],
            "description": "The ingredients",
            "moduleConfig": {
                "text2vec-openai": {
                  "skip": "false",
                  "vectorizePropertyName": "false"
                }
            }
        },
        {
            "dataType": ["object"],
            "name": "properties",
            "nestedProperties": [
                {"dataType": ["text"], "name": "color"},
                {"dataType": ["text"], "name": "viscosity"},
                {"dataType": ["text"], "name": "region"}
            ],
            "description": "The properties",
            "moduleConfig": {
                "text2vec-openai": {
                  "skip": "false",
                  "vectorizePropertyName": "false"
                }
            }
        },
        {
          "dataType": [
            "text"
          ],
          "description": "The code",
          "moduleConfig": {
            "text2vec-openai": {
              "skip": "false",
              "vectorizePropertyName": "false"
            }
          },
          "name": "code"
        }
      ]
    }
  ]
}
`

**Comment by danielbichuetti** [comment]
Yes, this is an issue when using OBJECT and OBJECT_ARRAY. If you set a nested property of a type and a null value is about to be inserted it returns a type error.

` {21: ErrorObject(message="invalid object[] property 'metadata__movements' on class 'Documents': invalid object '87' in array: property 'metadata__movements.code': invalid text property 'metadata__movements.code' on class 'Documents': not a string, but <nil>"`

@dudanogueira Any update about this bug?

**Comment by dirkkul** [comment]
This should be fixed in the next version
