### ISSUE TITLE
Improved integration in Langchain JS and Flowise

### ISSUE THREAD

**Issue by kristian-enblom** [weaviate/weaviate#3886]
### Describe your feature request

Hi!

I’d like to request some updates to the Weaviate integration in Langchain JS and Flowise. The current Langchain JS [integration](https://github.com/langchain-ai/langchainjs/blob/main/libs/langchain-community/src/vectorstores/weaviate.ts) doesn’t allow setting some parameters in search queries, like setting offsets. Also there’s only one type of similarity search integrated, but it would be great to add the option to use the reranker module, bm25 etc. I’m sure there are other great features that could also need adding but these are the ones I can think of. 

Same thing goes for the Weaviate [integration](https://github.com/FlowiseAI/Flowise/tree/main/packages/components/nodes/vectorstores/Weaviate) in Flowise, which is using Langchain JS. 

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by trengrj** [comment]
Hi @kristian-enblom, as those integrations are external libraries please feel free to contribute to them. For getting started you could join #contributors in the [weaviate slack](https://weaviate.io/slack) instance.
