### ISSUE TITLE
BM25 search does not return results even after upgrading version

### ISSUE THREAD

**Issue by simon-chen-1** [weaviate/weaviate#3890]
### How to reproduce this bug?

- My team and I are using Weaviate server version 1.22.6 and the Weaviate typescript client v1.5.0
- We are trying to query for a list of Articles by the `name` property using the BM25 search:

```
await wClient.graphql
   .get()
   .withClassName('Article')
   .withBm25({
      query: 'Archive',
      properties: ['name']
    })
   .withLimit(count)
   .withOffset(offset)
   .withFields('content name _additional { id, score, certainty }')
   .do();
```

- This query currently does not return any results.
- We have also tried using the Hybrid search with an `alpha` of 0. This does not return any results. However, using an `alpha` with a value of 0.1 returns results. 

### What is the expected behavior?

We expected to be able to query for a list of articles using the BM25 search on the `name` property. We verified that there are many articles containing the text "Archive" in their names, yet no articles are being returned in the results.

### What is the actual behavior?

No articles are being returned in the results when we try to search for the text "Archive" in the `name` property. Removing the `properties` key in the BM25 search to search across all properties also returns no results. Using a Hybrid search with an `alpha` value of 0 also returns no results but using an `alpha` value of 0.1 returns results.

### Supporting information

We are aware of a bug affecting the BM25 search across versions 1.21.0 - 1.21.4 with a fix having been released in 1.21.5 (https://github.com/weaviate/weaviate/pull/3592) which affects the compaction process of the data, resulting in corrupted data. However, we were on version 1.19.0 when our data was ingested so our data should theoretically not have been affected. We are currently on version 1.22.6 and our query is still returning no results.

Here is our schema for Articles:
```
class Article {
  class: string;
  id: string;
  score: number;
  certainty: number;
  creationTimeUnix: number;
  lastUpdateTimeUnix: number;
  properties: {
    content: string;
    name: string;
    page: number;
  }
}
```

If the Weaviate team strongly believes it is not the same bug affecting our search results, would the solution be to re-index our data? Ideally, my team and I would prefer not to do this as we'd have to re-index a significant amount of data for our customers

### Server Version

1.22.6

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by Mikesaosao** [comment]
Has the problem been resolved?

**Comment by dirkkul** [comment]
Hi, sorry haven't seen this one before - I have not heard any reports about this, so I'd assume that it is a local corruption

> If the Weaviate team strongly believes it is not the same bug affecting our search results, would the solution be to re-index our data? Ideally, my team and I would prefer not to do this as we'd have to re-index a significant amount of data for our customers

yes, I'd assume so.


Closing this, if you are still facing this please reopen
