### ISSUE TITLE
Idempotent Batch (Noop, Prop-only change, Upsert)

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#3949]
## Description

In a batch, we should always take the minimally invasive option:

* If an object exists exactly as specified, do nothing
* If an object exists with the same vector but different properties, do a [properties-only update](https://github.com/weaviate/weaviate/issues/3948)
* If an object exists with a different vector, do a regular update
* If an object does not exist at all, do a regular insert

## Existing API vs new API

The logic outlined above will likely require reading and analyzing objects before inserts. This can slow down inserts if all objects are new and all inserts are pure inserts. We need to make sure that we do not make initial loading any slower. Therefore I would suggest that we either:

* Verify that the new process does not (significantly) slow down inserts
* Make the feature opt-in, either through a flag on an existing API or by adding a completely new API (e.g. "batch upsert")

## Open Questions:

* What should we consider the previous object in a replication scenario? 
   * My suggestion would be to use the same consistency level that is specified for writing. However, that also means that for every insert, multiple nodes first have to agree on the current view of an object which could be a considerable performance bottleneck
   * An alternative would be to use a separate consistency level for reading that defaults to `ONE`. This way the read portion could always be done by the local node

## Acceptance Criteria

1. The following behavior is observed:
    * If an object exists exactly as specified, do nothing (Noop)
    * If an object exists with the same vector but different properties, do a [properties-only update](https://github.com/weaviate/weaviate/issues/3948)
    * If an object exists with a different vector, do a regular update
    * If an object does not exist at all, do a regular insert
2. The feature works correctly with replication enabled
3. An initial load (without any duplicates/updates) is not any slower than before, especially on a setup with replication enabled.

**Comment by VishalMCF** [comment]
Hello, @etiennedi is this a beginner-friendly issue?

**Comment by trengrj** [comment]
Completed in https://github.com/weaviate/weaviate/pull/4058
