### ISSUE TITLE
[Modules] Don't revectorize identical/similar objects in a batch

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#3950]
## Description

Building on the logic specified in #3949, an idempotent batch should skip vectorization in modules if one of the following conditions is met:

* The object already exists AND
    * all properties are identical OR
    * only properties were changed that are excluded in vectorization
    
The vectorization should always happen if

* The object does not already exist OR
* The object exists, but a vectorization-relevant property was changed from its previous value

## Acceptance Criteria

1. Vectorization is skipped according to the rules outlined above
2. If no vectorizer is used or the user specifies custom vectors, the existing logic is not changed; i.e. no additional checks are introduced that could slow down imports

**Comment by trengrj** [comment]
Completed in https://github.com/weaviate/weaviate/pull/4163
