### ISSUE TITLE
grpc does not return cross-references when making a query with the `group_by` option

### ISSUE THREAD

**Issue by SavvasMohito** [weaviate/weaviate#4032]
### How to reproduce this bug?

Create two collections and set one to cross-reference the other. Use python v4 client (which makes use of grpc) and run the following

```python
result = collection.query.near_text(
    query="some text",
    return_references=[QueryReference(link_on="cross_reference_name")],
    group_by=GroupBy(prop="some_colA_object_prop", objects_per_group=10, number_of_groups=10),
)
``` 

Running the same query without the group_by setting, does return the requested cross-references properly
```python
result = collection.query.near_text(
    query="some text",
    return_references=[QueryReference(link_on="cross_reference_name")],
)
``` 

### What is the expected behavior?

The returned objects should include the requested cross-references in `object.references`

### What is the actual behavior?

All of the returned objects have an empty `object.references` value. This is the case for all objects in both `result.objects` and `result.groups[{group_name}].objects` 

### Supporting information

I am using the latest beta python client v4.4b7. I have double-checked that my schemas and query options are set-up correctly. The issue only occurs when I set the `group_by` option. There are no errors shown in the container's logs.

I see [here](https://github.com/weaviate/weaviate/blob/3d1db0e3a938b63b422c41028ac8e6d8d9063465/adapters/handlers/grpc/v1/prepare_reply.go#L35-L63) that there are different procedures followed when there is a GroupBy option or not. Maybe this can help find the root of the problem.

### Server Version

1.23.3

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by SavvasMohito** [comment]
@tsmith023 Apologies for mentioning you directly, but could you please have a look at this one? Thanks in advance

**Comment by dirkkul** [comment]
should be fixed with the next release
