### ISSUE TITLE
Support new text embedding models

### ISSUE THREAD

**Issue by mauserzjeh** [weaviate/weaviate#4084]
### Describe your feature request

Currently the new text embedding models are not supported.

Error message: `wrong OpenAI model name, available model names are: [ada babbage curie davinci]`

Add support for new embedding models:
- `text-embedding-3-small`
- `text-embedding-3-large`

Official documentation: 
- https://platform.openai.com/docs/models/embeddings
- https://platform.openai.com/docs/guides/embeddings

Blogpost:
https://openai.com/blog/new-embedding-models-and-api-updates

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by iSuslov** [comment]
@mauserzjeh You can set `model` parameter in schema model config to any of those new models. See https://weaviate.io/developers/weaviate/modules/retriever-vectorizer-modules/text2vec-openai#api-settings-openai

**Comment by Techie5879** [comment]
Agreed, support for this ASAP will help us test these models with weaviate!

**Comment by etiennedi** [comment]
Does the [latest version](https://github.com/weaviate/weaviate/releases/tag/v1.23.6) fix your issues? It should support the new models.

**Comment by mauserzjeh** [comment]
> Does the [latest version](https://github.com/weaviate/weaviate/releases/tag/v1.23.6) fix your issues? It should support the new models.

Haven't try it yet, but reading the release it should be ok. I will close the issue once I tested it out

**Comment by jasoncsullivan** [comment]
> Does the [latest version](https://github.com/weaviate/weaviate/releases/tag/v1.23.6) fix your issues? It should support the new models.

@etiennedi  it should, but it looks like this is not available yet on the cloud dashboard (I'm only able to upgrade up to v1.23.4). When will 1.23.6 be generally available for users of the cloud product?
