### ISSUE TITLE
AttributeError: 'GetBuilder' object has no attribute 'with_after'

### ISSUE THREAD

**Issue by shubhamgajbhiye1994** [weaviate/weaviate#4094]
### How to reproduce this bug?

AttributeError                            Traceback (most recent call last)
<ipython-input-13-e67c56924299> in <module>
----> 1 client.query.get("Candidate",["fcu"]).with_after('000001bd-426e-51bd-9d41-29651e1f7e53').with_limit(5).do()

AttributeError: 'GetBuilder' object has no attribute 'with_after'

### What is the expected behavior?

it should show some output

### What is the actual behavior?

it should be iterative

### Supporting information

AttributeError                            Traceback (most recent call last)
<ipython-input-13-e67c56924299> in <module>
----> 1 client.query.get("Candidate",["fcu"]).with_after('000001bd-426e-51bd-9d41-29651e1f7e53').with_limit(5).do()

AttributeError: 'GetBuilder' object has no attribute 'with_after'

### Server Version

latest or 1.22.3

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by VishalMCF** [comment]
@shubhamgajbhiye1994 R u going to submit a PR?

**Comment by dirkkul** [comment]
a bit late, but this would a topic for our support forum: forum.weaviate.io
