### ISSUE TITLE
v1.23.6 new OpenAI models dont allow schema to be created

### ISSUE THREAD

**Issue by adambeer** [weaviate/weaviate#4098]
### How to reproduce this bug?

Creating a new schema though the REST endpoint with the following module config setup:
```
"moduleConfig": {
        "text2vec-openai": {
            "vectorizeClassName": false,
            "model": "text-embedding-3-large",
            "dimensions": 3072
        }
 }
```

### What is the expected behavior?

Response to return a 200 with the newly created schema

### What is the actual behavior?

A 200 response but no schema created and the following error in the logs:

`{"error":"interface conversion: interface {} is nil, not map[string]interface {}","level":"error","method":"POST","msg":"interface conversion: interface {} is nil, not map[string]interface {}","path":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/v1/schema","RawPath":"","OmitHost":false,"ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""},"time":"2024-01-29T16:54:53Z"}
{"action":"requests_total","api":"rest","class_name":"","error":"interface conversion: interface {} is nil, not map[string]interface {}","level":"error","msg":"unexpected error","query_type":"","time":"2024-01-29T16:54:53Z"}
goroutine 1208 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x13
github.com/weaviate/weaviate/adapters/handlers/rest.handlePanics({0x1dbc890, 0xc003756380}, {0x1da5f40, 0xc0035bbfb0}, 0xc00012a500)
        /go/src/github.com/weaviate/weaviate/adapters/handlers/rest/panics_middleware.go:80 +0x2d2
panic({0x1702ae0?, 0xc00322bc80?})
        /usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/weaviate/weaviate/usecases/modules.(*Provider).setSinglePropertyConfigDefaults(0x16d13a0?, 0xc0028343c0, 0xc003376480, {0x7faa9685aa18, 0xc00379e8c0})
        /go/src/github.com/weaviate/weaviate/usecases/modules/module_config_init_and_validate.go:102 +0x62d
github.com/weaviate/weaviate/usecases/modules.(*Provider).setPerPropertyConfigDefaults(...)
        /go/src/github.com/weaviate/weaviate/usecases/modules/module_config_init_and_validate.go:89
github.com/weaviate/weaviate/usecases/modules.(*Provider).SetClassDefaults(0xc0037fd140, 0xc0028343c0)
        /go/src/github.com/weaviate/weaviate/usecases/modules/module_config_init_and_validate.go:41 +0x17b
github.com/weaviate/weaviate/usecases/schema.(*Manager).setClassDefaults(0xc0036e4000, 0xc0028343c0)
        /go/src/github.com/weaviate/weaviate/usecases/schema/add.go:250 +0x39f
github.com/weaviate/weaviate/usecases/schema.(*Manager).addClass(0xc0036e4000, {0x1da68e0, 0xc00322b080}, 0xc0028343c0)
        /go/src/github.com/weaviate/weaviate/usecases/schema/add.go:144 +0x311
github.com/weaviate/weaviate/usecases/schema.(*Manager).AddClass(0xc0036e4000, {0x1da68e0, 0xc00322b080}, 0x101f983?, 0xc002fae390?)
        /go/src/github.com/weaviate/weaviate/usecases/schema/add.go:49 +0x71
github.com/weaviate/weaviate/adapters/handlers/rest.(*schemaHandlers).addClass(0xc0036ee300, {0xc00012a700?, 0xc0028343c0?}, 0x0?)
        /go/src/github.com/weaviate/weaviate/adapters/handlers/rest/handlers_schema.go:34 +0x6e
github.com/weaviate/weaviate/adapters/handlers/rest/operations/schema.SchemaObjectsCreateHandlerFunc.Handle(0xc00014ceb8?, {0xc00012a700?, 0xc0028343c0?}, 0x1d955c0?)
        /go/src/github.com/weaviate/weaviate/adapters/handlers/rest/operations/schema/schema_objects_create.go:32 +0x29
github.com/weaviate/weaviate/adapters/handlers/rest/operations/schema.(*SchemaObjectsCreate).ServeHTTP(0xc0036ee960, {0x1da1570, 0xc003369960}, 0xc00012a700)
        /go/src/github.com/weaviate/weaviate/adapters/handlers/rest/operations/schema/schema_objects_create.go:79 +0x282
github.com/go-openapi/runtime/middleware.(*Context).RoutesHandler.NewOperationExecutor.func1({0x1da1570, 0xc003369960}, 0xc00012a700)
        /go/pkg/mod/github.com/go-openapi/runtime@v0.24.2/middleware/operation.go:28 +0x53
net/http.HandlerFunc.ServeHTTP(0xc003376240?, {0x1da1570?, 0xc003369960?}, 0xc00012a600?)
        /usr/local/go/src/net/http/server.go:2136 +0x29
github.com/weaviate/weaviate/adapters/handlers/rest.configureAPI.makeSetupMiddlewares.func6.1({0x1da1570, 0xc003369960}, 0xc00012a700)
        /go/src/github.com/weaviate/weaviate/adapters/handlers/rest/middlewares.go:43 +0xdf
net/http.HandlerFunc.ServeHTTP(0x41a608?, {0x1da1570?, 0xc003369960?}, 0xc00014d000?)
        /usr/local/go/src/net/http/server.go:2136 +0x29
github.com/go-openapi/runtime/middleware.NewRouter.func1({0x1da1570, 0xc003369960}, 0xc00012a500)
        /go/pkg/mod/github.com/go-openapi/runtime@v0.24.2/middleware/router.go:78 +0x257
net/http.HandlerFunc.ServeHTTP(0x10?, {0x1da1570?, 0xc003369960?}, 0x7faa96b5bf60?)
        /usr/local/go/src/net/http/server.go:2136 +0x29
github.com/go-openapi/runtime/middleware.Redoc.func1({0x1da1570, 0xc003369960}, 0x1508856?)
        /go/pkg/mod/github.com/go-openapi/runtime@v0.24.2/middleware/redoc.go:72 +0x22e
net/http.HandlerFunc.ServeHTTP(0x1989eb8?, {0x1da1570?, 0xc003369960?}, 0x4125c5?)
        /usr/local/go/src/net/http/server.go:2136 +0x29
github.com/go-openapi/runtime/middleware.Spec.func1({0x1da1570, 0xc003369960}, 0xc002fae340?)
        /go/pkg/mod/github.com/go-openapi/runtime@v0.24.2/middleware/spec.go:46 +0x182
net/http.HandlerFunc.ServeHTTP(0xc0000b5a40?, {0x1da1570?, 0xc003369960?}, 0xc00012a500?)
        /usr/local/go/src/net/http/server.go:2136 +0x29
github.com/rs/cors.(*Cors).Handler-fm.(*Cors).Handler.func1({0x1da1570, 0xc003369960}, 0xc00012a500)
        /go/pkg/mod/github.com/rs/cors@v1.5.0/cors.go:200 +0x17e
net/http.HandlerFunc.ServeHTTP(0x0?, {0x1da1570?, 0xc003369960?}, 0xc003376240?)
        /usr/local/go/src/net/http/server.go:2136 +0x29
github.com/weaviate/weaviate/adapters/handlers/rest/swagger_middleware.AddMiddleware.func1({0x1da1570, 0xc003369960}, 0xc00012a500)
        /go/src/github.com/weaviate/weaviate/adapters/handlers/rest/swagger_middleware/swagger_middleware.go:37 +0x219
net/http.HandlerFunc.ServeHTTP(0xc002b49260?, {0x1da1570?, 0xc003369960?}, 0x3?)
        /usr/local/go/src/net/http/server.go:2136 +0x29
github.com/weaviate/weaviate/adapters/handlers/rest.makeAddLogging.func1.1({0x1da1570, 0xc003369960}, 0xc00012a500)
        /go/src/github.com/weaviate/weaviate/adapters/handlers/rest/middlewares.go:121 +0x273
net/http.HandlerFunc.ServeHTTP(0x183cc40?, {0x1da1570?, 0xc003369960?}, 0x1c?)
        /usr/local/go/src/net/http/server.go:2136 +0x29
github.com/weaviate/weaviate/adapters/handlers/rest.addPreflight.func1({0x1da1570, 0xc003369960}, 0xc00012a500)
        /go/src/github.com/weaviate/weaviate/adapters/handlers/rest/middlewares.go:156 +0x35b
net/http.HandlerFunc.ServeHTTP(0xc003376240?, {0x1da1570?, 0xc003369960?}, 0xc0000eb8f0?)
        /usr/local/go/src/net/http/server.go:2136 +0x29
github.com/weaviate/weaviate/adapters/handlers/rest.addLiveAndReadyness.func1({0x1da1570, 0xc003369960}, 0xc00012a500)
        /go/src/github.com/weaviate/weaviate/adapters/handlers/rest/middlewares.go:195 +0x10e
net/http.HandlerFunc.ServeHTTP(0xc003376240?, {0x1da1570?, 0xc003369960?}, 0xa?)
        /usr/local/go/src/net/http/server.go:2136 +0x29
github.com/weaviate/weaviate/adapters/handlers/rest.addHandleRoot.func1({0x1da1570, 0xc003369960}, 0xc00012a500)
        /go/src/github.com/weaviate/weaviate/adapters/handlers/rest/middlewares.go:58 +0x1d9
net/http.HandlerFunc.ServeHTTP(0xc003376240?, {0x1da1570?, 0xc003369960?}, 0x0?)
        /usr/local/go/src/net/http/server.go:2136 +0x29
github.com/weaviate/weaviate/adapters/handlers/rest.makeAddModuleHandlers.func1.1({0x1da1570, 0xc003369960}, 0xc00012a500)
        /go/src/github.com/weaviate/weaviate/adapters/handlers/rest/middlewares.go:79 +0x92
net/http.HandlerFunc.ServeHTTP(0xc0000eba18?, {0x1da1570?, 0xc003369960?}, 0x29cace0?)
        /usr/local/go/src/net/http/server.go:2136 +0x29
github.com/weaviate/weaviate/adapters/handlers/rest.addInjectHeadersIntoContext.func1({0x1da1570, 0xc003369960}, 0xc00012a500)
        /go/src/github.com/weaviate/weaviate/adapters/handlers/rest/middlewares.go:174 +0x20a
net/http.HandlerFunc.ServeHTTP(0xc0000ebac8?, {0x1da1570?, 0xc003369960?}, 0x72c225?)
        /usr/local/go/src/net/http/server.go:2136 +0x29
github.com/weaviate/weaviate/adapters/handlers/rest.makeCatchPanics.func1.1({0x1da1570?, 0xc003369960?}, 0xc002fae2e0?)
        /go/src/github.com/weaviate/weaviate/adapters/handlers/rest/panics_middleware.go:29 +0x98
net/http.HandlerFunc.ServeHTTP(0x412945?, {0x1da1570?, 0xc003369960?}, 0xc003369901?)
        /usr/local/go/src/net/http/server.go:2136 +0x29
net/http.serverHandler.ServeHTTP({0x1d9ce60?}, {0x1da1570?, 0xc003369960?}, 0x6?)
        /usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc003376090, {0x1da68e0, 0xc002fe40f0})
        /usr/local/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 100
        /usr/local/go/src/net/http/server.go:3086 +0x5cb`

### Server Version

1.23.6

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by antas-marcin** [comment]
@adambeer I have created [e2e tests](https://github.com/weaviate/weaviate/pull/4101/files) for `v1.23` and they all pass. Can you tell me more about your setup? is it a Weaviate cluster? from which Weaviate version did you upgrade to `v1.23.6`?

**Comment by adambeer** [comment]
@antas-marcin Its a docker self hosted installation on Amazon Linux 2023. Its a completely fresh install, no other version of Weaviate was ever on the machine.

**Comment by antas-marcin** [comment]
Ok, and you are doing this by directly invoking our REST API, yes? you are not using any of our clients?

**Comment by adambeer** [comment]
Just direct REST API. Ive never had issues doing it this way until this
version.

**Comment by antas-marcin** [comment]
@adambeer I have used this with my local Weaviate running on port 8080 and I was successful.
Can you also try to run this code against your environment?

```
curl \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{
        "class": "Article",
        "description": "A written text, for example a news article or blog post",
        "vectorizer": "text2vec-openai",
        "moduleConfig": {
          "text2vec-openai": {
            "vectorizeClassName": false,
            "model": "text-embedding-3-large",
            "dimensions": 3072
          }
        },
        "properties": [
            {
            "dataType": [
                "string"
            ],
            "description": "Title of the article",
            "name": "title"
            },
            {
            "dataType": [
                "text"
            ],
            "description": "The content of the article",
            "name": "content"
            }
        ]
    }' \
    http://localhost:8080/v1/schema
```

**Comment by adambeer** [comment]
@antas-marcin I just realized that I had the wrong configurations in the properties set to a different module...my bad. Sorry for the waste of time. Im closing this issue.
