### ISSUE TITLE
Async Index - Bug Failure

### ISSUE THREAD

**Issue by msj121** [weaviate/weaviate#4109]
### How to reproduce this bug?

No idea.

### What is the expected behavior?

To index - I assume that there is some code that is not checking the length... server should not fail due to this imo. - Currently it just builds up the vector queue size, good fallback as far as I can tell.

sadly bringing server down and backup still shows this error.

### What is the actual behavior?

`{"action":"cyclemanager","callback_id":"segmentgroup/compaction//var/lib/weaviate/episode/A6PjEAjA5S8c/lsm/property_description_searchable","callbacks_id":"store/compaction/..","class":"Episode","index":"episode","level":"error","msg":"callback panic: runtime error: makeslice: len out of range","shard":"A6PjEAjA5S8c","time":"2024-01-31T00:53:24Z"}`

### Server Version

1.23.3

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by asdine** [comment]
@msj121 Do we have access to a stacktrace or logs?

**Comment by msj121** [comment]
Sorry - I had it on "debug" not trace - I will try to change that for next time when I restart. Also, sadly I nuked that setup - but I have some of the data. I will try to push the data back into a new setup to see if I can get the error.

In the end weaviate did seem to handle indexing everything even after this error; however, it did this only after restarted (composer down and up).

**Comment by etiennedi** [comment]
A wild guess, but given the `_searchable` suffix of the prop title and the similar error message, I guess that this is a symptom of #4125. Please reopen if it occurs again.
