### ISSUE TITLE
generative-openai module is using a deprecated API version - Azure stopping support on 2 April 2024

### ISSUE THREAD

**Issue by felixthekraut** [weaviate/weaviate#4126]
### How to reproduce this bug?

The generative-openai module is using a deprecated API version for chat completions. Azure has notified its customers that the `2023-03-15-preview` version is deprecated and will be [fully retired (aka no longer accept API requests) on 2 April 2024](https://review.learn.microsoft.com/en-us/azure/ai-services/openai/api-version-deprecation?branch=pr-en-us-256331#retiring-soon). Azure is advising to migrate to `2023-12-01-preview`.

The `2023-03-15-preview` version is referenced in [https://github.com/weaviate/weaviate/blob/192abf0c71d9a2d1a39b233ba374167343014d59/modules/generative-openai/clients/openai.go#L42](https://github.com/weaviate/weaviate/blob/192abf0c71d9a2d1a39b233ba374167343014d59/modules/generative-openai/clients/openai.go#L42)

My recommendation is to upgrade to the new API version before the end of February in order to allow Azure users at least one month (March) to upgrade their Weaviate instances.

### What is the expected behavior?

Utilize `2023-12-01-preview` API version and avoid service disruptions for users leveraging Azure.

### What is the actual behavior?

The generative-openai module uses the `2023-03-15-preview` version and will cease to function for Azure customers on 2 April 2024.

### Supporting information

For context, here is the email Azure sent to its customers:

> Update your code to use the latest Azure OpenAI Service preview API by 2 April 2024
You're receiving this email because you've used an older Azure OpenAI Service preview API in the last 30 days. 
We recently made Azure OpenAI API [version 2023-12-01-preview](https://review.learn.microsoft.com/azure/ai-services/openai/api-version-deprecation?branch=pr-en-us-256331) available. You'll need to update any code that uses the following older versions before they're [retired](https://review.learn.microsoft.com/azure/ai-services/openai/api-version-deprecation?branch=pr-en-us-256331) on 2 April 2024: 
•	2023-03-15-preview 
•	2023-06-01-preview 
•	2023-07-01-preview 
•	2023-08-01-preview 
•	2023-09-15-preview 
The 2023-12-01 preview version includes improvements such as support for DALL-E 3.0 and enhanced content filtering. 
Required action 
To avoid potential service disruptions, [update your code](https://learn.microsoft.com/azure/ai-services/openai/reference) that uses any of the retiring Azure OpenAI API versions to use version 2023-12-01 by 2 April 2024.

### Server Version

1.23.7

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by dudanogueira** [comment]
Hi! It will be updated soon: https://github.com/weaviate/weaviate/pull/4124
Thanks!

**Comment by felixthekraut** [comment]
@dudanogueira I see your PR but it looks like it is defaulting the version to `2022-12-01` or am I missing something?

**Comment by felixthekraut** [comment]
@dudanogueira sorry I was looking at the wrong PR, disregard my comment!
