### ISSUE TITLE
Unexpected status code: 401, with response body: {'code': 401, 'message': 'oidc auth is not configured, please try another auth scheme or set up weaviate with OIDC configured'}.

### ISSUE THREAD

**Issue by Victor94-king** [weaviate/weaviate#4139]
### How to reproduce this bug?

I encountered this error while using dify project , and I try to connect using code below to connect weaviate but it also report error.

import weaviate

auth_config = weaviate.AuthApiKey(api_key="xxx")

client = weaviate.Client(
  url="http://localhost:8080",
  auth_client_secret=auth_config
)

Besides , I used template docker-compose.yaml file to build up weaivate repo, and I dont think this is reason why it happend.
`
---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.23.7
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'text2vec-cohere,text2vec-huggingface,text2vec-palm,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai'
      CLUSTER_HOSTNAME: 'node1'
volumes:
  weaviate_data:
...`

### What is the expected behavior?

connect to weative 

### What is the actual behavior?

![image](https://github.com/weaviate/weaviate/assets/103173758/6bb6d772-5b00-418e-93a0-dcb850dfe4d5)

### Server Version

1.23.7

### Code of Conduct

- [x] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by Victor94-king** [comment]
Hoping any help , best wishes!!!

**Comment by rthiiyer82** [comment]
Hey, if you are connecting to weaviate local instance (localhost:8080) then you don't need an API key. If you are trying to connect to Weaviate instance to the public internet then authentication is required. Also, if you using modules like Openai or huggingface then these would require API key and they are sent as assitional headers. Please visit https://weaviate.io/developers/weaviate/tutorials/connect for more details.
