### ISSUE TITLE
Default all properties in Read all Objects

### ISSUE THREAD

**Issue by pi-curst** [weaviate/weaviate#4143]
### Describe your feature request

Currently, it is required to specify the properties we intend to retrieve other. Is it possible to modify this so that if no properties are explicitly specified, all properties will be returned by default?

See step 1 --> https://weaviate.io/developers/weaviate/manage-data/read-all-objects

```
  query = (
      client.query.get(
          collection_name,       
          ["title", "description"] # update with the required properties <-- Can this be made optional and return all properties if not specified 
      )
      .with_additional(["id"])
      .with_limit(batch_size)
  )

  # Fetch the next set of results
  if cursor is not None:
      result = query.with_after(cursor).do()
  # Fetch the first set of results
  else:
      result = query.do()

```
Or is there a way to retrieve all the properties from the collection without specifying?

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by dirkkul** [comment]
This is the default in python v4, but you need to update your client+code
