### ISSUE TITLE
Single missing object fails entire batch delete

### ISSUE THREAD

**Issue by parkerduckworth** [weaviate/weaviate#4232]
### How to reproduce this bug?

It's not straightforward how to reproduce this. Getting Weaviate into a state where a doc id fails to resolve to a uuid is probably the result of very unfortunate parallel operations where one thread causes the deletion of an object right before another thread performing batch delete, leading to the unresolved uuid.

However, solving the overarching issue is much more straightforward. The [batch delete response](https://weaviate.io/developers/weaviate/api/rest/batch#a-response-body-in-detail) already supports returning individual errors per object.

 Whenever [this error](https://github.com/weaviate/weaviate/blob/master/adapters/repos/db/shard_write_batch_delete.go#L151) occurs, Weaviate can simply map the error to the specific object which was not found, which will eventually wind up in the response payload, and continue with deleting the rest of the batch.

### What is the expected behavior?

One failed uuid resolution will not result in failing the entire batch delete operation

### What is the actual behavior?

One failed uuid resolution currently does result in failing the entire process

### Supporting information

StackOverflow post with a report of the same issue:
https://stackoverflow.com/questions/77835556/weaviate-delete-batch-failing-with-single-id-mapping-error

### Server Version

The initial report specifies 1.23.1, but this issue has been around for awhile.

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by dudanogueira** [comment]
for reference: you will see logs like this one:

> batch delete objects: cannot find objects: finding matching doc ids in shard "xxxxxx": could not get uuid from doc_id=xxxxx

**Comment by parkerduckworth** [comment]
Fixed with #4284
