### ISSUE TITLE
Options to disable go profiling and change port

### ISSUE THREAD

**Issue by trengrj** [weaviate/weaviate#4235]
### Describe your feature request

Currently go profiling always runs on port `6060` and cannot be disabled.

https://github.com/weaviate/weaviate/blob/58dc274e3cdfada84e53ac1f7c988f6e66e1672f/adapters/handlers/rest/configure_api.go#L893-L896

We should add environment variables to:
- Allow for the port to be changed
- Allow for profiling to be disabled

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by bennycortese** [comment]
Hi trengrj! I tried to made two pull requests relating each sub-task listed, and am new to contributing to Weaviate. Could you point me in the direction of where in the repository I should add unit tests for this/do you have any notes on related things I should change? Thank you!

**Comment by trengrj** [comment]
Hi @bennycortese, thanks for the contributions!

Around these changes. There is already a already a `Profiling` struct in the config handler:

https://github.com/weaviate/weaviate/blob/18d663c9843c9e2941bb7a391df0edd94e6e9cab/usecases/config/config_handler.go#L194-L197

Could you please extend this struct with `Port` and `Enabled` and put environment parsing in [environment.go](https://github.com/weaviate/weaviate/blob/master/usecases/config/environment.go). This will allow for tests in `environment_test.go` and also allow for the config to be specified in yaml.

**Comment by bennycortese** [comment]
Hi @trengrj, thanks for the help in pointing me towards how to do this appropriately with this repository! I really appreciate the help.

I extended the Profiling struct for my PRs, put environment parsing in environment.go and updated configure_api.go appropriately. I still am unsure how to set this up in environment_test.go, and am a little confused why things like GO_BLOCK_PROFILE_RATE aren't being tested currently. Thank you again!

**Comment by trengrj** [comment]
Close by https://github.com/weaviate/weaviate/pull/4290 thanks @bennycortese!
