### ISSUE TITLE
The "Equal" filter by property (with text type) returns invalid objects

### ISSUE THREAD

**Issue by vkrasnoselskikh** [weaviate/weaviate#4237]
### How to reproduce this bug?

Below is the code that creates a new collection and inserts two objects into it:

```python
from weaviate.classes.config import Property, DataType
import weaviate.classes as wvc

# create empty collection
collection = client.collections.create(
    "DeleteTest",
    properties=[
            Property(name="document_key", data_type=DataType.TEXT),
            Property(name="body", data_type=DataType.TEXT),
        ]
    
)
# insert 2 rows
collection.data.insert_many([
    {"document_key": "test_domain"},
    {"document_key": "test_domain_weaviate"}
])
```
Let's try to get a key from the database - which starts the same way - but is not equal to these records:

```python
result = collection.query.fetch_objects(
        filters=wvc.query.Filter.by_property("document_key").equal("test"),
)
```

### What is the expected behavior?

```python
assert len(result.objects) == 0
```

### What is the actual behavior?

```python
len(result.objects) == 2 
```

Comes in two objects instead of zero

### Supporting information

It has been noticed that this also works when deleting objects. 

Or when using "ContainsAny" in a query and passing a list of strings

### Server Version

1.23.9

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by etiennedi** [comment]
My first impression is that this is working as desired. It's just the default tokenization option of `word` which breaks up `test_domain_weaviate` into `["test", "domain", "weaviate"]`. If you want to match the exact string you can also use a tokenization option of `field`, see https://weaviate.io/developers/weaviate/config-refs/schema#tokenization

Can you verify that this fixes your issues? Thanks.

**Comment by vkrasnoselskikh** [comment]
@etiennedi Thank you so much for this reference! 

It's just what I needed! 

I added in ` Property( ... , tokenization=Tokenization.FIELD),`
and everything worked. 

It was a surprise to me - that equal works as a LIKE. 

I didn't expect all fields to be tokenized by default. 
PS. It would be good to add a link to this page in the documentation on filters!

I'm closing this commit - it's not a bug

**Comment by etiennedi** [comment]
Awesome. Glad that this is resolved.

Cc @daveatweaviate and @databyjp foe the docs feedback ⬆️

**Comment by daveatweaviate** [comment]
Opened [a ticket](https://semi-technology.atlassian.net/browse/DR-150) to update docs

**Comment by rthiiyer82** [comment]
Closing this issue as we have added a link to Tokenization in our document and also the original issue appears to have solved.
