### ISSUE TITLE
Scalar Quantization

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#4252]
### Describe your feature request

This is to see if there is any demand for scalar quantization.

Weaviate currently offers the following compression setups for HNSW:
- Uncompressed -> fastest, but also highest memory usage
- BQ -> fast, low memory usage, but requires fairly long vectors (e.g. 1536d) for decent recall
- PQ -> very tunable, great memory reduction, decent recall, but slight performance drop compared to uncompressed

The potential appeal of adding scalar quantization would be that it provides a 4x compression over uncompressed floats, but is cheaper to compute and thus increases performance. As it is lossy, it requires reranking (as all compression algos) to keep the recall high.

If you believe this would be a valuable addition to Weaviate, please upvote.

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by akakalle** [comment]
Would this include support for int8 embeddings as well? Would love to use Cohere's new int8 embeddings for example.

**Comment by trengrj** [comment]
Completed in https://github.com/weaviate/weaviate/pull/5125 (to be released in Weaviate 1.26)
