### ISSUE TITLE
Move tenants to Object Storage

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#4272]
## Backround and tl;dr

Tenants can already be deactivated to the local disk, but they still take up disk space. With this we want to allow removing them from the local disk entirely and "offload" them to cloud storage. One major selling point of this feature is that when a tenant comes back from cloud storage to the local disk, it doesn't have to land on the same node. Instead, it could pick the node with the most available resources, thus contributing to a lazy rebalancing.

## Implementation ideas in a nutshell

Ideally we can reuse as much as possible of the existing backup logic which already supports moving entire collection/classes to and from cloud storage. We can think of tenant offload as a backup (only for a single tenant) that – after successfully backing up – also deletes the state from disk. Similarly when we load the tenant back, it can be considered similar to restoring a single tenant's backup and then deleting the backup.

At the same time, while we can hopefully reuse a lot of implementation from backups, we should still consider it a separate feature. For example, when you back something up, you can create many versions of the backup and a backup itself is immutable once created. For tenant offloading there is only a single state on the cloud storage system and it can be constantly mutated. Thus the state of the backup and the offloading implementation should never cross.

## APIs

In the simplest implementation, the only things we need are:
- Some collection-wide config to associate a specific class/collection with a cloud storage mechanism. It should feel similar to configuring a backup provider and ideally use the same existing module.
- A new `activityStatus` such as `FROZEN` is introduced. If this status is selected the tenant is moved to cloud storage

## Async nature 

With local tenant deactivation the status change was synchronous and atomic. With moving tenants to S3 this process must become async because moving a large tenant could take considerable time. However, that means that we might also require a different status model because we essentially have a desired state and an actual state. Alternatively we could introduce a second status specifically for movement/offloading that could show something like `TRANSFERRING`/`COMPLETE`. Open to suggestions, the goal is to have something simple that works.

For incoming requests while a tenant is still being transferred it would be preferable if they don't fail, but rather get retried with a small backoff. This way the user can activate the tenant (async) and immediately send a request. From their POV that request is just a bit slower, but it doesn't fail. That said, this could be a future improvement. 

Another alternative that we could consider is making the first implementation synchronous and limit the supported tenant size. However, my big concern here would be crash safety, so my preference would be async from the get-go.

## Replication 

One open question is how to deal with replicated shards. In an ideal world 3 replica shards are completely identical, so just storing one would be perfectly fine. However, before we have async replication, we have no easy way to guarantee that all replicas are perfectly in sync. My pragmatic suggestion would be to simply store (and retrieve) all replicas for the time being. Cloud storage is cheap, so the extra storage is less of an issue. The extra transfer is a slight performance issue, but we can always simplify it in the future to store and transfer a single shard.

## Acceptance 

The feature can be considered complete when the following user journeys work. Note that, the journeys are presented in stages, so the feature can be delivered iteratively.

### User Journey Stage 1: Happy path
1. The user creates a collection and configures it to use S3 for tenant offloading
2. The user sends a request to mark a tenant `FROZEN`
3. Weaviate starts moving the tenant to S3.
4. The tenant can no longer be queried or any data written (a clear error message is shown)
5. The tenant no longer uses up any disk space, but still appears in the schema (e.g. `GET /v1/schema/{col}/tenants`) with a clear indication of the current status
6. Weaviate moves the tenant back from S3 to the local disk.
7. The user send a request to mark the tenant `HOT`.
8. The tenant can be queried again.

### User Journey Stage 1: Unhappy Path – Crash while transferring to Cloud Storage
* Like the first journey, but a crash occurs while Weaviate is transferring the tenant shard to cloud storage
* After the node(s) restart(s), Weaviate retries to move the shard to cloud storage
* The movement eventually succeeds.
* Until the tenant was fully moved, the local disk stays the source of truth. I.e. a partially written shard onto S3 can be considered invalid and discarded

### User Journey Stage 1: Unhappy Path – Crash while transferring from Cloud Storage
* Like the first journey, but a crash occurs while Weaviate is transferring the tenant shard back from cloud storage onto the local disk
* After the node(s) restart(s), Weaviate retries to move the shard to cloud storage
* The movement eventually succeeds.
* Until the tenant was fully moved, the cloud storage bucket stays the source of truth. I.e. a partially written shard onto the local disk can be considered invalid and discarded

### User Journey Stage 1: Unhappy Path – S3 error
If tenant could not be moved due to an S3 error the tenant status will be reset to `HOT` and a clear error message is shown in this tenant's state. (Alternative: `COLD`).  Todo: Discuss if this makes sense.

### User Journey Stage 2: Happy path with rebalancing 
1. A 3-node cluster is provisioned and 30 tenants (with data) are added
2. 15 tenants are offloaded to cloud storage
3. The cluster is grown to 6 nodes
4. The 15 tenants from cloud storage are reactivated
5. They are (at least on average) spread across the 3 new nodes, so that data is (roughly) evenly spread now that the cluster was grown

### Other Points
* All clients are compatible with the new APIs

## Priorities

Assuming that it is more effort to build this for all currently supported cloud providers than for a single one, the clear preference is to start with S3, as we see the most demand here. So, the rough priorities would be:

* Happy Path on S3 without rebalancing
* Unhappy Path on S3 without rebalancing <-- first production readiness
* S3 with rebalancing <-- biggest value to operators of large MT clusters
* Other Cloud Storage Providers

## Summary questions:

1. Consider all new names for APIs, etc., as suggestions. What names would you suggest?
7. How to deal with replication (see above)
8. How to deal with the async nature (see above)
9. Anything else missing, unclear, or undesirable?

**Comment by etiennedi** [comment]
Topics we haven't considered yet (possibly out of scope for a first iteration):

- Backup of frozen tenants -> what is the definition of a backup? 
- Rack-awareness and zonality
    - If we have a 9-node cluster spread across three zones, would each set of 3 nodes only talk to a zonal bucket, thus eliminating cross-zonal traffic? Or would there be a monolithic multi-zonal bucket?

**Comment by daveatweaviate** [comment]
Does it makes sense to runs checksums after (or during?) the transfer and before deleting the original copy?
