### ISSUE TITLE
Async indexing + immediate tenant deactivation can lead to data loss on vector index

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#4276]
### How to reproduce this bug?

1. Start Weaviate with `ASYNC_INDEXING=true`
2. Run the script below. Note that the script deactivates even tenants, but never deactivates odd tenants (control)

```python3
import weaviate
import weaviate.classes as wvc
import numpy as np
from loguru import logger

objects_per_tenant = 31
tenants = 10

client = weaviate.connect_to_local()

client.collections.delete_all()
col = client.collections.create(
    "MT", multi_tenancy_config=wvc.config.Configure.multi_tenancy(enabled=True)
)

col.tenants.create([wvc.tenants.Tenant(name=f"t{i}") for i in range(tenants)])

for tenant in range(tenants):
    t = col.with_tenant(f"t{tenant}")
    with t.batch.fixed_size(100, 4) as batch:
        for i in range(objects_per_tenant):
            batch.add_object(
                {"obj_id": i},
                vector=np.random.rand(768, 1)[0].tolist(),
            )
    if tenant % 2 == 0:
        col.tenants.update(
            [wvc.tenants.Tenant(name=f"t{tenant}", activity_status="COLD")]
        )

for tenant in range(tenants):
    if tenant % 2 == 0:
        col.tenants.update(
            [wvc.tenants.Tenant(name=f"t{tenant}", activity_status="HOT")]
        )
    t = col.with_tenant(f"t{tenant}")
    logger.info(f"tenant {tenant}: has {len(t)} objects (aggregate)")
    res = t.query.near_vector(
        near_vector=np.random.rand(768, 1)[0].tolist(), limit=10000
    )

    logger.info(f"tenant {tenant}: vector search returns {len(res.objects)} objects")
```

### What is the expected behavior?

Regardless of whether the tenant was deactivated or not, we expect the vector search to return the correct number of results.

### What is the actual behavior?

Note that even tenants (which had a deactivate/activate cycle) return too few objects when running a vector search:

<img width="1115" alt="image" src="https://github.com/weaviate/weaviate/assets/8974479/1ac76e6d-fc71-45cc-b3f7-a59efdfea204">

### Supporting information

If I run the same script with async indexing turned off all is fine. This makes me believe that async indexing plays a key role for this bug.

<img width="1099" alt="image" src="https://github.com/weaviate/weaviate/assets/8974479/28ddf91f-d1e4-41a5-b20a-52c4caccf442">

### Server Version

Tested on `v1.24.0-rc.0`, but I believe earlier versions are also affected.

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by trengrj** [comment]
Fixed by https://github.com/weaviate/weaviate/pull/4277
