### ISSUE TITLE
Hybrid - Minimum viable results - acceptance threshold - skip very bad results

### ISSUE THREAD

**Issue by sebawita** [weaviate/weaviate#4315]
### Describe your feature request

Currently, hybrid search doesn't allow me to filter out really poor results – those where both keyword and vector search provide with very poor results.

It would be great if we could provide an `acceptance threshold` as part of a hybrid query, where we would require at least on of them to be satisfied to return an object i.e.
* max vector distance – accept results where distance is not more than x
* min keyword score – accept results where the score is at least y

This way we could eliminate results that are poor on both fronts (keyword and vector).

## Example:

I have two objects:
* "a very big army helicopter"
* "a small light civilian plane"

If I search for "sandwich", this should result in poor results on both fronts, and I would expect no results back.
While a search for "aeroplane", should result in a vector match (and no match on BM25), and I should get back the two objects back.

```python
import weaviate, os
import weaviate.classes.config as wc

client = weaviate.connect_to_local(
    headers={
        "X-OpenAI-Api-Key": os.environ["OPENAI_API_KEY"]
    }
)

test = client.collections.create(
    "Test",
    vectorizer_config=wc.Configure.Vectorizer.text2vec_openai()
)

test.data.insert_many([
    {
        "name":"a very big army helicopter"
    },
    {
        "name":"a small light civilian plane"
    },
])
```

## Proposed solution

```
import weaviate.classes.query as wq 
response = test.query.hybrid(
    "sandwich",

    # The new param to remove poor results on both fronts - at least one should be satisfied to include in the result set
    acceptance_threshold: {
        min_hybrid_score: 0.1,
        max_vector_distance: 0.2
    },

    return_metadata=wq.MetadataQuery(score=True),
)
```

## Note
BM25 alone doesn't return if no match was made ;)

If I run:
```
import weaviate.classes.query as wq 
response = test.query.bm25(
    "sandwich",
    return_metadata=wq.MetadataQuery(score=True),
)
```
The query returns 0 objects.
So, that is already a good indicator that we rely solely on the vector search. ;)

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by sebawita** [comment]
Note, the idea here is not to filter on the final hybrid score, but instead to filter out results based on the separate scores/distances before we get to calculate the final hybrid score.

**Comment by dirkkul** [comment]
I just had a look at this and dont think `min_hybrid_score` makes sense - the hybrid score only shows relative differences between the results and is not stable for small changes in the search request.

To give a concrete example:
Let's say we have 3 objects and a vector search would return the following distances: [1: 0, 2: 0.0001, 3: 0.5]. Now you do a hybrid search with 
- limit=2, then you would get the hybrid scores of (ignoring BM25): [1: 1, 2: 0]
- limit=3, then you would get the hybrid scores of (ignoring BM25): [1: 1, 2: 0.999, 3:0]
