### ISSUE TITLE
[HNSW] Reduce default maxConnections from 64 to 32

### ISSUE THREAD

**Issue by trengrj** [weaviate/weaviate#4363]
### Describe your feature request

Currently Weaviate uses a default maxConnections of 64.

This means that Weaviate will use up to 64 connections in the HNSW graph in levels n .. 1 and 128 connections in level 0.

While this default works well with older ANN vector datasets such as [SIFT](https://archive.ics.uci.edu/dataset/353/sift10m) with 128 dimensions, the standard in dimensions has increased with 768, 1536, and even 3072 now common.

During testing we have found better QPS/recall curves with lower `maxConnections` and generally best the values are in the 16-32 range depending on dataset size, with `ef` increased to reach the target recall level.

Proposal is to reduce maxConnections to 32, which is still on the higher end, but provides a better QPS/recall tradeoff.

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by etiennedi** [comment]
+1

The defaults are too high and those not configuring anything could get the impression that Weaviate is too slow to import / uses too much memory, simply because we use higher defaults than other systems.

**Comment by databyjp** [comment]
To that point on the users, I would expect to see more and more users to just use "out-of-the-box" parameters. 

Interesting to read that the optimal HNSW parameters depend on the vector length. **For the users who will want Weaviate to configure the parameters for them, would it be then possible to wait & see what the vector length is?**

And upon seeing the first object, Weaviate could then set the HNSW parameters? So if you're using `text-embedding-3-large` with 256 dims you might get different defaults than if you are using `text-embedding-3-large` with 3072 dims?

**Comment by trengrj** [comment]
@daveatweaviate we aren't planning to change the default `ef` value (although the default dynamic ef value is generally on the higher side comparatively). Because `ef` can be changed at query time this is more of a user tuneable feature where they can set the `ef` value based on what they need performance / recall wise. Changing `maxConnections` however is harder for users as it requires them to reload the data into a new class.

**Comment by trengrj** [comment]
> For the users who will want Weaviate to configure the parameters for them, would it be then possible to wait & see what the vector length is?

@databyjp once we have the vector index rebuild api https://github.com/weaviate/weaviate/issues/3171, I think we could allow for more auto tuning features and possible sliders in WCS to make the index faster vs more accurate (higher recall).

**Comment by trengrj** [comment]
Closed by https://github.com/weaviate/weaviate/pull/5248
