### ISSUE TITLE
Weighted average distance on named vectors

### ISSUE THREAD

**Issue by anatoleblanc** [weaviate/weaviate#4393]
### Describe your feature request

Hey friends, 

We are heavily using the newly created features around named vectors. 
Something that would help a lot would be the possibility to do weighted average of distance on different named vectors in the same call. 

An example: 
I have two named vectors in a vector db, "title_vector" and "tags_vector". 
I want to find all objects in my collections that are closest to a given string ; 80% based on the title, 20% on the tags. 

Lmk if that was understandable :)

Congrats on all the great work here!!

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by dirkkul** [comment]
this is part of 1.26
