### ISSUE TITLE
`object_count` metrics reports nonsense values when prom grouping is active

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#4396]
### How to reproduce this bug?

* Set env var `PROMETHEUS_MONITORING_GROUP=true`
* Create multiple collections / multiple tenants

### What is the expected behavior?

`object_count` prom metrics shows the total object count

### What is the actual behavior?

`object_count` seems to be overriding by whichever memtable flushed last.

### Supporting information

Leads to a lot of confusion in WCS GUI

### Server Version

all version ever since prom grouping was introduced

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by etiennedi** [comment]
Note: This also needs to take into account lazy shard loading. The metric should not force-load all shards, either it only fires when all shards are loaded or it ignores unloaded shards. I think waiting would be nicer, because then we don't have incorrect intermediate counts.

**Comment by rthiiyer82** [comment]
Closing the issue as we now have a fix. Verified on WCS and the total object count appears to be correct.
