### ISSUE TITLE
Triggering backup stops flushing of all future memtables

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#4418]
### How to reproduce this bug?

```python3
import weaviate
import weaviate.classes as wvc
import numpy as np
import random


client = weaviate.Client(url="http://localhost:8080")

client.schema.delete_all()
client.schema.create_class({"class": "Vector"})


print("import 100 objects")
with client.batch.configure() as batch:
    for i in range(100):
        batch.add_data_object(
            {"foo": "bar"}, "Vector", vector=np.random.rand(1, 1536)[0].tolist()
        )

print("trigger backup")
res = client.backup.create(
    f"backup-{random.randint(0, 10000)}", weaviate.backup.BackupStorage.FILESYSTEM
)
print(res)


with client.batch.configure() as batch:
    for i in range(10000):
        batch.add_data_object(
            {"foo": "bar"}, "Vector", vector=np.random.rand(1, 1536)[0].tolist()
        )
```

Note that I've used the `v3` python client because older versions are affected, too, but they don't support the `v4` client yet.

### What is the expected behavior?

The backup prevents compactions, but flushing works fine.

### What is the actual behavior?

The memtable and WAL are over 6min old and still aren't flushed. They will never be flushed.

<img width="1244" alt="Screenshot 2024-03-07 at 3 55 15 PM" src="https://github.com/weaviate/weaviate/assets/8974479/18f2e9e9-62ea-4cfc-ab87-324a4eca5829">

### Supporting information

Must be a gap somewhere in our testing. The backup logic specifically stops and then pauses compactions again. It seems we are not verifying that compactions (and flushes which are a requirement for compactions) continue after the backup.

Suggested test:

- backup is triggered
- validate that compactions ARE NOT happening during the backup
- validate that flushing IS happening during the backup
- backup is complete
- validate that flushing IS happening
- validate that compactions ARE happening

### Server Version

First breaks in `v1.23.1`, all future versions are affected. `v1.23.0` is the last known working versions

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by parkerduckworth** [comment]
Fixed by #4420
