### ISSUE TITLE
"runtime error: index out of range [0] with length 0" when hybrid search query is performed

### ISSUE THREAD

**Issue by rthiiyer82** [weaviate/weaviate#4516]
### How to reproduce this bug?

1. Create a class and insert objects. python code below

```
import weaviate

import weaviate.classes.config as wvc

from weaviate.collections.classes.data import DataObject

client = weaviate.connect_to_local(
    port=8080,
    grpc_port=50051
         # Replace with your inference API key
)
if (client.collections.exists("Hybridtest")):
         client.collections.delete("Hybridtest")
    # Create collection
    collection = client.collections.create(
        name="Hybridtest",
        vector_index_config=wvc.config.Configure.VectorIndex.hnsw(),
        properties=[
            wc.Property(name="text", data_type=wc.DataType.TEXT, vectorize_property_name=True,tokenization=wc.Tokenization.WORD),
            wc.Property(name="page", data_type=wc.DataType.NUMBER, vectorize_property_name=True),
        ]
    )
    # load records
    collection.data.insert_many(
        [
            DataObject(properties={"text": "apples are big", "page": 1},vector=[1.0]* 3),
            DataObject(properties={"text": "bananas are small", "page": 2},vector=[2.0]*3),
            DataObject(properties={"text": "papaya is a tropical fruit", "page": 3},vector=[3.0]*3),
            DataObject(properties={"text": "Mangoes are grown during summers", "page": 4},vector=[4.0]*3),
            DataObject(properties={"text": "apples and bananas are fruit", "page": 5},vector=[5.0]*3),
        ]
    )
```
3. Perform a hybrid search query. Graphql payload below

```
{
  Get {
    Hybridtest(
      limit: 30
       hybrid: {
         vector:[2,2,2]
         alpha: 1.0
         query: "fruits" }
    ) {
        text
        page
        _additional{
            score
            explainScore
            vector
        }
    }
  }
}
```

### What is the expected behavior?

We should see objects in the response. for e.g in this case, I would expect to see `bananas are small` output.

Note: I don't see the error when `alpha:0.0` is provided in the query. 

### What is the actual behavior?

Graphql response below
`{"action":"requests_total","api":"graphql","class_name":"Hybridtest","error":"runtime error: index out of range [0] with length 0","level":"error","msg":"unexpected error","query_type":"Get","time":"2024-03-19T09:47:12Z`

Pythonv4 response below:
`Query call with protocol GRPC search failed with message panic occurred: runtime error: index out of range [0] with length 0.`

### Server Version

1.24.4

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by donomii** [comment]
I'm currently seeing this behave correctly on master, and v1.24.4

{
  "data": {
    "Get": {
      "Hybridtest": [
        {
          "_additional": {
            "explainScore": "\nHybrid (Result Set vector) Document 879be9de-d76b-4cd2-91ee-de01bb3efaed: original score 0.99999994, normalized score: 0.5",
            "score": "0.5",
            "vector": [
              2,
              2,
              2
            ]
          },
          "page": 2,
          "text": "bananas are small"
        }
      ]
    }
  }
}

**Comment by donomii** [comment]
Could not reproduce, possibly fixed as part of another feature
