### ISSUE TITLE
[v1.24] Minimal observability for schema transactions

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#4602]
Schema transactions will disappear in v1.25 with #4280, but until then, we want to be able to mitigate schema-tx-related issues better.

Goals:
- Metrics that indicate when tx was started and resolved, as well as time since last successful schema change
- Tx-slowlog that can give general info about a tx taking longer than expected, including what it is waiting for

**Comment by etiennedi** [comment]
Metrics-suggestions from @mikewyer:

<img width="1100" alt="image" src="https://github.com/weaviate/weaviate/assets/8974479/0bf6d274-64e5-4656-b3a6-e95244f5a76c">

**Comment by dirkkul** [comment]
1.24 is not supported anymore, closing this :)
