### ISSUE TITLE
`X-Azure-Api-Key` doesn't work  in headers. Asking openai api key instead. while calling withNearText search.

### ISSUE THREAD

**Issue by mihir-kanzariya** [weaviate/weaviate#4649]
### How to reproduce this bug?

I am using azure openai, i created class and client . 

`const client = weaviate.client({
    scheme: 'https',
    host: 'XXXXX-vv0royyl.weaviate.network',
    headers: { 
        "X-Azure-Api-Key": PROCESS.ENV.AZURE_OPENAI_KEY
    }
});
`

I get below error while calling Below function

Function: ` result = await client.graphql
            .get()
            .withClassName(model)
            .withNearText({
                concepts: [question],
                targetVectors: ['content'],
            })
            .withWhere({
                path: ['trainingDataType'],
                operator: 'Equal',
                valueText: trainingDataType,
            })
            .withLimit(limit)
            .withFields('content _additional { distance }')
            .do();`
            
            
 Error
 `{
  "response": {
    "data": {
      "Get": {
        "Custcity": null
      }
    },
    "errors": [
      {
        "locations": [
          {
            "column": 6,
            "line": 1
          }
        ],
        "message": "explorer: get class: vectorize params: vectorize params: vectorize params: vectorize keywords: remote client vectorize: API Key: no api key found neither in request header: X-Openai-Api-Key nor in environment variable under OPENAI_APIKEY",
        "path": [
          "Get",
          "Custcity"
        ]
      }
    ],
    "status": 200,
    "headers": {}
  },
  "request": {
    "query": "{Get{Custcity(where:{operator:Equal,valueText:\"SCHEMA\",path:[\"trainingDataType\"]},nearText:{concepts:[\"Analyze the correlation between the number of activities (tasks and events) and opportunity win rates.\"],targetVectors:[\"content\"]},limit:8){content _additional { distance }}}}"
  }
}`

### What is the expected behavior?

It should consider azure open ai key

### What is the actual behavior?

It is not working with azure openai key

Slack conversation about issue: https://weaviate.slack.com/archives/C02RRQP23K3/p1712830332189929

### Server Version

1.24.8

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by andrewisplinghoff** [comment]
Probably not related to the actual problem, but I do not think that you can pass `baseURL`, `deploymentId` and `resourceName` as query parameters: https://weaviate.io/developers/weaviate/modules/retriever-vectorizer-modules/text2vec-openai#query-time-parameters

These settings related to Azure OpenAI are configured on the collection level:
https://weaviate.io/developers/weaviate/modules/retriever-vectorizer-modules/text2vec-openai#api-settings-azure-openai

**Comment by mihir-kanzariya** [comment]
in any case, it didn't work, I tried many combinations. Please follow slack conversation for better understanding of issue.

I guess there is a bug.

**Comment by rg1918** [comment]
Is there any update on this ?

**Comment by antas-marcin** [comment]
@mihir-kanzariya I think that I know why are you getting this error. I don't know how your class is configured but it looks like that Weaviate doesn't recognize it that it's an Azure configuration, did you define `resourceName` and `deploymentId` in your classes config?

**Comment by leSullivan** [comment]
Hi, 

im still Getting this error


    vectorizers: vectorizer.text2VecAzureOpenAI({
            deploymentID: AZURE_OPENAI_EMBEDDING_DEPOYMENT,
            baseURL: this.configService.openai.endpoint,
            resourceName: this.configService.openai.resourceName,
     }),

`
ENABLE_MODULES: text2vec-openai`
` DEFAULT_VECTORIZER_MODULE: text2vec-openai`

Any new solutions? Running the newest JS Client and Docker Img

**Comment by flipace** [comment]
According to the logic in weaviate, in case deploymentId or resourceName are not defined, it will not consider it to be an azure vectorizer (it internally uses the same text2vec-openai module).

@leSullivan I guess in your case it's due to `deploymentID` which should be `deploymentId`.

@andrewisplinghoff it's not possible atm to supply `resourceName` or `deploymentId` at request time - they both have to be configured in the class/collection schema at the moment and can't be overwritten. (see also https://github.com/weaviate/weaviate/issues/3605)

**Comment by dirkkul** [comment]
I think this was fixed - please reopen in case it was not

**Comment by yijingz1227** [comment]
I found this issue while following the setup guide. 

https://weaviate.io/developers/weaviate/model-providers/openai-azure/embeddings#vectorizer-parameters

<img width="946" alt="Image" src="https://github.com/user-attachments/assets/8006ec45-e4b6-4dd2-bd25-edc03cf69b79" />

While it should be `deploymentId` for `isAzure` to evaluate to `true`. 
https://github.com/weaviate/weaviate/blob/b9736cb2e492662a667e372c6aade5d1c452e2d2/modules/text2vec-openai/ent/class_settings.go#L142-L144
