### ISSUE TITLE
Windows is not supported with Embedded

### ISSUE THREAD

**Issue by Karthiksaran-001** [weaviate/weaviate#4668]
### Describe your feature request

when i install the Package and use for my Windows OS its showing error saying this feature is not supported by windows below i share the full description of the error 

WeaviateStartUpError: Windows is not supported with Embedded. Please upvote this feature request if you want this: https://github.com/weaviate/weaviate/issues/3315

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by tsmith023** [comment]
Hi @Karthiksaran-001, there is a long-running open issue in the backlog for this very feature: https://github.com/weaviate/weaviate/issues/3315

Please add your vote to that. I will be closing this issue as a duplicate in favour of the other, cheers!
