### ISSUE TITLE
text2vec-ollama is not working 

### ISSUE THREAD

**Issue by gkiri** [weaviate/weaviate#4796]
### How to reproduce this bug?

Enable the text2vec-ollama module

### What is the expected behavior?

able to import

### What is the actual behavior?

skipping the module

### Server Version

1.24.10

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by trengrj** [comment]
@gkiri can you please supply your `text2vec-ollama` configuration?

**Comment by gyuta** [comment]
@gkiri 

https://weaviate.io/developers/weaviate/modules/retriever-vectorizer-modules/text2vec-ollama
In document, it says 
> ADDED IN v1.25

But your weaviate version is 1.24.10.
So i think you have to update your weaviate.

In my case, I changed `docker-compose.yml`
> image: cr.weaviate.io/semitechnologies/weaviate:latest

and i got a` "version": "1.25.2"`

**Comment by gkiri** [comment]
works with latest .Thanks
