### ISSUE TITLE
Hybrid should skip properties with indexSearchable=False

### ISSUE THREAD

**Issue by dirkkul** [weaviate/weaviate#4869]
### How to reproduce this bug?

- have a property that is indexSearchable=False
- do a hybrid search without giving properties - might only happen with aggregate
- get error

```

weaviate.exceptions.WeaviateQueryError: Query call with protocol GQL Aggregate failed with message Error in GraphQL response: [
  {
    "locations": [
      {
        "column": 12,
        "line": 1
      }
    ],
    "message": "shard VHQYjfGOV5hV: sparse search: aggregate sparse search: bm25 objects: Searching by property 'product_id' requires inverted index. Is `indexSearchable` option of property 'prop' enabled? Set it to `true` or leave empty",
    "path": [
      "Aggregate",
      "Collection"
    ]
  }
], for the following query: {Aggregate{Collection(objectLimit: 12 hybrid:{query: "query", alpha: 0.7}){meta{count}}}}.
```

### What is the expected behavior?

no error

### What is the actual behavior?

error

### Server Version

1.25.0-rc0

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by donomii** [comment]
Confirmed this is only happening in aggregate

**Comment by rthiiyer82** [comment]
I can confirm that the above error isn't shown when performing aggregate hybrid search have property with indexSearchable=False
