### ISSUE TITLE
SIMD support for Scalar Quantisation

### ISSUE THREAD

**Issue by abdelr** [weaviate/weaviate#4966]
### Describe your feature request

When we use Scalar Quantisation, there are two settings where we need to calculate distances. During indexing, required by the pruning heuristic, we need to calculate distances between compressed vectors. During querying, we need to calculate the distance from the uncompressed query vector to the compressed indexed vectors.
A compressed vector is represented by a sequence of bytes. Each byte been the code that approximates the original `float32` in the corresponding dimension. The code is generated as:

```go
byte(math.Floor(float64((x - b) * codes / a)))
``` 

Where `a` and `b` are the global range and min of the variables you are encoding and codes stands for the amount of `codes` you want to generate (default to 256, meaning we use a full byte). Similarly, the original value could be approximated from de code as:

```go
x*a/codes+b
```

Based on the code before, we can infer the distance calculations for `dot` and `l2squared` directly in the compressed space as follows:

#### compressed to compressed (both, x and y are byte arrays)

```math
\sum_{i=1}^n \left( x_i*a/codes+b \right)* \left( y_i*a/codes+b \right)
```
```math
a^2/codes^2\sum_{i=1}^n \left( x_i*y_i \right)+a*b/codes+\sum_{i=1}^n\left(x_i\right)+\sum_{i=1}^n\left(y_i\right)+ib^2
```

Most parts we can pre-calculate except 

```math
\sum_{i=1}^n \left( x_i*y_i \right)
```

which we could implement very efficiently using SIMD.

#### uncompressed to compressed  (x is a float32 array and y is a byte array)
Similarly in the case we calculate distance from compressed to uncompressed vectors we would have:

```math
\sum_{i=1}^n x_i* \left( y_i*a/codes+b \right)
```

where x is a float32 array (uncompressed). We could derive the expression:

```math
a/codes\sum_{i=1}^n \left( x_i*y_i \right)+b\sum_{i=1}x_i
```

In this case we could calculate the 

```math
\sum_{i=1}x_i
```

once per vector when creating the distance but still need the SIMD version of 

```math
\sum_{i=1}^n \left( x_i*y_i \right)
```

#### compressed to compressed (both, x and y are byte arrays)

```math
\sum_{i=1}^n \left(\left( x_i*a/codes+b \right)- \left( y_i*a/codes+b \right) \right)^2
```
```math
a^2/codes^2*\sum_{i=1}^n \left( x_i- y_i \right)^2
```

so we need the SIMD implementation of:

```math
\sum_{i=1}^n \left( x_i- y_i \right)^2
```

#### uncompressed to compressed  (x is a float32 array and y is a byte array)

```math
\sum_{i=1}^n \left(x_i- \left( y_i*a/codes+b \right) \right)^2
```
```math
\sum_{i=1}^n \left(x_i^2 \right)+\left(a/codes\right)^2*\sum_{i=1}^n \left(y_i^2 \right)+n*b^2-2*a/codes*\sum_{i=1}^n \left(x_i*y_i \right)-2*b*\sum_{i=1}^n \left(x_i \right)+2*a*b/codes*\sum_{i=1}^n \left(y_i \right)
```
In this last case, we do not need any new function since we could calculate this based on the previous cases.

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by trengrj** [comment]
Closed by https://github.com/weaviate/weaviate/pull/5147 https://github.com/weaviate/weaviate/pull/4756 https://github.com/weaviate/weaviate/pull/5095 https://github.com/weaviate/weaviate/pull/5077
