### ISSUE TITLE
Description cannot be changed in 1.25.1

### ISSUE THREAD

**Issue by dudanogueira** [weaviate/weaviate#4981]
### How to reproduce this bug?

Try changing the description of a collection in 1.25.1

```python
import weaviate
client = weaviate.connect_to_local()
client.collections.delete("Test")
col = client.collections.create(
    "Test",
    description="This is a test"
)
col.config.update(description="Updated!")
assert(col.config.get().description == "Updated!")
```

### What is the expected behavior?

The description gets updated

### What is the actual behavior?

the description is not updated

### Server Version

1.25.1

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by dirkkul** [comment]
should be fixed in latest version
