### ISSUE TITLE
Restarts after HNSW delete cleanup cycles can lead to "Phantom Tombstones"

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#5019]
### How to reproduce this bug?

1. Import a dataset and force multiple delete cleanup cycles. The easiest way to do this is with with the v2 go-benchmarker using `go run main.go  ann-benchmark -v ~/Downloads/dbpedia-100k-openai-ada002-euclidean.hdf5 -d l2-squared --indexType hnsw --updatePercentage 0.05 --cleanupIntervalSeconds 30 --updateIterations 10 --updateRandomized`
2. Make sure that the import leads to multiple HNSW commit logs which can be condensed independently (this is the case with all default settings as of v1.23/v1.24/v1.25.
3. Wait for all tombstones to be cleaned up
4. Restart server

### What is the expected behavior?

All tombstones were cleaned up in the previous process, therefore no tombstones will be found or cleaned.

### What is the actual behavior?

We get some "false positives" or "phantom tombstones" referring to tombstones that have already been cleaned. Note that the cleanup cycle is very fast, as no actual work has to be done. Here is an example from a production setup, the red line denotes the restart. Note that we have more tombstones afert the restart than before:

<img width="1188" alt="Screenshot 2024-05-24 at 8 47 31 PM" src="https://github.com/weaviate/weaviate/assets/8974479/21ccee1d-dacc-44d2-8c62-4d23fa2c9120">
after

### Supporting information

Based on an initial investigation the theory is that the HNSW condenser loses information about removing a tombstone if that tombstone was not added in the same log, but a previous one.

### Server Version

v1.24.x (likely to affect previous versions, too)

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by trengrj** [comment]
Fixed with https://github.com/weaviate/weaviate/pull/5028
