### ISSUE TITLE
X-Google-Vertex-Api-Key doesn't work with Vertex models

### ISSUE THREAD

**Issue by sebawita** [weaviate/weaviate#5029]
### How to reproduce this bug?

To reproduce, use `X-Google-Vertex-Api-Key` as a header and a vertex model with the Python client.

```python
# This call doesn't work
client = weaviate.connect_to_local(
    headers={
        "X-Google-Vertex-Api-Key": VERTEX_AI_KEY, # this doesn't work 
        # "X-Google-Api-Key": VERTEX_AI_KEY,      # this works
        "X-Google-Studio-Api-Key": AI_STUDIO_KEY,
    }
)


collection = client.collections.create(
    name="ExampleCollection",

    # Define & configure the vectorizer module
    vectorizer_config=[
        Configure.NamedVectors.text2vec_palm(
            name="content",
            source_properties=["title"],
            model_id="text-embedding-004",

            api_endpoint="generativelanguage.googleapis.com",
            project_id="devrel-projects",
        ),

        Configure.NamedVectors.multi2vec_palm(
            name="poster",
            source_properties=["title"],
            model_id="textembedding-gecko@003",

            location="us-central1",
            project_id="devrel-projects"
        )
    ],
)

# this will fail
collection.data.insert({ "title": "a lazy brown fox that doesn't jump, because he is lazy"})
```

### What is the expected behavior?

It should be possible to pass Vertex key `X-Google-Vertex-Api-Key` as the header.

### What is the actual behavior?

`X-Google-Vertex-Api-Key` is not recognised by the Google module

### Server Version

1.24.14

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by antas-marcin** [comment]
This issue has been fixed in [v1.24.15](https://github.com/weaviate/weaviate/releases/tag/v1.24.15) and [v1.25.2](https://github.com/weaviate/weaviate/releases/tag/v1.25.2)
