### ISSUE TITLE
Cannot query certainty on a GroupBy call

### ISSUE THREAD

**Issue by jacksonhmg** [weaviate/weaviate#5078]
### How to reproduce this bug?

In this GraphQL call (no groups), certainty works fine:

```
"query": f"""
            {{
                Get {{
                    {class_name} (
                        limit: {limit}
                        nearText: {{
                            concepts: {json.dumps(concept)}
                        }}
                        where: {{
                            operator: Equal
                            path: ["user_id"]
                            valueString: "{user_id}"
                        }}
                    ) {{
                        {", ".join(fields)}
                        _additional {{
                            id
                            certainty
                        }}
                    }}
                }}
            }}
            """
```
            
            
            
            
            
 However, in this GraphQL call (with groups):
```
 query = f"""
    {{
        Get {{
            {class_name}(
                limit: {total_limit}
                nearText: {{
                    concepts: {json.dumps(keywords)}
                }}
                where: {{
                    operator: Equal
                    path: ["user_id"]
                    valueString: "{user_id}"
                }}
                groupBy: {{
                    path: ["category"],
                    groups: 6,
                    objectsPerGroup: {limit}
                }}
            ) {{
                _additional {{
                    group {{
                        groupedBy {{
                            path
                            value
                        }}
                        count
                        hits {{
                            {", ".join(fields)}
                            _additional {{
                                id
                                certainty
                            }}
                        }}
                    }}
                }}
            }}
        }}
    }}
    """
```
    
    
    I get this error:
    
    `[{'locations': [{'column': 33, 'line': 31}], 'message': 'Cannot query field "certainty" on type "All_MemoriesAdditionalGroupHitsAdditional".', 'path': None}]`

### What is the expected behavior?

Seeing as distance can be queried per object, I assumed certainty could be called the same way

### What is the actual behavior?

The error:
[{'locations': [{'column': 33, 'line': 31}], 'message': 'Cannot query field "certainty" on type "All_MemoriesAdditionalGroupHitsAdditional".', 'path': None}]

### Server Version

4.5.7

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by parkerduckworth** [comment]
Hey @jacksonhmg thanks for opening the issue. This is not a bug, just a feature which is not implemented yet. I'll make sure the limitation is documented from now on.
