### ISSUE TITLE
Request for Korean Language Tokenization Support (e.g. using Spacy Tokenizer)

### ISSUE THREAD

**Issue by yspaik** [weaviate/weaviate#5111]
### Describe your feature request

Hi, starting with version 1.24, Weaviate provides gse and trigram tokenization methods, mentioned in your document. Gse implements the "Jieba" algorithm, a popular Chinese text segmentation algorithm, while trigram splits text into all possible trigrams, useful for languages like Japanese. 

However, It seems that Korean is still not supported. To support Korean, allowing the setting of the Spacy tokenizer would suffice, as Spacy tokenizer supports Korean.

Is there any plan to support the feature of specifying the Spacy tokenizer as an additional option?

ref.
- Weaviate tokenization configuration
https://weaviate.io/developers/weaviate/config-refs/schema#tokenization

- Spacy Korean Tokenization model  
https://spacy.io/models/ko

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by dirkkul** [comment]
we added a tokenizer for korean in 1.27: https://weaviate.io/developers/weaviate/config-refs/schema#kagome_kr-tokenization-method
