### ISSUE TITLE
Add option to include HNSW cache prefilling in shard ready status

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#5161]
## Background

Right now, a zero-downtime rolling update is not always zero down-time on large-scale single-tenant setups. This is because of the following reasons:

- The starting node starts receiving traffic as soon as it reports ready
- It reports ready as soon as the DB is ready which in turn means the shards are loaded (assuming lazy shard loading is turned off, as it should be on large-scale single-tenant cases)
- A shard reports ready as soon as the index is loaded, however at this point it would still have a cold vector cache
- On a small-scale setup a cold vector cache is only a small performance penalty, but as we reach billion-scale setups, a cold cache means any request will effectively time out

## Feature request

1. Add a config flag such as `HNSW_STARTUP_WAIT_FOR_VECTOR_CACHE=true` which will make the cache prefilling synchronous and not report ready until the cache is ready
2. The flag should default to `false` for backward compatibility 
3. If set, startup time would be slightly higher, as we know have to wait for the cache to be filled, but in turn we'd only include the node in the load balancing when it's _actually_ ready to serve (at this scale)

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by trengrj** [comment]
Close by https://github.com/weaviate/weaviate/pull/5162
