### ISSUE TITLE
[CRITICAL] LSM objects may become corrupted from accidentally initializing bucket multiple times

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#5204]
### How to reproduce this bug?

1. Run with an image from https://github.com/weaviate/weaviate/pull/5203. *Note: As of creating this ticket this may require building an image locally, as the CI pipeline for that build currently fails*
2. Run the existing "tenant activation/deactivation" test of the chaos pipeline

### What is the expected behavior?

Pipeline completes

### What is the actual behavior?

![image](https://github.com/weaviate/weaviate/assets/8974479/20138614-69d0-4bfa-9667-71fe69f11d2c)

### Supporting information

Note that the new image actually _prevents_ the corruption by failing explicitly. However, in the same place where we now fail explicitly, we would previously silently accept the multiple bucket instantiations – which would in turn mean competing threads would try to run compactions on the same files – without any synchronization.

### Server Version

`v1.25.4`. Current theory is that this bug is new and was introduced with the RAFT changes (v1.25.0), but we can't rule out that it is older, either.

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by dirkkul** [comment]
pretty sure this was also fixed - closing but please reopen in case it was not
