### ISSUE TITLE
Cannot uncheck auto schema generation on WCS managed cluster

### ISSUE THREAD

**Issue by eostis** [weaviate/weaviate#5215]
### How to reproduce this bug?

Uncheck the option and save.

### What is the expected behavior?

Option should be unchecked.

### What is the actual behavior?

Option remains checked.

### Supporting information

[screencast-console.weaviate.cloud-2024.06.26-14_27_17.webm](https://github.com/weaviate/weaviate/assets/1785759/1d1cb1f3-4406-4776-beb0-a0b5952cd8f7)

### Server Version

1.25.5

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by eostis** [comment]
The ideal solution would be to set this option from the schema API: #1759

**Comment by mohamedshahin-weaviate** [comment]
@eostis Thank you so much for letting us know, I will update you over the support ticket.

**Comment by mohamedshahin-weaviate** [comment]
@eostis This has been fixed!

**Comment by eostis** [comment]
And it's working great now! I could create the indices for my customer's multilingual WooCommerce with Cohere.
