### ISSUE TITLE
Add metrics for batch sizes

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#5219]
### Describe your feature request

We can see in the metrics if a batch is slower than usual, but we cannot see why. There are all kinds of possible reasons for this. The simplest possible explanation is that a batch was simple larger (either in object count or total size in kb) than usual. It would be nice to be able to see this in the metrics.

Therefore, requesting two counters along the lines of `batch_objects_processed_total` and `batch_objects_processed_bytes`. We can then use `rate()` to look for changes.

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by Wert1996** [comment]
Hey, I would like to work on this as a first issue. I am guessing these are desired metrics for the batch object creation API. 
Can I get more details regarding this ? Some code pointers would be very helpful. 
Thank you, looking forward to contributing here.

**Comment by trengrj** [comment]
Hi @Wert1996, @robbespo00 has started working on this issue but happy to have a conversation with you on other possible issues or ideas if you are looking to contribute to Weaviate.

**Comment by Wert1996** [comment]
> Hi @Wert1996, @robbespo00 has started working on this issue but happy to have a conversation with you on other possible issues or ideas if you are looking to contribute to Weaviate.

Thanks for letting me know @trengrj . I will pick another issue.
