### ISSUE TITLE
Unable to combine uuids with strings in DataObject arrays

### ISSUE THREAD

**Issue by trengrj** [weaviate/weaviate#5264]
I expect a string "06bd10e6-e8c2-4277-b534-54583348669e" in a text[] will index ok but get the following error:

```python
import weaviate
import weaviate.classes as wc
from weaviate.collections.classes.data import DataObject

client = weaviate.connect_to_local(
    port=8080,
    grpc_port=50051,
)

client.collections.delete(name="Test")
collection = client.collections.create(name="Test")


collection.data.insert_many([
    DataObject(properties={"name": ["test", "06bd10e6-e8c2-4277-b534-54583348669e"]}),
])
```

Produces error

```
WeaviateInsertManyAllFailedError: Every object failed during insertion.
Here is the set of all errors: property 'name' on class 'Test': element [1]: mismatched data type - 'text' expected, got 'uuid'
```

**Comment by tsmith023** [comment]
This seems to be a problem with autoschema, specifically [this line](https://github.com/weaviate/weaviate/blob/main/usecases/objects/auto_schema.go#L303)

@danielbichuetti, is autoschema critical to your use-case? If not, disabling it should help!

**Comment by danielbichuetti** [comment]
@tsmith023 The schema was manually created. It's a `TEXT_ARRAY`. It happens when using `insert_many` and the new v4 client.

**Comment by tsmith023** [comment]
@danielbichuetti, can you provide an MRE for your Python code that demonstrates the issue originally reported by @trengrj? The error `mismatched data type -` only appears in the autoschema logic, perhaps you are seeing a different error?

**Comment by tsmith023** [comment]
> For already created collections, autoschema should not mess up, right? Or, just by being enabled it will somehow try to convert objects?

Indeed, autoschema shouldn't trigger for created collections. Is there possibly a misnaming issue going on whereby you create a collection with one name and then insert into a collection with an accidentally different name thereby triggering autoschema?

**Comment by danielbichuetti** [comment]
That's not the case, for sure. Here is the error message and the property. As you can see, the name is correct. This is only happening in TEXT_ARRAY.

` {1: ErrorObject(message="property 'metadata__origin_case_numbers' on class 'Documents': element [4]: mismatched data type - 'text' expected, got 'uuid'"`

![image](https://github.com/weaviate/weaviate/assets/90110233/83ad50ce-13dc-4343-afb4-56588496e471)

I will post later today a minimum reproducible code for you. But this is not the only data type error we are facing here. Furthermore, when using OBJECT_ARRAY and the TEXT_ARRAY inside it, we get errors for nil values.
