### ISSUE TITLE
Add flag to expand search to all available replicas

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#5293]
### Describe your feature request

* We introduce a flag, such as `SEARCH_FORCE_EXPAND_TO_ALL_REPLICAS` (just a draft name, pick a better one please!)
* If the flag is set, we try to query all replicas available in the cluster (best effort while keeping CL guarantees, see below)
* If a replica is unavailable, but the specified CL can still be reached, the search succeeds
* If so many replicas are unavailable that the specified CL can no longer be reached, the search fails
* Scope: For now only VectorSearch needs to be covered, in the future we might want to expand this to Hybrid Search or Keyword search, as well

## Example 1 (current behavior without the flag)

Imagine a 6-node cluster with a collection shared two times and replicated 3 times (`sharding.desiredCount==2`, `replication.factor==3`)

* The shards are named `s1`, `s2`
* The shards are distributed on the nodes as follows:
    * Node 1: `s1`
    * Node 2: `s2`
    * Node 3: `s1`
    * Node 4: `s2`
    * Node 5: `s1`
    * Node 6: `s2`
* A vector search comes in at Node 4 which makes node 4 the coordinator
* Node 4 has a local copy of `s2`, so it needs to a remote node to get results from `s1`
* It picks a random node, such as Node 1, and sends a query to node 1
* It aggregates the `s1` (local) and `s2` results to serve the request

Note that the current logic never queries more than a single replica per shard, meaning that the CL is not respected for the search itself. It is only respected for the objects returned by the search. <- This is an assumption, might require verification.

## Example 2 (with new flag set - all nodes healthy)
* Same shard / node distribution as above
* A vector search comes in at Node 4 which makes node 4 the coordinator
* Node 4 has a local copy of `s2`, but we're interested in all copies of `s2`, as well as all copies of `s1`
* Node 4 sends a remote query to all other nodes
* Node 4 aggregates (and de-duplicates) the results and serves the request to the user

## Example 2 (with new flag set - CL is QUORUM, but node 3 is down)
* Same shard / node distribution as above
* A vector search comes in at Node 4 which makes node 4 the coordinator
* Node 4 has a local copy of `s2`, but we're interested in all copies of `s2`, as well as all copies of `s1`
* Node 4 sends a remote query to all other nodes
* Node 3 cannot respond, therefore we are missing a copy of `s1`
* We still have two other copies of `s1`, one from Node 1, another from Node 5, therefore we can still reach a QUORUM
* Node 4 aggregates (and de-duplicates) the results and serves the request to the user

## Example 3(with new flag set - CL is QUORUM, but node 3 and node 1 are down)
* Same shard / node distribution as above
* A vector search comes in at Node 4 which makes node 4 the coordinator
* Node 4 has a local copy of `s2`, but we're interested in all copies of `s2`, as well as all copies of `s1`
* Node 4 sends a remote query to all other nodes
* Node 1 cannot respond, therefore we are missing a copy of `s1`
* Node 3 cannot respond, therefore we are missing a copy of `s1`
* We only have a 1/3 copies for `s1`, therefore we cannot reach a QUORUM
* The request fails

## Example 4 (with new flag set - CL is QUORUM, but node 2 and node 3 are down)
* Same shard / node distribution as above
* A vector search comes in at Node 4 which makes node 4 the coordinator
* Node 4 has a local copy of `s2`, but we're interested in all copies of `s2`, as well as all copies of `s1`
* Node 4 sends a remote query to all other nodes
* Node 2 cannot respond, therefore we are missing a copy of `s2`
* Node 3 cannot respond, therefore we are missing a copy of `s1`
* We have
    * 2/3 copies of `s1` -> QUORUM is reached
    * 2/3 copies of `s2` -> QUORUM is reached 
* Request succeeds

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by Wert1996** [comment]
Hey, I would like to work on this issue. Let me know if it has already been picked up by someone.

**Comment by dirkkul** [comment]
I think this is implemented - closing it but please reopen in case some parts are missing
