### ISSUE TITLE
batch.add_object() returns UUID in spite of import failure when using invalid HF API_KEY

### ISSUE THREAD

**Issue by FilippTrigub** [weaviate/weaviate#5335]
### How to reproduce this bug?

1. Set up a cluster
2. Configure a Huggingface index 
- I used: 
{'class': 'AudioChunkMultilingualE5largeinstruct',
 'vectorizer': 'text2vec-huggingface',
 'vectorIndexConfig': {'distance': 'cosine'},
 'moduleConfig': {'text2vec-huggingface': {'model': 'intfloat/multilingual-e5-large-instruct',
   'type': 'text'}},
 'properties': [{'name': 'content', 'dataType': ['text']},
  {'name': 'source', 'dataType': ['string']}]}
  
3. Set up an finegrained HF key WITHOUT permitting model inference
4. Import something
5. Observe UUID being returned, but no object being loaded into the index (cause HF key invalid)

### What is the expected behavior?

throw an error or a warning 

### What is the actual behavior?

UUID returned

### Server Version

1.25.5

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by dirkkul** [comment]
>. Observe UUID being returned, but no object being loaded into the index (cause HF key invalid)

batch is async, at the time you add it to the batch you only queue it locally. The client will send the object later and only then the server returns an error.

You can either:
- implement error handling like described here: https://weaviate.io/developers/weaviate/client-libraries/python#error-handling
- use data.insert/insert_many if you want/need immediate feedback

**Comment by FilippTrigub** [comment]
Thank you!

It is good to see that there is already an implementation.

It would then seem to me that my initial suggestion would essentially boil down to throwing an error if the collected number_errors > 0.

After all, if errors are caught, it would seem to me that if I upload anything, I want to believe that all of it was uploaded, if no error is thrown, and as you have perfectly demonstrated, this is possible, even with async. They could be thrown once the connection is closed, for example.

Best,

Filipp
