### ISSUE TITLE
Sandbox stuck in 97%, client cannot be made

### ISSUE THREAD

**Issue by LifeBoey** [weaviate/weaviate#5345]
### How to reproduce this bug?

I'm creating a sandbox and querying it and storing embeddings multiple, multiple times. I believe what's happening is that it's out of memory or that it's overloaded.

Regardless, now I'm unable to query it whatsoever. Weaviate refuses to start a client with it, and the dashboard shows it hanging and stuck at 97%, unable to be accessed or edited or even deleted.

![weaviate](https://github.com/weaviate/weaviate/assets/61004414/c2896b79-1780-4fbd-b3ee-865eda8e0a28)

### What is the expected behavior?

Weaviate to be able to create a client with the given URL and API key.

### What is the actual behavior?

raise WeaviateStartUpError(
weaviate.exceptions.WeaviateStartUpError: Weaviate did not start up in 5 seconds. Either the Weaviate URL https://07scjfynqigxsiv6scaufq.c0.europe-west3.gcp.weaviate.cloud is wrong or Weaviate did not start up in the interval given in 'startup_period'.

### Server Version

3.24.1

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by dudanogueira** [comment]
hi @LifeBoey !!

For any issues on our hosted Weaviate offering, the best place to ask for support is sending an email to support@weaviate.io

I will close this GH issue for now, but please, feel free to reach us at support any time!

Thanks!
