### ISSUE TITLE
Empty Array Response in GraphQL Search with Multi-Vector Schema in Weaviate

### ISSUE THREAD

**Issue by Myasir92** [weaviate/weaviate#5461]
### How to reproduce this bug?

I have created a collection in Weaviate where the vectorizer is set to "none." For each property of the object, I create multiple vectors and insert the object accordingly. However, when I perform a search using GraphQL, even with the exact text used during insertion, the response returns an empty array. Despite following the guidelines provided on the Weaviate website for multi-vector configurations (https://weaviate.io/developers/weaviate/config-refs/schema/multi-vector), I am still encountering this issue.

### Steps to Reproduce

1. **Collection Setup**: Created a collection with the vectorizer set to "none."
2. **Object Insertion**: Inserted objects with multiple vectors, each corresponding to different properties.
3. **GraphQL Search**: Performed a search using GraphQL with the same text vector used during insertion.

#### Schema Configuration

```json
{
  "class": "MyClass",
  "properties": [
    {
      "name": "property1",
      "dataType": ["text"]
    },
    {
      "name": "property2",
      "dataType": ["text"]
    }
  ],
  "vectorizer": "none"
}
```

#### Object Insertion

```json
{
  "class": "MyClass",
  "properties": {
    "property1": "text for property1",
    "property2": "text for property2"
  },
  "vectors": {
    "property1": [0.1, 0.2, 0.3, ...], // example vector
    "property2": [0.4, 0.5, 0.6, ...]  // example vector
  }
}
```

#### GraphQL Search Query
```
{
  Get {
    MyClass(
      nearVector: {
        vector: [0.1, 0.2, 0.3, ...]
      }
    ) {
      property1
      property2
    }
  }
}
```

### Observations

- The response returns an empty array, indicating no matches found.

### Request for Assistance

Could you please provide guidance on why the search is returning an empty array and how to resolve this issue?

Thank you for your assistance.

### What is the expected behavior?

The search should return the relevant objects that match the search text.

### What is the actual behavior?

The search returns an empty array.

### Supporting information

- Followed the guidelines provided on the Weaviate website for multi-vector configurations. (https://weaviate.io/developers/weaviate/config-refs/schema/multi-vector)
- The vectors are properly assigned during object insertion.
- The search text used in GraphQL matches exactly with the inserted text.

### Server Version

1.25.4

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by Myasir92** [comment]
@alpe @harrlight00 @dandv 
Looking forward to your response.

**Comment by Myasir92** [comment]
@donomii 
Can you please look into it?

**Comment by dirkkul** [comment]
```
{
  "class": "MyClass",
  "properties": {
    "property1": "text for property1",
    "property2": "text for property2"
  },
  "vectors": {
    "property1": [0.1, 0.2, 0.3, ...], // example vector
    "property2": [0.4, 0.5, 0.6, ...]  // example vector
  }
}
```

You need to create named vectors like described here:https://weaviate.io/developers/weaviate/manage-data/collections#define-multiple-named-vectors

Currently you are:
- creating a single "old-style" vector 
- adding named vectors in your object

Here is a PR that adds validation and will return a proper error in case this happens: https://github.com/weaviate/weaviate/pull/6045
