### ISSUE TITLE
"Like" and "Equal" Operator not working on chinese text?

### ISSUE THREAD

**Issue by Vzhangs** [weaviate/weaviate#5486]
### How to reproduce this bug?

insert some text data with chinese, and search them using like or equal operator

### What is the expected behavior?

Use regex matching or exact matching.

### What is the actual behavior?

Just return Nothing

### Supporting information

I only want a regex match for Chinese, but the Like and Equal operators don't seem to match my target, even though my input and the target are exactly the same.

### Server Version

The latest Docker image from two months ago

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by donomii** [comment]
Could we get a few more details about your configuration?  Which tokeniser are you using?  Can you post your entire schema? (It will be visible to the public, you can also mail it to us).
And if you could also share your query, so we can try to reproduce it

**Comment by Vzhangs** [comment]
![截屏2024-07-31 15 49 31](https://github.com/user-attachments/assets/6b0643b9-c9bf-4cf6-82c6-589a8e511e1e)
i just created a normal text Property and use fetch_objects
```python
collection.query.fetch_objects(
            filters=Filter.by_property("department_name").like("*部*"),
            return_properties=require_properties,
            limit=limit
        )
```

**Comment by donomii** [comment]
Can you give an example of the data you are trying to match?

**Comment by dirkkul** [comment]
closing for lack of response
