### ISSUE TITLE
LIMIT_RESOURCES uses wrong number of cpus

### ISSUE THREAD

**Issue by landorg** [weaviate/weaviate#5537]
### How to reproduce this bug?
Found this while debugging this: https://github.com/weaviate/weaviate/issues/5214
Run weaviate on a multicore system with `LIMIT_RESOURCES=true` and `GOMAXPROCS` unset.
In the logs:
```
{"cores":1,"level":"warning","msg":"GOMAXPROCS not set, and unable to read from cgroups, setting to number of cores","time":"2024-08-06T08:49:45Z"}
```
It's using only 1 core instead of nCores-1 as documented.

### What is the expected behavior?

Use n-1 cores.
Documentation:

> LIMIT_RESOURCES: When set to true, Weaviate automatically limits its resource usage. It sets memory usage to 80% of the total memory and uses all but one CPU core. It overrides any GOMEMLIMIT values but respects GOMAXPROCS settings.

### What is the actual behavior?

Uses 1 core

### Supporting information

looking at the [getCores](https://github.com/weaviate/weaviate/blob/64cf510427cacb1a5ac444192bd575b38eccd086/adapters/handlers/rest/configure_api.go#L139-L140) function I think there might be the bug.

```go
func getCores() (int, error) {
	cpuset, err := os.ReadFile("/sys/fs/cgroup/cpuset/cpuset.cpus")
	if err != nil {
		return 0, errors.Wrap(err, "read cpuset")
	}

	cores := strings.Split(strings.TrimSpace(string(cpuset)), ",")
	return len(cores), nil
}
```
[link](https://github.com/weaviate/weaviate/blob/6fd24322f15ecf46d40e1e35754b524fe96e61f5/adapters/handlers/rest/configure_api.go#L137-L146)
In my environments this /sys path returns `0-7` for 8 cores. That function returns then 1 in any case.

And also not sure if the logic here or log messages are correct:
```go
			cores, err := getCores()
			if err == nil {
				appState.Logger.WithField("cores", cores).
					Warn("GOMAXPROCS not set, and unable to read from cgroups, setting to number of cores")
				goruntime.GOMAXPROCS(cores)
			} else {
				cores = goruntime.NumCPU() - 1
				if cores > 0 {
					appState.Logger.WithField("cores", cores).
						Warnf("Unable to read from cgroups: %v, setting to max cores to: %v", err, cores)
					goruntime.GOMAXPROCS(cores)
				}
			}
```
[link](https://github.com/weaviate/weaviate/blob/6fd24322f15ecf46d40e1e35754b524fe96e61f5/adapters/handlers/rest/configure_api.go#L1226-L1239)

### Server Version

v1.26.1

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by andrewisplinghoff** [comment]
There's an open Pull Request for fixing this here: https://github.com/weaviate/weaviate/pull/5606

**Comment by dirkkul** [comment]
merged, should be fixed in next version
