### ISSUE TITLE
Tenants can't get created while a node is down

### ISSUE THREAD

**Issue by jfrancoa** [weaviate/weaviate#5565]
### How to reproduce this bug?

To reproduce this issue,
1. Create a three node cluster, you can use `tools/dev/run_dev_server.sh` script
```
./tools/dev/run_dev_server.sh 
./tools/dev/run_dev_server.sh second-node
./tools/dev/run_dev_server.sh third-node
```
2. Throw one of the nodes down: Ctrl+C in one of the running services
3. Create a multitenant class with RF 3 using the test_scripts from [tools](https://github.com/weaviate/tools/tree/main/test_scripts):
```
./create_class.py --replication_factor 3 --multitenant
```
4. Create one tenant for that class:
```
./create_tenants.py --number_tenants 1 --state active
```

The creation fails with:
```
./create_tenants.py --number_tenants 1 --state active
Failed to create tenants: Collection tenants may not have been added properly for Movies! Unexpected status code: 422, with response body: {'error': [{'message': 'updating schema: TYPE_ADD_TENANT: get partitions: not enough replicas: found 2 want 3'}]}.
```

This could be expected pre-RAFT, but with RAFT it should be possible to create tenants while one node is down, as well as it is possible to create a class.

### What is the expected behavior?

Tenants can get created with a node down.

### What is the actual behavior?

Tenants don't get created with a node being down.

### Server Version

1.26.1

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by moogacs** [comment]
resolved 
https://github.com/weaviate/weaviate/pull/5573
https://github.com/weaviate/weaviate/pull/5577
https://github.com/weaviate/weaviate/pull/5564
