### ISSUE TITLE
Improve Metrics for Batches

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#5673]
### Describe your feature request

* objects per batch
* tenants per batch
* batch size in bytes (both for grpc and REST)
* `total_api_level` equivalent for grpc (currently only exists for REST)

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by dirkkul** [comment]
linked PR says "Closes *this issue*"
