### ISSUE TITLE
Releases for macOS were missing from v1.25.13

### ISSUE THREAD

**Issue by suzuki-shunsuke** [weaviate/weaviate#5689]
Pre-built binaries for macOS were missing from v1.25.13.

https://github.com/weaviate/weaviate/releases/tag/v1.25.13

<img width="1003" alt="image" src="https://github.com/user-attachments/assets/a8f2cf6d-9288-419b-9031-019d0d0e7eb0">

Is this expected? If not, could you release pre-built binaries for macOS?

**Comment by antas-marcin** [comment]
@suzuki-shunsuke thank you for raising this. Mac binaries have been added to [v1.25.13](https://github.com/weaviate/weaviate/releases/tag/v1.25.13)
