### ISSUE TITLE
Weaviate console no longer working for localhost

### ISSUE THREAD

**Issue by cmedianu** [weaviate/weaviate#5855]
### How to reproduce this bug?

Go to https://console.weaviate.cloud/
Option to connect to localhost not visible

### What is the expected behavior?

Be able to connect to localhost as in the training videos

### What is the actual behavior?

Inability to connect to  localhost

### Server Version

not relevant

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by flipace** [comment]
@cmedianu which video(s) specifically are you referring to? There have been some UI overhauls - you can still connect to localhost by choosing "Add external cluster" and adding the localhost details.

![CleanShot 2024-09-23 at 12 49 18@2x](https://github.com/user-attachments/assets/ad1c21b1-407e-40b7-9394-dc32bf83c64d)

**Comment by cmedianu** [comment]
Hi @flipace. Thanks for getting back to me.  This was the video:
https://www.youtube.com/watch?v=L0Y_zZR8FRI&t=1365s

![image](https://github.com/user-attachments/assets/15e35d51-1a33-494d-b161-be19f6752de6)


It's great to hear the console still supports localhost, it's just less obvious than before and now it requires logging in.

Is it still a free feature, or will it go away after my 7 days trial expires?

Thanks!

**Comment by flipace** [comment]
Thanks for the hint - maybe some overlays/infos could be added on top to make it clear that it's still working, but just a little different in wording :)

> Is it still a free feature, or will it go away after my 7 days trial expires?

WCS can be used for free for your self-hosted instances at this time. I'm not aware of any plans to change this (but i'm just a random user of the project too 😉 ). For just browsing the collections, you can also use any other GraphQL client (ie https://altairgraphql.dev/ or self-host graphiql) and point it to your weaviate instance (like `http://weaviate.docker-config.orb.local/v1/graphql`), then you don't need togo through WCS.

**Comment by cmedianu** [comment]
@flipace , thanks for the info! 

I started using the GraphQL plugin that comes with IntelliJ, works pretty good!

Thanks!
