### ISSUE TITLE
after upgrade 1.26.1 to 1.26.4, all data lost except schema

### ISSUE THREAD

**Issue by smoothdvd** [weaviate/weaviate#5869]
### How to reproduce this bug?

upgrade weaviate 1.26.1 to 1.26.4 in docker compose

### What is the expected behavior?

keep data

### What is the actual behavior?

data lost

### Supporting information

weaviate-1  | {"action":"startup","build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","default_vectorizer_module":"none","level":"info","msg":"the default v
ectorizer modules is set to \"none\", as a result all new schema classes without an explicit vectorizer setting, will use this vectorizer","time":"2024-09-23T03:26:32Z"}
weaviate-1  | {"action":"startup","auto_schema_enabled":true,"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"auto schema enabled s
etting is set to \"true\"","time":"2024-09-23T03:26:32Z"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"No resource limits set, weaviate will use all available memory and
CPU. To limit resources, set LIMIT_RESOURCES=true","time":"2024-09-23T03:26:32Z"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"module offload-s3 is enabled","time":"2024-09-23T03:26:32Z"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"open cluster service","servers":{"node1":8300},"time":"2024-09-23T0
3:26:32Z"}
weaviate-1  | {"address":"172.22.0.5:8301","build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"starting cloud rpc server ...","time":"
2024-09-23T03:26:32Z"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"starting raft sub-system ...","time":"2024-09-23T03:26:32Z"}
weaviate-1  | {"address":"172.22.0.5:8300","build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"tcp transport","tcpMaxPool":3,"tcpTimeo
ut":10000000000,"time":"2024-09-23T03:26:32Z"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"loading local db","time":"2024-09-23T03:26:32Z"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"local DB successfully loaded","time":"2024-09-23T03:26:32Z"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"schema manager loaded","n":0,"time":"2024-09-23T03:26:32Z"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","metadata_only_voters":false,"msg":"construct a new raft node","name":"nod
e1","time":"2024-09-23T03:26:32Z"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","id":"12-39-1727059869905","last-index":39,"last-term":12,"level":"info","msg":"starting
restore from snapshot","size-in-bytes":82526,"time":"2024-09-23T03:26:32Z"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"restoring schema from snapshot","time":"2024-09-23T03:26:32Z"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"successfully restored schema from snapshot","time":"2024-09-23T03:2
6:32Z"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"reload local db: update schema ...","time":"2024-09-23T03:26:32Z"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","index":"Assets","level":"info","msg":"reload local index","time":"2024-09-23T03:26:32Z"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","index":"Kpkp_H14","level":"info","msg":"reload local index","time":"2024-09-23T03:26:33Z
"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","index":"Kpkp_L14","level":"info","msg":"reload local index","time":"2024-09-23T03:26:33Z
"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","index":"NewspaperArticle","level":"info","msg":"reload local index","time":"2024-09-23T0
3:26:33Z"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","last_applied_index":39,"last_snapshot_index":39,"last_store_log_applied_index":39,"level
":"info","msg":"successfully reloaded indexes from snapshot","n":4,"time":"2024-09-23T03:26:34Z"}
weaviate-1  | {"action":"","build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","id":"12-39-1727059869905","last-index":39,"last-term":12,"level":"info","msg
":"snapshot restore progress","percent-complete":"[100.00]%","read-bytes":82526,"size-in-bytes":82526,"time":"2024-09-23T03:26:34Z"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","id":"12-39-1727059869905","last-index":39,"last-term":12,"level":"info","msg":"restored
from snapshot","size-in-bytes":82526,"time":"2024-09-23T03:26:34Z"}
weaviate-1  | {"action":"raft","build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","index":1,"level":"info","msg":"raft initial configuration","servers":"[[
{Suffrage:Voter ID:node1 Address:172.22.0.3:8301}]]","time":"2024-09-23T03:26:34Z"}
weaviate-1  | {"action":"raft_cluster_recovery","build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","existed_single_cluster_node":{"Suffrage":0,"ID":"node1"
,"Address":"172.22.0.3:8301"},"level":"info","msg":"perform cluster recovery","new_single_cluster_node":{"Suffrage":0,"ID":"node1","Address":"172.22.0.5:8301"},"time":"2024-09-23T03:26:34Z"}
weaviate-1  | {"action":"raft","build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","follower":{},"leader-address":"","leader-id":"","level":"info","msg":"ra
ft entering follower state","time":"2024-09-23T03:26:34Z"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"restoring schema from snapshot","time":"2024-09-23T03:26:34Z"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"successfully restored schema from snapshot","time":"2024-09-23T03:2
6:34Z"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"reload local db: update schema ...","time":"2024-09-23T03:26:34Z"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","index":"Assets","level":"info","msg":"reload local index","time":"2024-09-23T03:26:34Z"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","index":"Kpkp_H14","level":"info","msg":"reload local index","time":"2024-09-23T03:26:34Z
"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","index":"Kpkp_L14","level":"info","msg":"reload local index","time":"2024-09-23T03:26:34Z
"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","index":"NewspaperArticle","level":"info","msg":"reload local index","time":"2024-09-23T0
3:26:34Z"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","last_applied_index":39,"last_snapshot_index":39,"last_store_log_applied_index":39,"level
":"info","msg":"successfully reloaded indexes from snapshot","n":4,"time":"2024-09-23T03:26:34Z"}
weaviate-1  | {"action":"","build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","id":"12-39-1727059869905","last-index":39,"last-term":12,"level":"info","msg
":"snapshot restore progress","percent-complete":"[100.00]%","read-bytes":82526,"size-in-bytes":82526,"time":"2024-09-23T03:26:34Z"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"persisting snapshot","time":"2024-09-23T03:26:34Z"}
weaviate-1  | 2024-09-23T03:26:34.160Z [INFO]  snapshot: creating new snapshot: path=/var/lib/weaviate/raft/snapshots/15-42-1727061994160.tmp
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","id":"15-42-1727061994160","last-index":42,"last-term":15,"level":"info","msg":"starting
restore from snapshot","size-in-bytes":82708,"time":"2024-09-23T03:26:34Z"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"restoring schema from snapshot","time":"2024-09-23T03:26:34Z"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"successfully restored schema from snapshot","time":"2024-09-23T03:2
6:34Z"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"reload local db: update schema ...","time":"2024-09-23T03:26:34Z"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","index":"Assets","level":"info","msg":"reload local index","time":"2024-09-23T03:26:34Z"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","index":"Kpkp_H14","level":"info","msg":"reload local index","time":"2024-09-23T03:26:34Z
"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","index":"Kpkp_L14","level":"info","msg":"reload local index","time":"2024-09-23T03:26:34Z
"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","index":"NewspaperArticle","level":"info","msg":"reload local index","time":"2024-09-23T0
3:26:34Z"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","last_applied_index":39,"last_snapshot_index":42,"last_store_log_applied_index":39,"level
":"info","msg":"successfully reloaded indexes from snapshot","n":4,"time":"2024-09-23T03:26:34Z"}
weaviate-1  | {"action":"","build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","id":"15-42-1727061994160","last-index":42,"last-term":15,"level":"info","msg
":"snapshot restore progress","percent-complete":"[100.00]%","read-bytes":82708,"size-in-bytes":82708,"time":"2024-09-23T03:26:34Z"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","id":"15-42-1727061994160","last-index":42,"last-term":15,"level":"info","msg":"restored
from snapshot","size-in-bytes":82708,"time":"2024-09-23T03:26:34Z"}
weaviate-1  | {"action":"raft","build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","index":1,"level":"info","msg":"raft initial configuration","servers":"[[
{Suffrage:Voter ID:node1 Address:172.22.0.5:8301}]]","time":"2024-09-23T03:26:34Z"}
weaviate-1  | {"action":"raft","build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","follower":{},"leader-address":"","leader-id":"","level":"info","msg":"ra
ft entering follower state","time":"2024-09-23T03:26:34Z"}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","last_snapshot_index":42,"last_store_applied_index_on_start":39,"level":"info","msg":"raf
t node constructed","raft_applied_index":42,"raft_last_index":42,"time":"2024-09-23T03:26:34Z"}
weaviate-1  | {"action":"hnsw_prefill_cache_async","build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"not waiting for vector cache pr
efill, running in background","time":"2024-09-23T03:26:34Z","wait_for_cache_prefill":false}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"Completed loading shard assets_thiWHvUbXgpP in 2.102396ms","time":"
2024-09-23T03:26:34Z"}
weaviate-1  | {"action":"hnsw_vector_cache_prefill","build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","count":3000,"index_id":"main","level":"info","limit
":1000000000000,"msg":"prefilled vector cache","time":"2024-09-23T03:26:34Z","took":152298}
weaviate-1  | {"action":"lsm_recover_from_active_wal","build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","class":"Kpkp_H14","index":"kpkp_h14","level":"war
ning","msg":"empty write-ahead-log found. Did weaviate crash prior to this or the tenant on/loaded from the cloud? Nothing to recover from this file.","path":"/var/lib/weaviate/kpkp_h14/dPp8tIvvoomW/lsm/property__id/seg
ment-1722344810317211731","shard":"dPp8tIvvoomW","time":"2024-09-23T03:26:34Z"}
weaviate-1  | {"action":"lsm_recover_from_active_wal","build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","class":"Kpkp_H14","index":"kpkp_h14","level":"war
ning","msg":"empty write-ahead-log found. Did weaviate crash prior to this or the tenant on/loaded from the cloud? Nothing to recover from this file.","path":"/var/lib/weaviate/kpkp_h14/dPp8tIvvoomW/lsm/property_post_id
/segment-1722344810315124232","shard":"dPp8tIvvoomW","time":"2024-09-23T03:26:34Z"}
weaviate-1  | {"action":"lsm_recover_from_active_wal","build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","class":"Kpkp_H14","index":"kpkp_h14","level":"war
ning","msg":"empty write-ahead-log found. Did weaviate crash prior to this or the tenant on/loaded from the cloud? Nothing to recover from this file.","path":"/var/lib/weaviate/kpkp_h14/dPp8tIvvoomW/lsm/objects/segment-
1722344810314197506","shard":"dPp8tIvvoomW","time":"2024-09-23T03:26:34Z"}
weaviate-1  | {"action":"lsm_recover_from_active_wal","build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","class":"Kpkp_H14","index":"kpkp_h14","level":"war
ning","msg":"empty write-ahead-log found. Did weaviate crash prior to this or the tenant on/loaded from the cloud? Nothing to recover from this file.","path":"/var/lib/weaviate/kpkp_h14/dPp8tIvvoomW/lsm/property_image/s
egment-1722344810315986353","shard":"dPp8tIvvoomW","time":"2024-09-23T03:26:34Z"}
weaviate-1  | {"action":"lsm_recover_from_active_wal","build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","class":"Kpkp_H14","index":"kpkp_h14","level":"war
ning","msg":"empty write-ahead-log found. Did weaviate crash prior to this or the tenant on/loaded from the cloud? Nothing to recover from this file.","path":"/var/lib/weaviate/kpkp_h14/dPp8tIvvoomW/lsm/property_image_s
earchable/segment-1722344810316853701","shard":"dPp8tIvvoomW","time":"2024-09-23T03:26:34Z"}
weaviate-1  | {"action":"hnsw_prefill_cache_async","build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"not waiting for vector cache pr
efill, running in background","time":"2024-09-23T03:26:34Z","wait_for_cache_prefill":false}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"Completed loading shard kpkp_h14_dPp8tIvvoomW in 140.114645ms","tim
e":"2024-09-23T03:26:34Z"}
weaviate-1  | {"action":"hnsw_prefill_cache_async","build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"not waiting for vector cache pr
efill, running in background","time":"2024-09-23T03:26:34Z","wait_for_cache_prefill":false}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"Completed loading shard kpkp_l14_HFl0b8axtgRe in 507.114µs","time":
"2024-09-23T03:26:34Z"}
weaviate-1  | {"action":"hnsw_vector_cache_prefill","build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","count":3000,"index_id":"main","level":"info","limit
":1000000000000,"msg":"prefilled vector cache","time":"2024-09-23T03:26:34Z","took":43757}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","docker_image_tag":"1.26.4","level":"info","msg":"configured versions","server_version":"
1.26.4","time":"2024-09-23T03:26:34Z"}
weaviate-1  | {"action":"grpc_startup","build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"grpc server listening at [::]:50051","time"
:"2024-09-23T03:26:34Z"}
weaviate-1  | {"action":"restapi_management","build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","docker_image_tag":"1.26.4","level":"info","msg":"Serving w
eaviate at http://[::]:8080","time":"2024-09-23T03:26:34Z"}
weaviate-1  | {"action":"hnsw_prefill_cache_async","build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"not waiting for vector cache pr
efill, running in background","time":"2024-09-23T03:26:35Z","wait_for_cache_prefill":false}
weaviate-1  | {"build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"Completed loading shard newspaperarticle_KiBwe29Gye4x in 6.279397ms
","time":"2024-09-23T03:26:35Z"}
weaviate-1  | {"action":"hnsw_vector_cache_prefill","build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","count":3000,"index_id":"main","level":"info","limit
":1000000000000,"msg":"prefilled vector cache","time":"2024-09-23T03:26:35Z","took":43914}
weaviate-1  | {"action":"hnsw_vector_cache_prefill","build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","count":132947,"index_id":"main","level":"info","lim
it":1000000000000,"msg":"prefilled vector cache","time":"2024-09-23T03:26:35Z","took":674717141}
weaviate-1  | {"action":"raft","build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","last-leader-addr":"","last-leader-id":"","level":"warning","msg":"raft h
eartbeat timeout reached, starting election","time":"2024-09-23T03:26:35Z"}
weaviate-1  | {"action":"raft","build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"raft entering candidate state","node":{},"term":16,
"time":"2024-09-23T03:26:35Z"}
weaviate-1  | {"action":"telemetry_push","build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"telemetry started","payload":"\u0026{Mach
ineID:34ae7634-c8b7-4147-940b-ef39d2b1ef88 Type:INIT Version:1.26.4 NumObjects:0 OS:linux Arch:amd64 UsedModules:[]}","time":"2024-09-23T03:26:35Z"}
weaviate-1  | {"action":"raft","build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"raft election won","tally":1,"term":16,"time":"2024
-09-23T03:26:35Z"}
weaviate-1  | {"action":"raft","build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","leader":{},"level":"info","msg":"raft entering leader state","time":"202
4-09-23T03:26:35Z"}
weaviate-1  | {"action":"bootstrap","build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"node reporting ready, node has probably recove
red cluster from raft config. Exiting bootstrap process","time":"2024-09-23T03:26:35Z"}
weaviate-1  | {"address":"172.22.0.5:8300","build_git_commit":"584532a","build_go_version":"go1.21.13","build_image_tag":"1.26.4","build_wv_version":"1.26.4","level":"info","msg":"current Leader","time":"2024-09-23T03:2
6:36Z"}

### Server Version

1.26.4

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by dirkkul** [comment]
Hello @smoothdvd 

I am verysorry that this happened to you :(
We identified the problem and released a fix a couple of days ago. Here is a larger explanation of what happened: https://forum.weaviate.io/t/important-bug-fix-available/5290

**Comment by nikhilbansalgofynd** [comment]
Hi @dirkkul 

I am also facing the same issue on version 1.26.4. We are running in on k8s cluster. Whenever our pod is restarted by any chance, all our data gets lost. I wanted to know the steps of how can we upgrade it to latest or any stable version. During the upgrade as well, we are facing data loss in our UAT environment. And getting the error logs as below. We can't bear any data loss on production. 


{"action":"lsm_recover_from_active_wal","build_git_commit":"ab0312d","build_go_version":"go1.22.8","build_image_tag":"1.26.6","build_wv_version":"1.26.6","class":"Org_8i160mgl4qfy3ntia5fa6_KnowledgeBase","index":"org_8i160mgl4qfy3ntia5fa6_knowledgebase","level":"warning","msg":"empty write-ahead-log found. Did weaviate crash prior to this or the tenant on/loaded from the cloud? Nothing to recover from this file.","path":"/var/lib/weaviate/org_8i160mgl4qfy3ntia5fa6_knowledgebase/EC68XSym6TBf/lsm/property_text/segment-1738865234492522621","shard":"EC68XSym6TBf","time":"2025-02-06T18:10:44Z"}
{"action":"lsm_recover_from_active_wal","build_git_commit":"ab0312d","build_go_version":"go1.22.8","build_image_tag":"1.26.6","build_wv_version":"1.26.6","class":"Org_8i160mgl4qfy3ntia5fa6_KnowledgeBase","index":"org_8i160mgl4qfy3ntia5fa6_knowledgebase","level":"warning","msg":"empty write-ahead-log found. Did weaviate crash prior to this or the tenant on/loaded from the cloud? Nothing to recover from this file.","path":"/var/lib/weaviate/org_8i160mgl4qfy3ntia5fa6_knowledgebase/EC68XSym6TBf/lsm/property_loc_lines_from/segment-1738865234492413541","shard":"EC68XSym6TBf","time":"2025-02-06T18:10:44Z"}
{"action":"lsm_recover_from_active_wal","build_git_commit":"ab0312d","build_go_version":"go1.22.8","build_image_tag":"1.26.6","build_wv_version":"1.26.6","class":"Org_8i160mgl4qfy3ntia5fa6_KnowledgeBase","index":"org_8i160mgl4qfy3ntia5fa6_knowledgebase","level":"warning","msg":"empty write-ahead-log found. Did weaviate crash prior to this or the tenant on/loaded from the cloud? Nothing to recover from this file.","path":"/var/lib/weaviate/org_8i160mgl4qfy3ntia5fa6_knowledgebase/EC68XSym6TBf/lsm/property_blobType_searchable/segment-1738865234495078941","shard":"EC68XSym6TBf","time":"2025-02-06T18:10:44Z"}
{"action":"lsm_recover_from_active_wal","build_git_commit":"ab0312d","build_go_version":"go1.22.8","build_image_tag":"1.26.6","build_wv_version":"1.26.6","class":"Org_8i160mgl4qfy3ntia5fa6_KnowledgeBase","index":"org_8i160mgl4qfy3ntia5fa6_knowledgebase","level":"warning","msg":"empty write-ahead-log found. Did weaviate crash prior to this or the tenant on/loaded from the cloud? Nothing to recover from this file.","path":"/var/lib/weaviate/org_8i160mgl4qfy3ntia5fa6_knowledgebase/EC68XSym6TBf/lsm/property_source_searchable/segment-1738865234495201051","shard":"EC68XSym6TBf","time":"2025-02-06T18:10:44Z"}
{"action":"lsm_recover_from_active_wal","build_git_commit":"ab0312d","build_go_version":"go1.22.8","build_image_tag":"1.26.6","build_wv_version":"1.26.6","class":"Org_8i160mgl4qfy3ntia5fa6_KnowledgeBase","index":"org_8i160mgl4qfy3ntia5fa6_knowledgebase","level":"warning","msg":"empty write-ahead-log found. Did weaviate crash prior to this or the tenant on/loaded from the cloud? Nothing to recover from this file.","path":"/var/lib/weaviate/org_8i160mgl4qfy3ntia5fa6_knowledgebase/EC68XSym6TBf/lsm/property_dataSourceSyncId_searchable/segment-1738865234493886731","shard":"EC68XSym6TBf","time":"2025-02-06T18:10:44Z"}
{"action":"lsm_recover_from_active_wal","build_git_commit":"ab0312d","build_go_version":"go1.22.8","build_image_tag":"1.26.6","build_wv_version":"1.26.6","class":"Org_8i160mgl4qfy3ntia5fa6_KnowledgeBase","index":"org_8i160mgl4qfy3ntia5fa6_knowledgebase","level":"warning","msg":"empty write-ahead-log found. Did weaviate crash prior to this or the tenant on/loaded from the cloud? Nothing to recover from this file.","path":"/var/lib/weaviate/org_8i160mgl4qfy3ntia5fa6_knowledgebase/EC68XSym6TBf/lsm/property_pageId_searchable/segment-1738865234494523281","shard":"EC68XSym6TBf","time":"2025-02-06T18:10:44Z"}
{"action":"lsm_recover_from_active_wal","build_git_commit":"ab0312d","build_go_version":"go1.22.8","build_image_tag":"1.26.6","build_wv_version":"1.26.6","class":"Org_8i160mgl4qfy3ntia5fa6_KnowledgeBase","index":"org_8i160mgl4qfy3ntia5fa6_knowledgebase","level":"warning","msg":"empty write-ahead-log found. Did weaviate crash prior to this or the tenant on/loaded from the cloud? Nothing to recover from this file.","path":"/var/lib/weaviate/org_8i160mgl4qfy3ntia5fa6_knowledgebase/EC68XSym6TBf/lsm/property_size/segment-1738865234491952791","shard":"EC68XSym6TBf","time":"2025-02-06T18:10:44Z"}
{"action":"lsm_recover_from_active_wal","build_git_commit":"ab0312d","build_go_version":"go1.22.8","build_image_tag":"1.26.6","build_wv_version":"1.26.6","class":"Org_8i160mgl4qfy3ntia5fa6_KnowledgeBase","index":"org_8i160mgl4qfy3ntia5fa6_knowledgebase","level":"warning","msg":"empty write-ahead-log found. Did weaviate crash prior to this or the tenant on/loaded from the cloud? Nothing to recover from this file.","path":"/var/lib/weaviate/org_8i160mgl4qfy3ntia5fa6_knowledgebase/EC68XSym6TBf/lsm/property_path/segment-1738865234492076611","shard":"EC68XSym6TBf","time":"2025-02-06T18:10:44Z"}
{"action":"lsm_recover_from_active_wal","build_git_commit":"ab0312d","build_go_version":"go1.22.8","build_image_tag":"1.26.6","build_wv_version":"1.26.6","class":"Org_8i160mgl4qfy3ntia5fa6_KnowledgeBase","index":"org_8i160mgl4qfy3ntia5fa6_knowledgebase","level":"warning","msg":"empty write-ahead-log found. Did weaviate crash prior to this or the tenant on/loaded from the cloud? Nothing to recover from this file.","path":"/var/lib/weaviate/org_8i160mgl4qfy3ntia5fa6_knowledgebase/EC68XSym6TBf/lsm/property_type/segment-1738865234492375351","shard":"EC68XSym6TBf","time":"2025-02-06T18:10:44Z"}



Pls guide us with correct steps to upgrade it to stable version.

**Comment by parkerduckworth** [comment]
Hey @nikhilbansalgofynd, I see that the `build_wv_version` in the logs you shared is `1.26.6`. Just want to confirm: did you experience this dataloss on version 1.26.4, and already attempt to fix it by upgrading to 1.26.6, where the issue still persists?
