### ISSUE TITLE
raise WeaviateQueryError(e.details(), "GRPC search")  # pyright: ignore weaviate.exceptions.WeaviateQueryError: Query call with protocol GRPC search failed with message explorer: get class: vectorize params: could not vectorize input for collection DemoCollectionTest with search-type nearText. Make sure a vectorizer module is configured for this collection.

### ISSUE THREAD

**Issue by SurajPysquad** [weaviate/weaviate#5886]
issue with ollama local 
Here is the code.

client.collections.create(
                "DemoCollectionTest",
                vectorizer_config=[
                    Configure.Vectorizer.text2vec_ollama(
                        name="title_vector",
                        source_properties=["title"],
                        api_endpoint="http://host.docker.internal:11434",
                        # If using Docker, use this to contact your local Ollama instance
                        model="llama3",  # The model to use, e.g. "nomic-embed-text"
                    )
                ],
                generative_config=Configure.Generative.ollama(
                    api_endpoint="http://host.docker.internal:11434",
                    # If using Docker, use this to contact your local Ollama instance
                    model="llama3"  # The model to use, e.g. "phi3", or "mistral", "command-r-plus", "gemma"
                )
                # Additional parameters not shown
            )
            
            response = collection.query.near_text(
            query="test",  # The model provider integration will automatically vectorize the query
            limit=15
        )
        
        getting this error 
        raise WeaviateQueryError(e.details(), "GRPC search")  # pyright: ignore
weaviate.exceptions.WeaviateQueryError: Query call with protocol GRPC search failed with message explorer: get class: vectorize params: could not vectorize input for collection DemoCollectionTest with search-type nearText. Make sure a vectorizer module is configured for this collection.

**Comment by databyjp** [comment]
Hi @SurajPysquad, thank you for trying Weaviate. This looks like a support question. Would you mind posting this on our forum? :) 

If you could provide the full list of reproducible steps, that would make it easier to follow as well. Thank you!

https://forum.weaviate.io/c/support/6
