### ISSUE TITLE
Broken Link for Ollama Python Notebook in Integrations

### ISSUE THREAD

**Issue by sagungargs15** [weaviate/weaviate#5937]
### How to reproduce this bug?

https://github.com/weaviate/recipes/blob/main/integrations/ollama/local_rag.ipynb is broken.

Reference to Original Link from Post: https://www.linkedin.com/posts/weaviate-io_with-ollama-and-weaviate-you-can-easily-activity-7198709919494103040-rB2A/

### What is the expected behavior?

Link should work

### What is the actual behavior?

Link is Broken

### Server Version

Latest

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by CShorten** [comment]
Hey @sagungargs15! Here is the link to the notebook - https://github.com/weaviate/recipes/blob/main/weaviate-features/generative-search/ollama_local_rag.ipynb!

Thank you so much for flagging this!
