### ISSUE TITLE
[Tech Debt] Break up test `acceptance-tests-large` (`--acceptance-go-client-named-vectors`)

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#5951]
The test mentioned in the title runs 3 or 4 independent test suites in sequence. This is enough to push it over the default 10m timeout and as a result the timeout has been increased. To make the CICD pipeline faster, it would be better if this test was split up into multiple smaller test jobs that can run in parallel.

**Comment by melsonic** [comment]
Hey @etiennedi, can I work on this issue?

**Comment by moogacs** [comment]
Hi @melsonic  feel free to pick it up, looking forward for your PR :)

**Comment by melsonic** [comment]
sure @moogacs

**Comment by moogacs** [comment]
[PR](https://github.com/weaviate/weaviate/pull/6125) merged against 1.25
