### ISSUE TITLE
Diff behaviour for batch insert vs normal insert using named_vectors

### ISSUE THREAD

**Issue by projects-g** [weaviate/weaviate#6058]
### How to reproduce this bug?

4.9.0 for weaviate-client
image: cr.weaviate.io/semitechnologies/weaviate:stable-v1.25-32f7242

`questions = client.collections.create("questions")`

1)  No error

```
with questions.batch.dynamic() as batch:
    for i in range(5):
        img = [0.55] * 512
        txt = [0.25] * 512
        uuid = generate_uuid5(i)
        batch.add_object(
            properties={"i":i},
            vector={
                "image": img,
                "text": txt
            },
            uuid=uuid
        )
```

2) Error

```
for i in range(5):
    img = [0.55] * 512
    txt = [0.25] * 512
    uuid = generate_uuid5(i)
    questions.data.insert(
        properties={"i":i},
        vector={
            "image": img,
            "text": txt
        },
        uuid=uuid
    )
```

The message:
    
`UnexpectedStatusCodeError: Object was not added! Unexpected status code: 422, with response body: {'error': [{'message': 'invalid object: collection Questions is configured without multiple named vectors, but received named vectors:`
 

### What is the expected behavior?

Both behaviours should be the same.
both should fail or both should succeed

### What is the actual behavior?

DIff behaviour for same logic

### Server Version

cr.weaviate.io/semitechnologies/weaviate:stable-v1.25-32f7242

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by dirkkul** [comment]
Hello!

You need to check the batch for errors after you exit the context manager, see here: https://weaviate.io/developers/weaviate/client-libraries/python#error-handling

```
import weaviate

client = weaviate.connect_to_local()
questions = client.collections.create("questions5")
with questions.batch.dynamic() as batch:
    for i in range(5):
        img = [0.55] * 512
        txt = [0.25] * 512
        batch.add_object(
            properties={"i":i},
            vector={
                "image": img,
                "text": txt
            },
        )

assert len(questions.batch.failed_objects) == 5
```

this code snippet works and every object fails with the correct error message
