### ISSUE TITLE
Unknown argument \"nearText\" on field

### ISSUE THREAD

**Issue by V-yw** [weaviate/weaviate#6084]
### How to reproduce this bug?

version: '3.7'
services:
  weaviate:
    image: harbor.xxx.com/common/weaviate:1.27.0
    ports:
      - "8081:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=20
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - TRANSFORMERS_INFERENCE_API=http://xx.55.145.120:21992/encode  
      - ENABLE_MODULES=text2vec-transformers  
    volumes:
      - ./data:/var/lib/weaviate

The TRANSFORMERS_INFERENCE_API interface is OK, but when I was about to use the following curl interface to test whether weaviate is good, a problem occurred
curl -X POST "http://192.168.101.xx:8081/v1/graphql" -H "Content-Type: application/json" -d '{
"query": "{ Get { Article (nearText: {concepts: [\"Hello, World!\"]}) { text } } }"
}'
{"errors":[{"locations":[{"column":18,"line":1}],"message":"Unknown argument \"nearText\" on field \"Article\" of type \"GetObjectsObj\". Did you mean \"nearVector\" or \"nearObject\"?","path":null}]}

### What is the expected behavior?

ok

### What is the actual behavior?

Unknown argument \"nearText\" on field

### Server Version

1.27.0

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by dirkkul** [comment]
Hi, could you please make a [post in our support forum](https://forum.weaviate.io/)? I think this is a config issue and not a bug.

Thank you and please open a new issue if it turns out to be a bug!
