### ISSUE TITLE
Wrong Filter command for any_of

### ISSUE THREAD

**Issue by udjuraev-ipa** [weaviate/weaviate#6095]
### How to reproduce this bug?

Just check out section @ https://weaviate.io/developers/weaviate/search/filters

### What is the expected behavior?

Filter with `any of`
```
from weaviate.classes.query import Filter

jeopardy = client.collections.get("JeopardyQuestion")
response = jeopardy.query.fetch_objects(
    filters=(
        Filter.any_off([  # Combines the below with `&`
            Filter.by_property("points").greater_than(300),
            Filter.by_property("points").less_than(700),
            Filter.by_property("round").equal("Double Jeopardy!"),
        ])
    ),
    limit=5
)

for o in response.objects:
    print(o.properties)
```

### What is the actual behavior?

```
from weaviate.classes.query import Filter

jeopardy = client.collections.get("JeopardyQuestion")
response = jeopardy.query.fetch_objects(
    filters=(
        Filter.all_of([  # Combines the below with `&`
            Filter.by_property("points").greater_than(300),
            Filter.by_property("points").less_than(700),
            Filter.by_property("round").equal("Double Jeopardy!"),
        ])
    ),
    limit=5
)

for o in response.objects:
    print(o.properties)
```

### Server Version

Not applicable 

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by dirkkul** [comment]
should be fixed :)

We have a [separate repo for our website+docs](https://github.com/weaviate/weaviate-io/issues). In the future, could you add any issues there? :)
