### ISSUE TITLE
Headers X-Google-Api-Key and X-Google-Vertex-Api-Key don't work with Multi2VecGoogle and Palm

### ISSUE THREAD

**Issue by sebawita** [weaviate/weaviate#6206]
### How to reproduce this bug?

Tested with Weaviate Cloud, weaviate version:`1.26.7` and TypeScript client `3.2.1`.

When I work with `multi2vecGoogle` and `multi2vecPalm` modules, I should be able to provide my Vertex key with the following headers:
* `x-palm-api-key`
* `X-Google-Api-Key`
* `X-Google-Vertex-Api-Key`

However, only `x-palm-api-key` works, while the other two fail with the following error:
```
Query call with protocol gRPC failed with message: /weaviate.v1.Weaviate/Search UNKNOWN: explorer: get class: concurrentTargetVectorSearch): explorer: get class: vectorize search vector: vectorize params: vectorize params: vectorize keywords: remote client vectorize: Google API Key: no api key found neither in request header: X-Palm-Api-Key or X-Google-Api-Key or X-Google-Vertex-Api-Key or X-Google-Studio-Api-Key nor in environment variable under PALM_APIKEY or GOOGLE_APIKEY
```

> note: When I work with `text2VecGoogle` and `text2VecPalm,` all 3 headers seem to work.

## Reproduce steps
1. Connect to Weaviate using `X-Google-Vertex-Api-Key` header
2. Create a new collection with multi2vecGoogle vectorizer
3. Try to insert an object with an image -> this will throw an error

### What is the expected behavior?

All 3 headers should allow me to pass my Vertex key.

### What is the actual behavior?

Headers X-Google-Api-Key and X-Google-Vertex-Api-Key don't work with Multi2VecGoogle and Palm

### Server Version

1.26.7

### Weaviate Setup

Single Node

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by sebawita** [comment]
It looks like the issue is with Weaviate Cloud.
All 3 headers work with a Docker instance.

**Comment by sebawita** [comment]
It looks like the issue is with Weaviate Cloud.
All 3 headers work with a Docker instance.

**Comment by Stancobridge** [comment]
Am facing same issue with weaviate docker instance, but my case am using python and trying to set this header => X-Google-Studio-Api-Key.
