### ISSUE TITLE
"Get tenants" is retried for 20s on non-MT class

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#6261]
### How to reproduce this bug?

1. Create a 3-node cluster
2. Create a collection that does not use multi-tenancy
3. Try to list tenants

### What is the expected behavior?

The request fails immediately because the collection does not use multi-tenancy.

### What is the actual behavior?

The request takes 20s and retries multiple times and then eventually fails because the collection does not use multi-tenancy.

### Supporting information

Tested on `v1.25.24`

### Server Version

v1.25.24

### Weaviate Setup

Multi-Node Cluster

### Nodes count

3+

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by redouan-rhazouani** [comment]
Hi there,

I was able to reproduce the issue, and it has now been resolve. 
You can find the details of the fix in this [PR](https://github.com/weaviate/weaviate/pull/6458).
I've also tested the fix locally, and it works successfully.

Best,
Red
