### ISSUE TITLE
Vectorizing TEXTARRAY properties and nested properties

### ISSUE THREAD

**Issue by vats98754** [weaviate/weaviate#6313]
### Describe your feature request

I'm trying to vectorize TEXTARRAY and nested properties but it seems the default behavior is not to. Is there not a way to regex/parse your way down to the smallest unit (i.e. TEXT/string item), whether in an array or as a property within nested_properties, and vectorize these individual values to store as a collection of vector key to [vector...] values generically across objects and TEXTARRAYs?

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by dudanogueira** [comment]
hi @vats98754 !!

Thanks for opening a feature request.

However, **TEXTARRAY** is already vectorized. Check out this code:

```python
payload_url = "https://webhook.site/ec8436b5-4a54-4705-b8e0-95f50b81b9f6"
client.collections.delete("Test")
collection = client.collections.create(
    "Test",
    vectorizer_config=wvc.config.Configure.Vectorizer.text2vec_openai(
        base_url=payload_url
    ),
    properties=[
        wvc.config.Property(name="single", data_type=wvc.config.DataType.TEXT),
        wvc.config.Property(name="array", data_type=wvc.config.DataType.TEXT_ARRAY),
        wvc.config.Property(
            name="nested_property",
            data_type=wvc.config.DataType.OBJECT,
            nested_properties=[
                wvc.config.Property(
                    name="sub_property1",
                    data_type=wvc.config.DataType.TEXT
                ),
                wvc.config.Property(
                    name="sub_property2",
                    data_type=wvc.config.DataType.INT
                ),
                wvc.config.Property(
                    name="sub_property3",
                    data_type=wvc.config.DataType.TEXT_ARRAY
                )                
            ]
        )
    ]
)
collection.data.insert({
    "single": "text_single_value",
    "array": ["text1", "text2"],
    "nested_property": {"sub_property1": "somedata", "sub_property2": 123, "sub_property3": ["sub3_t1", "sub3_t2"]}
})
```
and this is the payload that is received:

```
{
  "input": [
    "Test array text1 array text2 single text_single_value"
  ],
  "model": "text-embedding-3-small",
  "dimensions": 1536
}
```
Indeed, the nested object is not vectorizable nor filterable. We have an issue covering this feature here:
https://github.com/weaviate/weaviate/issues/3694

In light of that, I will close this feature request, so we can funnel it to https://github.com/weaviate/weaviate/issues/3694

Please, consider leaving a thumbs up and any suggestion there. [It is already very high in our roadmap](https://weaviate.io/developers/weaviate/roadmap)

Thanks!
