### ISSUE TITLE
Error notified while server is running.

### ISSUE THREAD

**Issue by johnciocoiu** [weaviate/weaviate#64]
The following error pops up when the server is running.

```
transport: http2Client.notifyError got notified that the client transport was broken EOF.
```

**Comment by bobvanluijt** [comment]
https://github.com/GoogleCloudPlatform/google-cloud-go/issues/293#issuecomment-258167408

**Comment by bobvanluijt** [comment]
Maybe as solution: https://github.com/GoogleCloudPlatform/google-cloud-go/issues/293#issuecomment-293321701
