### ISSUE TITLE
Support for Voyage embedding multimodal model

### ISSUE THREAD

**Issue by PetrAPConsulting** [weaviate/weaviate#6506]
### Describe your feature request

Voyage AI embedding models are recommended embedders from Anthropic so probably many use them in LLM+RAG chatbots. Voyage released quite recently very interesting multimodal embedding model voyage-multimodal-3. This model is not currently in list of supported models. Maybe you could consider it. 

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by dudanogueira** [comment]
Discussion initiated here: https://forum.weaviate.io/t/support-for-voyage-embedding-multimodal-model/8955/2

Link to API: https://docs.voyageai.com/reference/multimodal-embeddings-api

**Comment by antas-marcin** [comment]
@PetrAPConsulting VoyageAI multimodal module is ready and will be released with `v1.25+` patch release versions.
