### ISSUE TITLE
List request should respond unique records

### ISSUE THREAD

**Issue by johnciocoiu** [weaviate/weaviate#78]
A list request now contains all historical items, but that is not correct. Just return the most recent item per ID.

**Comment by johnciocoiu** [comment]
@bobvanluijt, tried to fix this bug, but ran into a lot of problems. Should take a look together to fix this. I'll plan a meeting.

**Comment by johnciocoiu** [comment]
Looked into it with a colleague, but we think the only way to fix this is adding an extra column or extra table/kind, in which the most recent records are tracked with a boolean. There are no GROUP functions available in GQL.

**Comment by bobvanluijt** [comment]
This problem only lies in connectors that don't support grouping.

Current query datastore:
`query := datastore.NewQuery(f.kind).Filter("RefType =", refType).Filter("Deleted =", false).Order("-CreateTimeMs").Limit(limit)`. Returns the same UUID's but you only want the last one.

The solution, create new `kind` called: `weaviate_history`. When something is deleted, move it to history. This also means that the column `Deleted` can be removed.

**Comment by johnciocoiu** [comment]
Resolved problem with new kind in datastore-connection. All history items are added to the `weaviate_history` kind. Only the newest (unique) items/uuids exist in the `weaviate` `kind`.
