### ISSUE TITLE
Rollback schema changes if parts of it fail

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#846]
If creating a property or class fails, the name is blocked and cannot be used again.

There should be a rollback so that anything that was already changed on a failed request is removed again.

Based on our findings in #842, #843 and #844

**Comment by fefi42** [comment]
I had quite some trouble at the beginning importing schemas, just from syntax issues and stuff. Without a rollback this is a quite cumbersome. I think prioritizing this will speed up the schema creation and testing process.

**Comment by dirkkul** [comment]
I'm pretty sure this is resolved
