### ISSUE TITLE
"Word not in contextionary" error message is misleading

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#929]
The message reads like this
>  `Could not find the word ‘uom’ from the property ‘procStdUom’ in the class name ‘Classification’ in the contextionary. Consider using keywords to define the semantic meaning of this class.`

However, keywords are no longer a replacement for missing words after #856. Every word has to be present in the contextionary.

**Comment by bobvanluijt** [comment]
Is this still an issue @etiennedi ?

**Comment by etiennedi** [comment]
Not sure, I'll investigate.
