### ISSUE TITLE
Support "delete schema property" in >0.20.0

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#973]
Deleting a property is non-trivial with our >0.20.0 setup, as we need to make sure that every indexed document for this gets changed, i.e. we need a reindexing process.

**Comment by bobvanluijt** [comment]
FYI: Support request came in asking for this feature

**Comment by bobvanluijt** [comment]
Hi bot 👋

**Comment by etiennedi** [comment]
We need to really think about whether we want to support this, as it comes with quite a high implementation cost. Essentially what we need to do is this:

- Keep a log of which feature is deleted. Essentially just marking it as so. With this, it wouldn't appear in requests/searches anymore. However, the vector positions are not changed yet at this point.
- Periodically iterate over the entire database and delete this prop from every single object.
- If the property was part of the vectorization, we also need to re-vectorize every object without the deleted property.
- During the deletion the property name is essentially blocked, i.e. the user can't delete the property "foo" and immediately add a new property "foo" again if the db hasn't been cleaned up yet. On large datasets this could easily take days or weeks.

So while this is certainly possible, we should consider if the large effort is really worth it. There is a good reason why Databases, such as Elasticsearch explicitly **do not** support this: https://stackoverflow.com/a/16156873/5322199

**Comment by bobvanluijt** [comment]
Makes sense – let's park it for now (maybe in the future?). It should be removed accordingly from the API specs though :)

**Comment by etiennedi** [comment]
Ok, I'll try to get the removal in before the September 15 release.

**Comment by bobvanluijt** [comment]
Awesome - thanks (to avoid confusion, that's removal from the specs, right? 😉)

**Comment by etiennedi** [comment]
Yes, the feature itself is already not present at the moment ;-)

**Comment by bobvanluijt** [comment]
Haha, yeah, I just wanted to double-check because of the "remove" and "delete" ambiguity ;-)
